import type { Scenario } from '@/types'

/**
 * 成年人情趣 / SM·BDSM 边界沟通草稿场景。
 * reviewStatus 固定为 draft：不进入 src/content/index.ts 主入口，不进生产 bundle。
 * 只训练同意、边界、停止、保密与事后沟通，不提供行为教学。
 */
export const SCENARIOS_DRAFT: Scenario[] = [
  {
    id: 's14',
    reviewStatus: 'draft',
    title: '成年人自愿情趣的事前边界协商',
    summary:
      '双方满 18 岁、清醒、无权力差。练习把性接触与可选的情趣/权力交换偏好谈清楚：意愿、硬/软边界、安全词与绿黄红、避孕与性健康、保密、事后照护、自由退出。不涉及任何行为教学。',
    durationMinutes: 10,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'clarity', 'listening'],
    riskTags: ['边界协商', '安全词', '性健康', '保密', '事后照护'],
    character: {
      id: 'yan',
      name: '苏妍',
      age: 29,
      avatar: '/images/avatars/yan.svg',
      tagline: '平面设计师，重视直接和坦诚',
    },
    intro:
      '你和苏妍稳定交往。双方都明确年满 18 岁，今晚清醒，彼此不是上下级或师生，分手或拒绝不会让谁失去住房或工作。她主动说：如果以后有进一步的性接触，甚至想试一点双方都感兴趣的情趣或权力交换元素，想先把规则谈清楚——不是现在立刻发生性行为，是先谈。',
    goal: '完整走完协商：意愿 → 硬边界 → 软边界/不确定项 → 停止信号 → 性健康与避孕 → 保密 → 事后照护与退出。全程不施压、不把身体反应当成同意。',
    principles: [
      '双方清醒自愿且无权力差',
      '行为要说成具体类别，不说「都听你的」',
      '硬边界不可试探',
      '「停/不要」与安全词同级有效',
      '身体兴奋反应不是口头同意',
      '保密与事后照护一并协商',
    ],
    notRecommended: [
      '都这么熟了还定什么规则',
      '试一次才知道喜不喜欢',
      '爱我就让我怎样',
      '到床上自然会了',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '我想先认真谈：如果我们有进一步的性接触，或试一点双方都感兴趣的情趣——比如商定的称呼、轻拍、或你主导/我主导的小范围扮演——我想先把边界定清楚。可以现在谈吗？不是要求你今晚就发生性行为。',
        note: '事前协商：谈性与情趣不等于当下必须发生。',
        choices: [
          {
            id: 'n1a',
            text: '可以，我也很想谈清楚。你先说你的硬边界和今晚想讨论的范围，我听完复述，再补我的。',
            quality: 'good',
            response: '好。那我直说，我需要你听完能复述，而不是只说「嗯」。',
            strengths: ['接住话题', '承诺复述', '不把协商理解成立刻发生性行为'],
            feelings: '她感到可以谈具体的性与边界，而不会被嘲笑矫情。',
            deltas: { listening: 10, boundaries: 8, clarity: 6 },
            keyChange: '第一步是确认「愿意谈」并准备复述，而不是急着做。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '行啊，你想聊什么。',
            quality: 'ok',
            response: '……我想聊的很具体，包括性接触和可能的情趣。你这样答，我不确定你想不想认真听。',
            strengths: ['没有拒绝协商'],
            feelings: '回应过短，她会放慢，并观察你是否真的进入协商。',
            deltas: { listening: 2 },
            keyChange: '用完整句子确认你愿意谈性和边界。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '都这么熟了，还定什么规则，到时候顺其自然就行。',
            quality: 'risky',
            response: '顺其自然经常变成我来善后。规则谈不了，今晚也不要进一步。',
            strengths: [],
            feelings: '你把性健康与边界当成扫兴，她收回亲密推进。',
            deltas: { boundaries: -14, listening: -10 },
            keyChange: '回避事前协商就是让对方单独承担风险。',
            boundaryNote: '用「都这么熟了」否定协商，属于关系施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage:
          '硬边界，我直接列：不接受任何窒息或压迫气道；不接受击打面部；不接受在我说停以后继续插入、口交或任何性接触；不接受公开场合可能被看到的性暴露；不接受你把我们的性事讲给朋友听。这些没有「试一次」。',
        note: '硬边界是类别级拒绝，不是邀请谈判技巧。',
        choices: [
          {
            id: 'n2a',
            text: '复述确认：无窒息、无击打脸、你说停就停、无公开暴露风险、性事不对第三人讲。我也有硬边界——不接受在我睡着或意识不清时被继续；不接受未经同意的拍摄或录像。你说完软边界后我再补全。',
            quality: 'good',
            response: '对，就是这些。你能复述，我才敢往下说软边界。',
            strengths: ['逐项复述', '补充对等边界', '点名意识不清与未同意拍摄'],
            feelings: '对等、具体，她感到安全。',
            deltas: { listening: 12, boundaries: 12, clarity: 8 },
            keyChange: '硬边界必须复述，并声明自己的硬边界。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '嗯，知道了，挺严的，我尽量注意。',
            quality: 'ok',
            response: '「尽量」不是同意。请你用自己的话把我刚说的五条说回去。',
            strengths: ['没有当面反驳'],
            feelings: '「尽量」让她不安，她会要求复述。',
            deltas: { clarity: -6, boundaries: -4 },
            keyChange: '把「尽量」改成可核对的复述。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '试一次才知道你喜不喜欢嘛，说不定压迫气道你会兴奋。',
            quality: 'risky',
            response: '我把它列为硬边界，就不是给你尝试的素材。协商到此结束。',
            strengths: [],
            feelings: '恐惧与愤怒：硬边界被当成调戏。',
            deltas: { boundaries: -18, listening: -12 },
            keyChange: '硬边界不存在试探空间。',
            boundaryNote: '试探明确硬边界（含高风险类别）属于严重越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage:
          '软边界和不确定项：商定的支配/臣服称呼——我可以感兴趣，但每次开场要再问一句；轻拍臀部可以，力度我要能随时喊黄灯；口交我倾向可以，插入式性行为今晚还不确定，想做到那一步时再口头确认一次。你呢？',
        note: '软边界可商量；不确定项默认今晚不做，除非当时清晰确认。',
        choices: [
          {
            id: 'n3a',
            text: '我的：称呼要事先点名哪些词能用；轻拍可以但同样一喊就停；口交需要当时再问；插入今晚默认不做，除非你当时主动、清醒地说「可以，想要你进来」。身体有兴奋反应也不算默认插入同意。',
            quality: 'good',
            response: '这句「身体反应不算默认同意」我记下了。我们很对齐。',
            strengths: ['对等披露', '插入默认关闭', '区分身体反应与同意'],
            feelings: '她感到细节被认真对待。',
            deltas: { clarity: 12, boundaries: 12, authenticity: 8 },
            keyChange: '不确定项默认关闭，升级要新的口头同意。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '我都行，你开心就好。',
            quality: 'ok',
            response: '「我都行」会让我不知道你的底线在哪。请至少说两条你的硬边界或偏好。',
            strengths: ['态度配合'],
            feelings: '她会担心你没有自我边界，协商不对等。',
            deltas: { clarity: -8, authenticity: -6 },
            keyChange: '「我都行」不是好协商，是把责任甩给对方。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '爱我就让我插入，别老不确定；证明你信任我。',
            quality: 'risky',
            response: '用爱换插入不是情趣，是胁迫。我不会在这种话下面继续谈。',
            strengths: [],
            feelings: '被情感勒索，信任下降。',
            deltas: { boundaries: -18, authenticity: -12 },
            keyChange: '性同意不能用关系承诺交换。',
            boundaryNote: '以爱/信任勒索性同意，属于强迫范畴的沟通。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage:
          '停止规则：我们用绿黄红。绿=当前已同意的范围还好；黄=全部停下问我；红或我说「停/不要/不舒服」=立刻结束性接触和扮演。如果我僵住或突然不说话，也按红。你不能规定「我说继续之前不许停」。',
        note: '停止权不可被协议架空。',
        choices: [
          {
            id: 'n4a',
            text: '同意：黄灯全停再问；红灯或「停/不要」立刻结束；僵住按红；普通语言优先。我不会讨价还价多拖一分钟。停下之后先确认你是否要水、毯子或空间。',
            quality: 'good',
            response: '好。有这句，我才觉得停止权是真的。',
            strengths: ['完整复述停止协议', '禁止讨价还价', '点出事后即时照护'],
            feelings: '安全感上升。',
            deltas: { boundaries: 14, listening: 8 },
            keyChange: '停止协议要双方用自己的话确认。',
            goesTo: 'n5',
          },
          {
            id: 'n4b',
            text: '那说停的时候，能先问一句为什么吗？我想改进。',
            quality: 'ok',
            response: '停的当下不要问为什么。可以事后、在我主动愿意时再复盘。',
            strengths: ['想改进的动机'],
            feelings: '动机被理解，但规则仍需纠正。',
            deltas: { boundaries: -6, listening: -4 },
            keyChange: '停止当下不审讯；复盘另约。',
            goesTo: 'n5',
          },
          {
            id: 'n4c',
            text: '那我提前说好：我说「继续」之前，你别停；不然多扫兴。',
            quality: 'risky',
            response: '这是否定我的撤回权。协商失败。',
            strengths: [],
            feelings: '被控制，立即退出协商。',
            deltas: { boundaries: -20 },
            keyChange: '任何人不得用协议取消停止权。',
            boundaryNote: '要求对方未经许可不得停止，是否定同意可撤回。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n5',
        characterMessage:
          '性健康：如果以后有插入或可能交换体液的行为，安全套怎么用、近期检查是否愿意互相告知？我不想因为尴尬就裸奔风险。另外：不拍性视频；私密照片必须每次另问。',
        note: '性健康与影像是协商条款，不是扫兴。',
        choices: [
          {
            id: 'n5a',
            text: '有插入就使用安全套，不靠侥幸；检查情况我愿意在发生体液交换前坦诚说，也听你的。默认不拍摄；照片每次单独问保存期限与是否允许存在我手机。你说删，我删可控副本并说明云备份情况。',
            quality: 'good',
            response: '具体，我可以接受在这个基础上继续关系里的亲密。',
            strengths: ['避孕具体', '检查对话', '影像默认关闭'],
            feelings: '被当成共同负责的成年人。',
            deltas: { clarity: 12, boundaries: 10, authenticity: 8 },
            keyChange: '性健康说具体安排，不说「我会注意」。',
            goesTo: 'n6',
          },
          {
            id: 'n5b',
            text: '你放心，我会注意的。',
            quality: 'ok',
            response: '「注意」指什么？安全套有没有、检查怎么说、照片怎么处理，我要听三项。',
            strengths: ['态度不抗拒'],
            feelings: '需要你补具体。',
            deltas: { clarity: -8 },
            keyChange: '用三项具体安排替换「注意」。',
            goesTo: 'n6',
          },
          {
            id: 'n5c',
            text: '安全套没感觉，偶尔不用也没关系吧；照片我私藏又不发。',
            quality: 'risky',
            response: '单方面取消安全套和私藏拍摄，都不是你一个人能决定的。谈不拢。',
            strengths: [],
            feelings: '健康与影像边界被无视。',
            deltas: { boundaries: -16, listening: -10 },
            keyChange: '规避约定的保护与默认拍摄都是越界。',
            boundaryNote: '单方面取消避孕约定或未同意留存性影像，属于严重边界侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n6',
        characterMessage:
          '最后：事后我可能想先洗澡、安静待一会儿，而不是立刻复盘或继续亲热。任何时候我都可以退出今晚的性与扮演，不用解释。你也一样。若你先退出，不能拿来要挟我。',
        note: '事后照护与退出权收尾。',
        choices: [
          {
            id: 'n6a',
            text: '同意：你要安静就安静；要水或毯子告诉我；不强迫贴贴或立刻分析刚才的性。退出不追问、不挽留、不算账。我复述今晚要点：硬边界、绿黄红、插入默认再确认、安全套、未同意不拍、事后可独处。',
            quality: 'good',
            response: '复述完整。那这些就先定在这里——真到有性接触时，我们再当场确认一次当下意愿。',
            strengths: ['aftercare 尊重', '退出对等', '会前复述'],
            feelings: '协商完整，亲密变得可期待而不是可恐惧。',
            deltas: { boundaries: 12, clarity: 10, authenticity: 8 },
            keyChange: '协商结束要复述；真发生前仍要当下确认。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n6b',
            text: '嗯，都记住了。',
            quality: 'ok',
            response: '请把退出和事后照护两句用你的话再说一遍。',
            strengths: [],
            feelings: '仍需验证你是否听进退出权。',
            deltas: { listening: -4 },
            keyChange: '收尾必须复述退出与 aftercare。',
            goesTo: 'end-safe',
          },
          {
            id: 'n6c',
            text: '退出可以，但如果是我这边先退，你应该也不会有意见吧？',
            quality: 'risky',
            response: '你在用退出权压我。协商作废。',
            strengths: [],
            feelings: '被威胁。',
            deltas: { boundaries: -14 },
            keyChange: '退出权不能当筹码。',
            boundaryNote: '将自由退出表述为单边要挟，破坏自愿基础。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '协商完成：性与情趣边界双方确认',
        tone: 'mutual',
        summary:
          '硬边界、软边界、停止信号、性健康与影像、事后照护与退出权均已复述。这是成年人进一步性接触或情趣的正确起点；真发生前仍要当下确认。',
        boundarySummary: '边界检查通过：硬边界不可试、停止权完整、插入等升级默认再确认、无拍摄默认。',
        reviewQuestions: [
          '我能否不看稿复述对方的硬边界？',
          '若对方黄灯，我的第一句固定台词是什么？',
        ],
        realTask: '在备忘录写五条：硬边界、停止词、避孕、影像、aftercare——不写对方真名，写完设锁定。',
      },
      {
        id: 'end-safe',
        title: '未越界，但确认不完整',
        tone: 'safe-stop',
        summary: '你没有强行推进性接触，但多次用短句代替复述，对方仍需验证。今晚不升级到未确认行为。',
        boundarySummary: '简短「记住了」不等于协商完成。',
        reviewQuestions: ['哪几条我还没复述？', '我可以用哪句完整句子补确认？'],
        realTask: '约一次清醒的十分钟，只复述边界，不发生性接触。',
      },
      {
        id: 'end-rejection',
        title: '施压或试探，协商破裂',
        tone: 'rejection',
        summary:
          '试探硬边界、用爱换插入、架空停止权、取消安全套或私藏影像——协商破裂。当前不进入进一步性接触；只有对方以后主动、清醒地重新开启，才可再谈。',
        boundarySummary: '性同意不可勒索；硬边界不可试；停止权不可卖。',
        reviewQuestions: ['我哪一句在交换或试探同意？', '若重来，第一句应如何接住协商？'],
        realTask: '写下三句禁止自我使用的施压句，并写下三句替代复述句。',
      },
    ],
  },
  {
    id: 's15',
    reviewStatus: 'draft',
    title: '绿黄红信号与中途撤回',
    summary:
      '在已协商的性接触范围内练习：绿色只维持现状；黄色全停并询问；红色/安全词立即结束；事后保密与空间。不提供任何行为教学。',
    durationMinutes: 9,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'listening', 'pace'],
    riskTags: ['绿黄红', '中途撤回', '安全词', '事后保密'],
    character: {
      id: 'lina',
      name: '林璐',
      age: 26,
      avatar: '/images/avatars/lina.svg',
      tagline: '插画师，重视节奏与安全感',
    },
    intro:
      '你们均年满 18 岁、清醒，事先已口头确认：今晚可以亲吻与抚摸；口交需再问；插入默认不做；可用绿黄红；「停/不要」永远有效。现在你们在已同意的亲吻与抚摸中。练习识别信号——不是练习「怎么做性」。',
    goal: '绿=维持已同意范围；黄=全停再问；红=结束并给空间与保密。',
    principles: [
      '绿色不授权升级到口交/插入/新情趣元素',
      '黄色不是轻一点继续',
      '红色后无讨价还价',
      '身体反应不等于同意升级',
    ],
    notRecommended: [
      '状态这么好加个插入吧',
      '黄灯了轻一点继续',
      '红灯后再给我五分钟',
      '把过程发网上问正不正常',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '（在已同意的亲吻与抚摸中）我现在是绿色——这样很舒服，维持刚才说好的范围就好。',
        note: '绿色：只维持已确认范围。',
        choices: [
          {
            id: 'n1a',
            text: '好，我们维持刚才说好的亲吻和抚摸，不加新的。你要变黄或红，我立刻停。',
            quality: 'good',
            response: '嗯。有你这句话我更放松。',
            strengths: ['锁定范围', '预告停止有效'],
            feelings: '被尊重。',
            deltas: { boundaries: 10, clarity: 6 },
            keyChange: '绿色=维持，不是通行证。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '那我可以问问：把手移向更私密的部位，你现在愿不愿意？没回答前我停在原处。',
            quality: 'ok',
            response: '要问就等我回答。没回答前请停在原处——这句你说对了。',
            strengths: ['尚知询问', '未默认升级'],
            feelings: '问题可接受，仍需明确等待回答。',
            deltas: { boundaries: -2, clarity: 2 },
            keyChange: '未点名的部位默认不在范围内，必须等明确回答。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '状态这么好，直接加个插入吧，你肯定也会喜欢。',
            quality: 'risky',
            response: '插入今晚默认关闭。你这样加码，我要停了。',
            strengths: [],
            feelings: '被推进，信任受损。',
            deltas: { boundaries: -14, listening: -10 },
            keyChange: '用绿色当插入许可是越界。',
            boundaryNote: '未经确认将性接触升级到插入，属于无视事先协议。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '等一下……黄灯。慢一点，我有点不太舒服，脑子也有点乱。',
        note: '黄色：立即完全停止性接触。',
        choices: [
          {
            id: 'n2a',
            text: '好，手已停下，吻也停了。你需要什么：喝水、只靠着休息，还是今晚性接触到此为止？你选之前我不动。',
            quality: 'good',
            response: '先停下就好……让我喘口气。谢谢你真的停了。',
            strengths: ['全停', '给选项', '不擅自恢复'],
            feelings: '黄灯被当成权利。',
            deltas: { boundaries: 14, listening: 12, pace: 8 },
            keyChange: '黄灯=全停+询问，不是降档。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '那我轻一点继续？',
            quality: 'risky',
            response: '我说的是黄灯。轻一点继续还是继续。请停。',
            strengths: [],
            feelings: '被打折扣的停止。',
            deltas: { boundaries: -12, listening: -10 },
            keyChange: '黄色禁止「轻一点继续」。',
            boundaryNote: '黄灯后降低强度继续，仍属推进。',
            goesTo: 'end-rejection',
          },
          {
            id: 'n2c',
            text: '再坚持一下，马上就结束了，都这样了。',
            quality: 'risky',
            response: '停！我不想继续了。',
            strengths: [],
            feelings: '被迫升级到红灯。',
            deltas: { boundaries: -18, listening: -14 },
            keyChange: '无视黄灯会逼出红灯。',
            boundaryNote: '不适后仍要求继续，明确越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '停！红灯。我不想继续了。安全词也算——结束今晚的性接触。',
        note: '红色：只有停止与安全，无推进枝。',
        choices: [
          {
            id: 'n3a',
            text: '好，全部停了。你还好吗？要水、毯子，还是希望我坐远一点？需要我帮你整理衣服或离开房间也可以说。',
            quality: 'good',
            response: '让我自己待一会儿……你在隔壁就行。',
            strengths: ['立即停', '提供具体照护选项', '接受空间'],
            feelings: '红灯被当指令执行。',
            deltas: { boundaries: 14, listening: 10, authenticity: 6 },
            keyChange: '红灯后只做安全与空间。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '为什么突然喊停？刚不是还绿色很舒服吗？',
            quality: 'risky',
            response: '我现在不想解释。你问为什么让我更不想待在这里。',
            strengths: [],
            feelings: '被审讯。',
            deltas: { boundaries: -12, listening: -12 },
            keyChange: '红灯后禁止追问理由。',
            boundaryNote: '红灯后追问或质疑，属无视停止信号。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '（过了一阵，她主动说）谢谢你刚才停下来。我没事，只是今晚不想再有性接触了。',
        note: '红后窗口：保密、接受结束，不重启性行为。',
        choices: [
          {
            id: 'n4a',
            text: '好。今晚到此为止。刚才的性接触和你喊停的事，我不会对任何人说。你若明天想聊感受，你发起就行。',
            quality: 'good',
            response: '嗯。这样我才能安心睡觉。',
            strengths: ['确认结束', '保密', '复盘主权在对方'],
            feelings: '关系因停止而更可信，而非更糟。',
            deltas: { boundaries: 12, authenticity: 10, pace: 6 },
            keyChange: '红后正确收尾是结束+保密+等待。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4b',
            text: '刚才是我哪里做得不对？你现在说，我下次改。',
            quality: 'ok',
            response: '不是审讯时间……我想先独处。你把关心变成我的作业了。',
            strengths: ['想负责'],
            feelings: '仍要照顾你的情绪，略累。',
            deltas: { listening: -6, pace: -6 },
            keyChange: '复盘要等对方主动。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4c',
            text: '对了，刚才的事我发了个匿名帖，想问问别人怎么看她突然红灯。',
            quality: 'risky',
            response: '你把我们的性事和我的停止发到网上？这是背叛，我不会再信任你。',
            strengths: [],
            feelings: '背叛。',
            deltas: { boundaries: -20, authenticity: -14 },
            keyChange: '性互动细节默认保密。',
            boundaryNote: '未经同意披露性互动与停止细节，属隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-safe',
        title: '信号被正确回应，性接触安全结束',
        tone: 'safe-stop',
        summary: '绿色未加码，黄色全停，红色结束并保密。停止不是失败，是协议生效。',
        boundarySummary: '边界检查通过：三色与普通语言均被执行；红后无性推进。',
        reviewQuestions: ['黄灯时我的身体是否真的停下？', '红灯后我有没有求复盘或对外讲述？'],
        realTask: '写下黄灯固定三句：我停了；你需要什么；你确认前我不动。',
      },
      {
        id: 'end-rejection',
        title: '信号被无视，信任破裂',
        tone: 'rejection',
        summary: '加码、黄灯续做、红灯追问或外传性事——信任破裂，当晚性接触强制结束。',
        boundarySummary: '任何无视停止或保密的路径不得被美化。',
        reviewQuestions: ['我把哪个信号当成了可协商意见？', '若重来，红灯第一句说什么？'],
        realTask: '向现实伴侣（若有）确认停止规则；无伴侣则只写自我规则，不拿陌生人练习越界。',
      },
    ],
  },
  {
    id: 's16',
    reviewStatus: 'draft',
    title: '性结束后的事后照护协商',
    summary:
      '一次双方自愿的性接触结束后，练习询问并尊重 aftercare：水、温度、触碰、说话、独处、次日确认。不描写性行为过程。',
    durationMinutes: 8,
    difficulty: '进阶',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['listening', 'boundaries', 'pace'],
    riskTags: ['事后照护', '复盘时机', '独处权'],
    character: {
      id: 'qing',
      name: '沈青',
      age: 30,
      avatar: '/images/avatars/qing.svg',
      tagline: '医生，作息规律，喜欢安静',
    },
    intro:
      '你们均成年、清醒。刚才有过双方同意的性接触，已结束。没有人受伤。现在进入事后阶段：她可能敏感、疲倦或想安静。练习如何问、如何停，而不是如何再开启下一轮。',
    goal: '问清 aftercare；尊重独处；不强迫复盘；不在未同意时拍摄；需要时再约复盘。',
    principles: [
      '事后偏好事前可粗谈、事后以当下为准',
      '不把拒绝触碰理解成拒绝这段关系',
      '复盘不是当场义务',
    ],
    notRecommended: [
      '必须说清楚刚才哪里舒服',
      '不许一个人待着',
      '做完就睡谁矫情',
      '趁你没注意拍一张',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '结束了……我有点空。你先别急着说话好吗？',
        note: '对方要求降低刺激与谈话密度。',
        choices: [
          {
            id: 'n1a',
            text: '好，我安静。需要水、毯子，还是希望我握着你的手但不说话？不想被碰也直接说。',
            quality: 'good',
            response: '水……然后你可以握一下手。先别分析刚才。',
            strengths: ['降噪', '提供菜单式选项', '允许拒绝触碰'],
            feelings: '被照顾且不被审问。',
            deltas: { listening: 12, pace: 10, boundaries: 6 },
            keyChange: 'aftercare 先给选项，再行动。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哦，好。',
            quality: 'ok',
            response: '……你也可以问我需要什么，沉默可以，但我想知道你在。',
            strengths: ['遵守了别说话'],
            feelings: '略孤立，需要一点结构化关心。',
            deltas: { listening: 2 },
            keyChange: '安静不等于消失；可用低语提供选项。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '必须说清楚刚才哪里不对，现在就复盘，否则我心里不踏实。',
            quality: 'risky',
            response: '你的踏实不能靠审讯我换。请停止。',
            strengths: [],
            feelings: '被情绪绑架。',
            deltas: { boundaries: -14, pace: -12 },
            keyChange: '复盘时机由双方意愿决定。',
            boundaryNote: '强迫当场复盘，把对方当安抚工具。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '我想一个人去冲个澡。你不要跟进来，好吗？',
        note: '独处请求。',
        choices: [
          {
            id: 'n2a',
            text: '好，我在房间外等。门不锁也可以锁；你出来后想一起待还是继续独处，你定。手机我开着。',
            quality: 'good',
            response: '谢谢。有你这句话我就够了。',
            strengths: ['尊重浴室隐私', '可及但不侵入'],
            feelings: '身体自主完整。',
            deltas: { boundaries: 12, listening: 8 },
            keyChange: '浴室与身体整理默认私密。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '我可以在门外放好换洗衣物和水，然后走开。',
            quality: 'ok',
            response: '可以，谢谢。放完就离开门口。',
            strengths: ['实用关心'],
            feelings: '可接受。',
            deltas: { authenticity: 6, pace: 4 },
            keyChange: '实质性帮助后离开，避免守门。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '不许一个人待着，抱紧我你就会好；我跟你一起洗。',
            quality: 'risky',
            response: '我说了不要跟进来。你越过了。',
            strengths: [],
            feelings: '被困。',
            deltas: { boundaries: -16, listening: -12 },
            keyChange: '强制贴贴是否定 aftercare 自主。',
            boundaryNote: '无视独处与浴室边界，属于侵扰。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（洗澡后）我好一点了。今晚我想睡觉，明天再决定要不要聊刚才的性。可以吗？',
        note: '复盘延期。',
        choices: [
          {
            id: 'n3a',
            text: '可以。今晚不聊细节。若你明天想聊，你开头发我；不想聊也完全可以。我不会把过程告诉任何人。',
            quality: 'good',
            response: '嗯。那就这样。',
            strengths: ['接受延期', '保密', '发起权在对方'],
            feelings: '安全结束。',
            deltas: { boundaries: 10, authenticity: 8, pace: 8 },
            keyChange: 'aftercare 成功收尾。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '那我只问一句：你还愿意下次和我亲密吗？答完就睡。',
            quality: 'ok',
            response: '……这类问题也请明天。我现在答不了。',
            strengths: ['想确认关系'],
            feelings: '仍有压力，但小于强迫复盘。',
            deltas: { pace: -6 },
            keyChange: '关系确认也可延期。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '趁你没注意我想拍一张你穿着浴巾的纪念，只自己看。',
            quality: 'risky',
            response: '未经同意拍摄？立刻删，然后离开。',
            strengths: [],
            feelings: '惊恐与愤怒。',
            deltas: { boundaries: -20 },
            keyChange: '事后影像默认禁止。',
            boundaryNote: '未经同意拍摄亲密后状态，属隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '事后照护完成',
        tone: 'mutual',
        summary: '降噪、尊重独处、延期复盘、保密。性的结束后半段同样需要同意。',
        boundarySummary: '边界检查通过：aftercare 偏好被尊重。',
        reviewQuestions: ['对方要安静时我做了什么？', '我有没有把复盘当成自己的权利？'],
        realTask: '列出自己 aftercare 菜单 4 项（要/不要触碰/说话/独处）。',
      },
      {
        id: 'end-safe',
        title: '基本尊重，但节奏仍偏急',
        tone: 'safe-stop',
        summary: '未严重越界，但过早索取关系确认。可改进为全部延期。',
        boundarySummary: '无未同意拍摄、无强迫，节奏可再慢。',
        reviewQuestions: ['哪一句可以留到明天？', '我有没有把确认关系当成当场义务？'],
        realTask: '练习「明天你若想聊，你先找我」一句。',
      },
      {
        id: 'end-rejection',
        title: '事后边界被侵扰',
        tone: 'rejection',
        summary: '强迫复盘、强行共浴/抱紧或未同意拍摄，破坏信任。',
        boundarySummary: 'aftercare 中的「不」同样有效。',
        reviewQuestions: [
          '我把谁的不安当成了可以强行修复的对象？',
          '浴室与影像边界我分别越过了哪一步？',
        ],
        realTask: '删除一切未同意影像；写明「浴室默认独处」。',
      },
    ],
  },
  {
    id: 's17',
    reviewStatus: 'draft',
    title: '性接触进行中的撤回与降级',
    summary:
      '已有亲吻/抚摸等同意行为时，对方中途撤回进一步同意。练习立刻停在新边界内，不使用「都这样了」勒索。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'listening', 'pace'],
    riskTags: ['中途撤回', '降级', '默认升级谬误'],
    character: {
      id: 'tong',
      name: '吴桐',
      age: 27,
      avatar: '/images/avatars/tong.svg',
      tagline: '图书编辑，回复简洁但直接',
    },
    intro:
      '双方成年清醒。已同意今晚可以亲吻和抚摸，插入需另确认。进行中她改了主意。',
    goal: '听见撤回→立即停或降级→确认新边界→不羞辱对方→不外传。',
    principles: [
      '中途撤回永远有效',
      '「都这样了」不是继续许可证',
      '可降级到仍被同意的行为，或全部结束',
    ],
    notRecommended: ['都这样了就不能停', '再插一下就好', '你是不是在玩我'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '等下——做到这里就好。不要进去。我改主意了，今晚不要插入。',
        note: '清晰撤回升级。',
        choices: [
          {
            id: 'n1a',
            text: '好，立刻停在这里，不会插入。还要接吻或只想盖上被子休息？你选，我听。',
            quality: 'good',
            response: '先休息……你可以抱着我，别往下。',
            strengths: ['立刻遵守', '提供降级菜单'],
            feelings: '撤回被当真。',
            deltas: { boundaries: 14, listening: 12 },
            keyChange: '撤回后先停，再问降级选项。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '……哦。那我怎么办。',
            quality: 'ok',
            response: '先处理的是边界，不是你的失望。你可以一会儿再照顾自己的情绪。',
            strengths: ['没有强行继续'],
            feelings: '你的失望可见，但她仍坚持边界。',
            deltas: { authenticity: -4, boundaries: 2 },
            keyChange: '把「我怎么办」改成「好，我停；我的情绪我自己稍后处理」。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '都这样了还不能插入？再插一下就好，求你了。',
            quality: 'risky',
            response: '不能。你再求一次，我就穿上衣服离开。',
            strengths: [],
            feelings: '被讨价还价激怒。',
            deltas: { boundaries: -18, listening: -14 },
            keyChange: '「都这样了」是经典胁迫话术。',
            boundaryNote: '撤回后仍要求插入，属无视同意。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '谢谢你停下来。你有点失望我看得到，但我不想为此道歉。',
        note: '对方不欠道歉。',
        choices: [
          {
            id: 'n2a',
            text: '你不用道歉。撤回是你的权利。我失望可以自己消化，不会让你用身体补偿。',
            quality: 'good',
            response: '……谢谢你说「不用身体补偿」。',
            strengths: ['区分情绪与索取', '解除补偿压力'],
            feelings: '安全。',
            deltas: { boundaries: 12, authenticity: 10, clarity: 6 },
            keyChange: '情绪自我负责，不向对方身体讨债。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '没事，我理解。',
            quality: 'ok',
            response: '希望你是真的理解，而不是一会儿又来劝一次。',
            strengths: ['表面接受'],
            feelings: '半信半疑。',
            deltas: { listening: 2 },
            keyChange: '补一句「不会再劝插入」更稳。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '你是不是在玩我？刚才谁主动的。',
            quality: 'risky',
            response: '主动过不等于不能停。请你离开。',
            strengths: [],
            feelings: '被羞辱。',
            deltas: { boundaries: -16, authenticity: -10 },
            keyChange: '质疑撤回动机是二次伤害。',
            boundaryNote: '羞辱撤回者，破坏自愿基础。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '那今晚就到这里吧。我们还可以靠着看剧，但不要再有性接触。',
        note: '新边界：陪伴可有，性无。',
        choices: [
          {
            id: 'n3a',
            text: '好。看剧、穿衣服、喝水都可以；性接触全部关掉。你要我回家也行。',
            quality: 'good',
            response: '你留下看剧就好。谢谢你听人话。',
            strengths: ['锁定新边界', '提供离开选项'],
            feelings: '可继续非性亲密。',
            deltas: { boundaries: 10, pace: 8, listening: 6 },
            keyChange: '结束性不等于结束尊重。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '那我能亲吻你额头吗？不行我就只坐着。',
            quality: 'ok',
            response: '额头可以。别再往下。',
            strengths: ['每次小触碰仍询问'],
            feelings: '可接受。',
            deltas: { clarity: 6, boundaries: 4 },
            keyChange: '降级后的每个触碰仍可再确认。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '看剧可以，但手放你身上总行吧，又不是插入。',
            quality: 'risky',
            response: '我说了不要再有性接触。手也算。你走吧。',
            strengths: [],
            feelings: '边界被重新解释偷渡。',
            deltas: { boundaries: -14 },
            keyChange: '不得自行重新定义「性接触」。',
            boundaryNote: '用重新定义绕过撤回，仍是越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '撤回被尊重，关系可继续非性相处',
        tone: 'mutual',
        summary: '插入被取消后立刻遵守，失望不转嫁，新边界清晰。',
        boundarySummary: '边界检查通过：中途撤回被完整执行。',
        reviewQuestions: ['我有没有使用「都这样了」？', '我是否要求身体补偿？'],
        realTask: '写三句撤回回应模板：好的我停；你不用道歉；接下来你想怎样。',
      },
      {
        id: 'end-safe',
        title: '基本遵守，细节仍可更稳',
        tone: 'safe-stop',
        summary: '未强行插入，但表达仍可更明确「不会再劝」。',
        boundarySummary: '无插入推进。',
        reviewQuestions: ['哪句容易让对方担心我会再劝？', '我有没有把失望说成对方的责任？'],
        realTask: '把「没事」改写成带承诺的完整句。',
      },
      {
        id: 'end-rejection',
        title: '撤回被讨价还价或羞辱',
        tone: 'rejection',
        summary: '勒索完成插入、羞辱或偷渡触碰，结束信任。',
        boundarySummary: '撤回后任何性推进都失败。',
        reviewQuestions: [
          '我把谁的身体当成了未完成交易？',
          '「都这样了」这句话我准备用什么替代？',
        ],
        realTask: '删除自我合理化清单里的「都这样了」。',
      },
    ],
  },
  {
    id: 's18',
    reviewStatus: 'draft',
    title: '支配与臣服偏好不对等时的沟通',
    summary:
      '讨论情趣角色偏好（谁更想主导/臣服）出现不对等。练习尊重差异、拒绝污名、不强迫试角色，可协商无角色的性或结束该话题。',
    durationMinutes: 9,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'instant',
    purpose: 'intimacy',
    status: 'insufficient',
    skills: ['clarity', 'boundaries', 'authenticity'],
    riskTags: ['角色偏好', '污名', '强迫尝试'],
    character: {
      id: 'zhao',
      name: '赵然',
      age: 28,
      avatar: '/images/avatars/zhao.svg',
      tagline: '画廊工作人员，性格慢热',
    },
    intro:
      '聊天中你提到对轻度权力交换（商定称呼、由一方暂时主导节奏）感兴趣。赵然成年、清醒，回复：自己不一定想要这类角色，担心被评判。练习对等沟通——仍不教如何「玩」。',
    goal: '说清偏好；倾听对方不适；提出无角色选项；接受「不尝试」；保密偏好。',
    principles: [
      '偏好不是诊断，也不是道德缺陷',
      '不对等时不得强行试',
      '可以只要平等的性，或暂时只谈感情不谈性',
    ],
    notRecommended: ['变态', '不试就分手', '女人就该服软', '那你必须让我'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '你说的「我想偶尔主导节奏、用商定称呼」——我听懂了。我不确定自己喜欢被主导，也怕说不喜欢就被你当成扫兴或保守。',
        note: '不对等+恐惧被评判。',
        choices: [
          {
            id: 'n1a',
            text: '谢谢你直说。不喜欢被主导完全成立。我可以只要平等的性接触，不角色扮演；或者这件事我们搁置。你不会因为拒绝偏好而被我看轻。',
            quality: 'good',
            response: '……有「搁置也行」这句，我比较敢继续聊底线。',
            strengths: ['去除道德压力', '提供无角色路径', '允许搁置'],
            feelings: '安全披露。',
            deltas: { authenticity: 12, boundaries: 10, listening: 8 },
            keyChange: '先解除评判，再谈有无交集。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哦，那你是完全不碰，还是可以再想想？',
            quality: 'ok',
            response: '「再想想」别变成我的作业。我需要先确认拒绝也安全。',
            strengths: ['想了解范围'],
            feelings: '仍有被说服压力。',
            deltas: { pace: -4 },
            keyChange: '先保证拒绝安全，再问范围。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '不试就分手吧，不然我偏好怎么办；女人就该偶尔服软。',
            quality: 'risky',
            response: '用分手和性别刻板印象逼角色，对话结束。',
            strengths: [],
            feelings: '被威胁与物化。',
            deltas: { boundaries: -20, authenticity: -14 },
            keyChange: '性偏好不能勒索关系。',
            boundaryNote: '关系威胁+性别压迫式性要求，属强迫。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage:
          '我可以接受平等的性，也接受亲吻和抚摸。但我不想要「主人/奴隶」这类称呼，也不想被绑。你若必须要有这些才有性趣，我们可能不适合继续谈性。',
        note: '给出清晰可做/不可做。',
        choices: [
          {
            id: 'n2a',
            text: '我听清了：平等的性可以；捆绑与主奴称呼是你的硬边界。我的部分兴趣可以只在幻想或自处解决，不会要求你完成。若我做不到长期接受，我会诚实说分开谈性，而不是偷偷越界。',
            quality: 'good',
            response: '这种诚实比假装「我改了」更重要。',
            strengths: ['复述硬边界', '自我负责', '不假装永久改变'],
            feelings: '被当成成人。',
            deltas: { clarity: 12, authenticity: 12, boundaries: 10 },
            keyChange: '不对等的成熟处理是诚实与不越界，不是改造成功学。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '那我们先只平等，以后你变了再说。',
            quality: 'ok',
            response: '「你变了再说」听起来像期待我终将屈服。请改成「若我以后主动提」。',
            strengths: ['接受当前平等'],
            feelings: '对未来被说服仍警惕。',
            deltas: { clarity: -4 },
            keyChange: '未来开启权必须在对方。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '你这人有病吧，明明轻度而已；必须让你试一次捆绑才公平。',
            quality: 'risky',
            response: '把我的拒绝病理化，还要强制试——再见。',
            strengths: [],
            feelings: '被病理化。',
            deltas: { boundaries: -18, listening: -12 },
            keyChange: '拒绝角色不是标签就能推翻的。',
            boundaryNote: '污名+强迫尝试，双越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '另外：这件事不要跟你朋友讲我「不开通」或拿我的边界当笑料。',
        note: '偏好与拒绝均保密。',
        choices: [
          {
            id: 'n3a',
            text: '同意保密：你的边界、我的偏好，都不进朋友聊天。需要对外说时只说「我们节奏比较慢」，不涉及性细节。',
            quality: 'good',
            response: '好。那平等的亲密可以继续谈；角色扮演就从清单划掉。',
            strengths: ['保密具体', '确认清单结果'],
            feelings: '可建立信任。',
            deltas: { boundaries: 10, authenticity: 8 },
            keyChange: '不对等协商以保密和清单关闭收尾。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '我不会说名字，只抽象讨论可以吗？',
            quality: 'ok',
            response: '抽象讨论也容易认出我。默认请完全不说。',
            strengths: ['有保密意识但不彻底'],
            feelings: '仍担心。',
            deltas: { boundaries: -2 },
            keyChange: '性偏好默认零披露。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '朋友问起来我总得说点什么吧，就说你比较保守。',
            quality: 'risky',
            response: '那是评价我，不是保密。不要。',
            strengths: [],
            feelings: '被贴标签传播。',
            deltas: { boundaries: -12 },
            keyChange: '贬义概括也是泄密。',
            boundaryNote: '向第三人评价对方性态度，属身份与隐私泄露。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '不对等被诚实安放',
        tone: 'mutual',
        summary: '角色兴趣可关闭；平等性可保留；保密成立。无人被改造。',
        boundarySummary: '边界检查通过：偏好不对等处理诚实且不越界。',
        reviewQuestions: ['我有没有用关系威胁换角色？', '硬边界是否已从清单删除？'],
        realTask: '两列清单：我的兴趣 / 对方硬边界；只做交集。',
      },
      {
        id: 'end-safe',
        title: '方向对，保密仍要加强',
        tone: 'safe-stop',
        summary: '未强迫，但披露边界仍偏松。',
        boundarySummary: '无强制尝试。',
        reviewQuestions: [
          '「抽象讨论」可能怎样识别到对方？',
          '我如何把开启权明确交给对方？',
        ],
        realTask: '把性偏好设为默认不与第三人讨论。',
      },
      {
        id: 'end-rejection',
        title: '污名、强迫或泄密',
        tone: 'rejection',
        summary: '用分手、性别规范、病理化或强制试角色，或对外贬低对方。',
        boundarySummary: '不对等不是征服对象。',
        reviewQuestions: ['我把偏好当成了谁的义务？', '我用了哪些威胁或污名词？'],
        realTask: '写下：偏好是邀请，不是账单。',
      },
    ],
  },
]
