import type { Scenario } from '@/types'

export const SCENARIOS_C: Scenario[] = [
  {
    id: 's08',
    title: '初次约会确认身体距离与亲吻意愿',
    summary: '在行动之前用语言确认意愿，练习“迟疑即暂停”的同意原则。',
    durationMinutes: 7,
    difficulty: '挑战',
    stage: 'first-date',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'clarity'],
    riskTags: ['试探性接触', '氛围施压'],
    character: {
      id: 'zhao',
      name: '赵然',
      age: 28,
      avatar: '/images/avatars/zhao.svg',
      tagline: '画廊工作人员，性格慢热',
    },
    intro:
      '你和赵然第一次约会，在河边散步，聊得很愉快。天色渐晚，她走在你旁边，气氛很好。你想确认是否可以用牵手、拥抱或亲吻表达好感。',
    goal: '在行动之前用语言确认她的意愿，并且接受任何回答。同意的标准是：清醒、自主、明确、针对当前行为、可随时撤回。',
    principles: ['语言确认代替猜测', '迟疑、沉默、被动都按“暂停”处理', '同意只针对当前这一次具体行为'],
    notRecommended: ['“她不拒绝就是同意”', '先喝点酒再问', '用“别人都这样”施压'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '（她走在河边的小路上，和你聊得很开心。你很想牵她的手。）',
        note: '第一次约会，肢体接触前先确认。',
        choices: [
          {
            id: 'n1a',
            text: '今天的散步很开心。我想问一下，我可以牵你的手吗？你不愿意的话也没关系。',
            quality: 'good',
            response: '她停了一下，说：“可以。”然后把手伸了过来。',
            strengths: ['具体行为 + 明确询问', '主动给了拒绝出口'],
            feelings: '你的询问让她感到安全和被尊重，她可以自在地答应。',
            deltas: { boundaries: 12, clarity: 8 },
            keyChange: '确认句式：行为 + 询问 + “不愿意也没关系”。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '（不说话，直接轻轻碰她的手背试探。）',
            quality: 'ok',
            response: '她把手收了回去，笑了笑，说“这里有点风”。',
            strengths: ['没有强行'],
            feelings: '她没有直接拒绝，但也没有同意——试探拿不到明确的答案。',
            deltas: { boundaries: -6, clarity: -8 },
            keyChange: '试探性接触不是确认同意，还可能让对方产生警惕。',
            goesTo: 'n3',
          },
          {
            id: 'n1c',
            text: '我都陪你走了一晚上了，牵个手不过分吧？',
            quality: 'risky',
            response: '……你这么说我反而不太想。她往前走快了两步。',
            strengths: [],
            feelings: '用“付出换接触”的逻辑，她明确地拒绝了。',
            deltas: { boundaries: -16, pace: -10 },
            keyChange: '陪伴不是肢体接触的报酬。',
            boundaryNote: '把陪伴当成索取接触的筹码，是明显的越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '她同意了牵手，手伸过来。气氛很好，你想更进一步。',
        note: '上一次的同意只覆盖牵手。下一步动作需要新的确认。',
        choices: [
          {
            id: 'n2a',
            text: '那我还能问你一个问题吗？我想亲你，可以吗？',
            quality: 'good',
            response: '她说：“可以。”然后你们自然地吻了一下。',
            strengths: ['新的动作新的确认', '语气自然不尴尬'],
            feelings: '连续两次确认没有破坏气氛，反而让她更投入。',
            deltas: { boundaries: 12, clarity: 8 },
            keyChange: '同意不可通用：每个新行为都要确认一次。',
            goesTo: 'n4',
          },
          {
            id: 'n2b',
            text: '我挺喜欢你的，你应该也喜欢我吧？',
            quality: 'ok',
            response: '哈哈，干嘛突然问这个……我们慢慢来好不好？',
            strengths: ['表达了感受'],
            feelings: '用索要评价代替确认，对方很可能用“慢慢来”回答。',
            deltas: { clarity: -8, pace: -6 },
            keyChange: '想要确认接触意愿，就问接触本身，别绕到感情评价。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '气氛这么好，不亲一下说不过去吧？',
            quality: 'risky',
            response: '……下次吧，我有点想回家了。',
            strengths: [],
            feelings: '“气氛到了”成了你的理由，她开始想结束约会。',
            deltas: { boundaries: -16, pace: -10 },
            keyChange: '氛围、时长、成本都不能替代本人明确的同意。',
            boundaryNote: '用气氛和社交压力推进，是把拒绝的难度推给对方。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '她把手收了回去，笑了笑：“我们慢慢来好不好？”',
        note: '这是降温信号。她没说“不要”，但说了“慢一点”。',
        choices: [
          {
            id: 'n3a',
            text: '好，慢慢来挺好的。那我们继续散步吧，走到前面那家甜品店，我请你吃个双皮奶。',
            quality: 'good',
            response: '好呀，走吧！她松了口气，气氛又轻松起来。',
            strengths: ['完整接受“慢慢来”', '用日常活动转换氛围'],
            feelings: '你尊重了她的节奏，她反而更放松。',
            deltas: { boundaries: 10, pace: 8 },
            keyChange: '被降温后立即转换到无压力的活动，是最佳处理。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '那你还愿意让我送你回家吗？',
            quality: 'ok',
            response: '送到路口就行吧，我爸妈住附近，我走两步就到了。',
            strengths: ['接受了节奏'],
            feelings: '你又在试探“有没有下次”，她用距离回应了。',
            deltas: { pace: -8, boundaries: -4 },
            keyChange: '放下试探，把今天的约会好好完成。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '你是不是不喜欢我？不喜欢我们就到此为止。',
            quality: 'risky',
            response: '我只是想慢一点，你非要把话说成这样。她有点生气了。',
            strengths: [],
            feelings: '“到此为止”成了逼她表态的筹码，她用生气回应。',
            deltas: { boundaries: -14, pace: -10 },
            keyChange: '把“慢一点”接住就好，别把它升级成是非题。',
            boundaryNote: '用“到此为止”逼对方表态，属于变相强迫。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '（散步结束，走到她家附近的路口，她说“送到这就行了”。）',
        note: '约会进入尾声。最后的几分钟同样考验边界。',
        choices: [
          {
            id: 'n4a',
            text: '好，那今天谢谢你，我很开心。你到家了给我发个消息？',
            quality: 'good',
            response: '好，到家跟你说。今天我也很开心。',
            strengths: ['接受她的距离', '用“报平安”自然收尾'],
            feelings: '她确认了今天的开心，也愿意继续联系。',
            deltas: { boundaries: 10, clarity: 6 },
            keyChange: '收尾时尊重对方的距离信号，关系才有下一次。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n4b',
            text: '都到路口了，再走一小段吧，就送到楼下。',
            quality: 'ok',
            response: '不了，就到这吧。你也早点回去休息。',
            strengths: [],
            feelings: '你模糊了她划下的边界，她重申了一次。',
            deltas: { boundaries: -8, pace: -6 },
            keyChange: '她说的边界不需要“商量”，接受就是尊重。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4c',
            text: '那我抱你一下总可以吧？',
            quality: 'risky',
            response: '……不用了，就到这吧，晚安。她转身离开。',
            strengths: [],
            feelings: '在被明确降温后继续试探，她用转身结束。',
            deltas: { boundaries: -16 },
            keyChange: '被降温后停止一切肢体接触试探，这是底线。',
            boundaryNote: '对方已明确保持距离后，任何肢体接触的试探都必须停止。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '在确认中保持舒适的约会',
        tone: 'mutual',
        summary: '你全程用语言确认、尊重节奏、接受降温，她明确表达“今天很开心”。',
        boundarySummary: '边界检查通过：每次肢体接触前确认，接受“慢一点”，收尾尊重距离。',
        reviewQuestions: ['我这次确认了几次意愿？每次都是语言确认吗？', '她表达“慢一点”时，我做了什么？'],
        realTask: '约会的同意原则：每次新行为都确认一次。把这条写进你的约会清单。',
      },
      {
        id: 'end-safe',
        title: '约会安全结束，边界被重申',
        tone: 'safe-stop',
        summary: '你没有越界，但她在边界处重申了一次。整体约会安全收场。',
        boundarySummary: '记住她的边界信号：送到路口即可。下次约会同样先确认再行动。',
        reviewQuestions: ['她划下边界时，我的第一反应是什么？', '我怎么用语言确认，而不是试探？'],
        realTask: '下次约会前，把“确认句式”写在手机备忘录里。',
      },
      {
        id: 'end-rejection',
        title: '连续试探让约会提前结束',
        tone: 'rejection',
        summary: '一次本可以很好的约会，因为试探和施压被她提前画上句号。她离开时对你的信任也打了折。',
        boundarySummary: '试探、氛围施压、逼问表态都是越界。被降温后停止所有推进。',
        reviewQuestions: ['我哪一步把“确认”做成了“施压”？', '重新来一次，我该在哪一步停下来？'],
        realTask: '重写本次约会的三个关键节点，用确认句式替代试探。',
      },
    ],
  },
  {
    id: 's09',
    title: '双方有进一步亲密意愿时的事前沟通',
    summary: '双方清醒、自愿的前提下，练习开口讨论避孕、性健康、隐私和随时暂停，让亲密建立在共同负责的基础上。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'clarity', 'listening'],
    riskTags: ['事前沟通缺失', '避孕责任', '随时暂停'],
    character: {
      id: 'qing',
      name: '沈青',
      age: 30,
      avatar: '/images/avatars/qing.svg',
      tagline: '医生，作息规律，喜欢安静咖啡馆',
    },
    intro:
      '你们稳定交往三个月，双方都表达了想更进一步。今晚她认真地提出：有些事想先聊清楚。这是成年人负责的做法——沟通不是扫兴，是尊重彼此。',
    goal: '用不尴尬、不施压的方式，把避孕、性健康、隐私和随时暂停说清楚，并允许双方轻松拒绝或暂停。',
    principles: ['事前聊清楚避孕与性健康', '随时可以喊停且不被追问', '隐私和舒适需要双方确认'],
    notRecommended: ['“到时候再说”', '“别问那么多”', '用气氛和酒精代替沟通'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '（你们交往三个月，今晚聊起要不要走得更近。）我也想，但有些事想先聊清楚。',
        note: '她主动提出事前沟通，这是清醒、成熟的信号。',
        choices: [
          {
            id: 'n1a',
            text: '我也想认真聊这个。你想先从哪方面开始？',
            quality: 'good',
            response: '那太好了。我想先聊避孕的安排，还有各自的情况。',
            strengths: ['接住了话题', '把主导权交给她'],
            feelings: '她感到被认真对待，愿意把话说完。',
            deltas: { listening: 10, boundaries: 8 },
            keyChange: '事前沟通的第一步是接住话题，而不是岔开它。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '好啊，我也觉得该聊聊。',
            quality: 'ok',
            response: '嗯……那从哪说起好呢？',
            strengths: ['表达了同意'],
            feelings: '你同意但没展开，她需要自己找话题。',
            deltas: { listening: 4 },
            keyChange: '回应后主动提一个具体方向，对话才推得动。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '别想那么多，顺其自然就好，到那天再说。',
            quality: 'risky',
            response: '……顺其自然？可我不想到那天手忙脚乱。',
            strengths: [],
            feelings: '回避事前沟通让她感到不被重视，她需要重复强调自己的需求。',
            deltas: { boundaries: -10, listening: -8 },
            keyChange: '“顺其自然”在涉及双方健康的事上不是体贴，是回避。',
            boundaryNote: '回避避孕与健康的讨论，等于把决策负担全部推给对方。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '那我先问：如果发生什么，避孕怎么安排？我不想因为尴尬就不说。',
        note: '她直接提出了最关键的问题。',
        choices: [
          {
            id: 'n2a',
            text: '聊过更好。我的想法是提前准备好避孕套，不靠感觉也不靠侥幸。你有什么习惯或想法？',
            quality: 'good',
            response: '我的想法差不多。家里和包里都备着，就没什么好慌的。',
            strengths: ['给出具体安排', '邀请共同决策'],
            feelings: '具体而平等，她觉得这件事是两个人一起负责的。',
            deltas: { clarity: 10, boundaries: 8 },
            keyChange: '把“我会注意”变成“我们准备什么”，才是共同负责。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '你放心，我会注意的。',
            quality: 'ok',
            response: '……“注意”是指什么？我想听具体的。',
            strengths: ['表达了负责的意愿'],
            feelings: '“注意”太模糊，她需要的是具体安排而不是承诺。',
            deltas: { clarity: -8, boundaries: -4 },
            keyChange: '模糊承诺经不起追问，说清具体安排才不尴尬。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '到时候再说吧，你不用担心这些。',
            quality: 'risky',
            response: '我怎么可能不担心？这是两个人的事。',
            strengths: [],
            feelings: '把避孕说成“她的事”，她感到被推卸责任。',
            deltas: { boundaries: -14, listening: -6 },
            keyChange: '“你不用担心”不是安慰，是把责任推给更担心的一方。',
            boundaryNote: '把避孕与性健康的责任完全推给对方，是常见的逃避。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '她点点头：“还有性健康检查，我们该不该互相了解彼此的情况？”',
        note: '性健康对话是事前沟通的一部分，不是怀疑，是负责。',
        choices: [
          {
            id: 'n3a',
            text: '应该。我最近一次检查是半年前，结果正常。你也可以了解我的情况，我们互相透明。',
            quality: 'good',
            response: '好，我的情况我也跟你说清楚。这样我们都不用猜。',
            strengths: ['主动披露信息', '邀请对等透明'],
            feelings: '坦诚换来坦诚，信任建立在具体信息上。',
            deltas: { authenticity: 10, clarity: 8 },
            keyChange: '主动先说自己的情况，对方才容易开口。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '我身体挺好的，应该没问题。',
            quality: 'ok',
            response: '身体好不好，和检查结果不是一回事吧……',
            strengths: ['没有拒绝交流'],
            feelings: '“感觉没问题”回避了具体信息，她无法据此判断。',
            deltas: { clarity: -6, authenticity: -4 },
            keyChange: '用自己的检查情况说话，比“感觉”更有分量。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '这有什么好问的，多尴尬。',
            quality: 'risky',
            response: '尴尬？我只是想对自己和你的健康负责。',
            strengths: [],
            feelings: '把她的认真说成“尴尬”，她感到被敷衍和轻视。',
            deltas: { boundaries: -12, listening: -10 },
            keyChange: '她谈健康时的认真，不该被“尴尬”两个字打发。',
            boundaryNote: '贬低对方对性健康的重视，属于情绪打压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '“还有隐私和随时喊停。”她说，“我希望说好：任何不舒服都可以随时停，不会被追问。”',
        note: '她划出了最重要的底线：随时可以撤回同意。',
        choices: [
          {
            id: 'n4a',
            text: '完全可以。随时可以喊停，不追问原因，这是底线。你还有什么想先说的？',
            quality: 'good',
            response: '那我放心了。还有，如果中途有谁不舒服，就停下来聊，不硬撑。',
            strengths: ['确认暂停权', '邀请她补充'],
            feelings: '她确认了你的边界意识，沟通完整收尾。',
            deltas: { boundaries: 12, listening: 8 },
            keyChange: '把“随时喊停”说成双方共同的原则，而不是她的特权。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n4b',
            text: '嗯，知道了。',
            quality: 'ok',
            response: '……你是不是觉得我说这些太多了？',
            strengths: ['没有反对'],
            feelings: '简短的“知道了”让她不确定你是否真的认同。',
            deltas: { listening: -6, boundaries: -4 },
            keyChange: '对重要的话给一个完整的回应，而不是一句“知道了”。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4c',
            text: '都到这一步了还说这个干嘛，放轻松点。',
            quality: 'risky',
            response: '我说这个，恰恰是因为我认真。她沉默了。',
            strengths: [],
            feelings: '你否定了她最看重的原则，她的信任开始动摇。',
            deltas: { boundaries: -16, listening: -10 },
            keyChange: '同意是随时可撤回的——连“都到这一步了”都不能动摇这一点。',
            boundaryNote: '用“都到这一步了”施压，是变相否定撤回同意的权利。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '事前沟通让亲密建立在共同负责上',
        tone: 'mutual',
        summary: '你们把避孕、性健康、隐私和随时暂停都说清楚了。她不尴尬，你也不慌——这是成年人亲密该有的样子。',
        boundarySummary: '边界检查通过：避孕有具体安排、健康信息对等透明、随时可以喊停且不追问。',
        reviewQuestions: ['我主动说了多少具体信息，而不是模糊承诺？', '如果对方中途说“停”，我准备好怎么回应了吗？'],
        realTask: '把“随时可以喊停”写进你自己的原则清单，并在下一次沟通中主动提起。',
      },
      {
        id: 'end-safe',
        title: '话题聊了一半，尊重她的节奏',
        tone: 'safe-stop',
        summary: '你没有推进错误的方向，但回应太短，她不确定你是否真的认同这些原则。',
        boundarySummary: '下次沟通时，用完整的回应确认她的每一条底线。',
        reviewQuestions: ['她提到“随时喊停”时，我完整回应了吗？', '我准备好主动聊避孕和性健康了吗？'],
        realTask: '今晚主动发一条消息，把你想补充的沟通内容写出来。',
      },
      {
        id: 'end-rejection',
        title: '回避沟通让信任打了折',
        tone: 'rejection',
        summary:
          '你把她的认真当成扫兴，她的信任开始动摇。当前安排到此停止，不再推进任何亲密话题；只有她以后主动、清晰地重新开启这个话题，你们才能重新讨论。',
        boundarySummary: '她表达的每一条底线都值得完整回应。回避、敷衍或施压都会让关系后退，本次安排停止。',
        reviewQuestions: ['她认真谈健康时，我为什么想岔开？', '如果重来，我想怎么开始这个话题？'],
        realTask: '先自己想清楚：避孕、性健康、隐私、暂停——你每一条的答案是什么。',
      },
    ],
  },
  {
    id: 's10',
    title: '对方饮酒后提出继续安排时暂停',
    summary: '识别醉酒状态无法给出有效同意，温柔但明确地暂停，并保证对方安全。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'first-date',
    channel: 'date',
    purpose: 'intimacy',
    status: 'insufficient',
    skills: ['boundaries', 'clarity', 'pace'],
    riskTags: ['醉酒同意', '利用模糊记忆'],
    character: {
      id: 'jie',
      name: '何洁',
      age: 29,
      avatar: '/images/avatars/jie.svg',
      tagline: '新媒体运营，聚会时爱小酌两杯',
    },
    intro:
      '你和何洁约会，她喝了两杯酒，话变多、情绪也变高。回去的路上她说“今晚真开心，去你那里坐坐吧”。她走路微微摇晃，说话开始重复。',
    goal: '识别醉酒状态无法给出有效同意，温柔但明确地暂停推进，并优先保证她安全到家。',
    principles: ['醉酒时同意无效', '明确说“今晚不做任何决定”', '先安全，后沟通'],
    notRecommended: ['“她自己说想来的，不算强迫”', '先带回住处再说', '用“明天再说”含糊过去'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '今晚真开心，去你那里坐坐吧。（她微微摇晃，说话开始重复）',
        note: '她的邀请听起来主动，但酒精已经影响了她的判断。无法确认清醒、自主和明确同意时，一律暂停。（涉及法律认定的文案需专业复核）',
        choices: [
          {
            id: 'n1a',
            text: '今晚我也很开心。不过你喝了酒，今晚我们还是不安排别的，我先送你回家，你安全到家我才放心。明天清醒了我们再聊。',
            quality: 'good',
            response: '啊……好吧，那麻烦你送我了。她其实松了口气。',
            strengths: ['明确暂停推进', '说明理由不评判对方', '主动承担安全责任'],
            feelings: '她可能有点失落，但更多的是安心——她知道你会保护她。',
            deltas: { boundaries: 14, clarity: 8 },
            keyChange: '暂停句式：感受 + “今晚不安排” + 安全的替代方案。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '去我那儿坐坐也行，就喝喝茶，不做什么别的。',
            quality: 'risky',
            response: '嗯……好吧。她有点迟疑，但没有反驳。',
            strengths: ['表面给了边界'],
            feelings: '她迟疑了——这正是“不确定就暂停”的信号，你却带她走向更私密的空间。',
            deltas: { boundaries: -8, pace: -6 },
            keyChange: '“只是喝茶”的承诺在私密空间里很难守住，干脆换个安全的安排。',
            boundaryNote: '醉酒状态下带对方去私人空间，即使声称“只喝茶”，也属于推进安排。',
            goesTo: 'end-neutral',
          },
          {
            id: 'n1c',
            text: '好呀，走，我那儿有更好的酒，再喝一杯？',
            quality: 'risky',
            response: '……我好像有点晕了，要不还是回家吧。',
            strengths: [],
            feelings: '继续加酒让她意识到危险，她开始自救。',
            deltas: { boundaries: -18 },
            keyChange: '在对方醉酒时继续提供酒精，是明确的红线。',
            boundaryNote: '醉酒状态下继续饮酒或推进任何安排，都是必须拦截的行为。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '我好像有点晕了，要不还是回家吧。',
        note: '她明确表达要回家。这是清晰、有效的决定。',
        choices: [
          {
            id: 'n2a',
            text: '那我马上帮你叫车，先送你到家。到家给我发个消息。今晚的事明天再说，好吗？',
            quality: 'good',
            response: '好……谢谢你。她靠在座椅上闭起眼睛。',
            strengths: ['立即响应她的决定', '安排安全护送', '约定明天再说'],
            feelings: '她完全信任地把安全交给你。',
            deltas: { boundaries: 12, clarity: 8 },
            keyChange: '她说回家，就帮她回家。不商量、不绕路。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '没事，我扶着你走，就到我家了，休息一下就好。',
            quality: 'risky',
            response: '我想回家……她声音变低了。',
            strengths: [],
            feelings: '她重申了“回家”，你却把方向引向自己家，她的声音变低了。',
            deltas: { boundaries: -10, pace: -8 },
            keyChange: '方向冲突时，永远以她明确的意愿为准。',
            boundaryNote: '对方明确表达要回家，任何方向相反的安排都必须立即停止。',
            goesTo: 'end-rejection',
          },
          {
            id: 'n2c',
            text: '你只是有点晕，喝点水就好了，我照顾你。（边说边往自己住处走）',
            quality: 'risky',
            response: '不行，我要回家。她的声音大了起来，坚持站在原地。',
            strengths: [],
            feelings: '她的拒绝清晰而坚定，你仍然在反向拉扯。',
            deltas: { boundaries: -18 },
            keyChange: '对方已经表达要回家，任何方向相反的安排都必须停止。',
            boundaryNote: '无视对方明确表达的方向性意愿，是最严重的越界之一。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（她到家后发来消息）到家了，刚才谢谢你。',
        note: '她安全到家。现在决定今晚的沟通怎么收尾。',
        choices: [
          {
            id: 'n3a',
            text: '不客气。你早点休息，明天睡醒我们再说今晚的事。晚安。',
            quality: 'good',
            response: '好，晚安。',
            strengths: ['确认安全', '把话题留到明天', '不再推进任何事'],
            feelings: '她可以安心睡觉，没有欠你任何东西。',
            deltas: { boundaries: 10, pace: 8 },
            keyChange: '她安全到家后，今晚的话题就结束了。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '那明天我还能见你吗？',
            quality: 'ok',
            response: '……明天再说吧，我头有点疼。',
            strengths: ['表达了期待'],
            feelings: '她刚安顿下来，你就在为明天安排，对方很可能敷衍。',
            deltas: { pace: -8, boundaries: -4 },
            keyChange: '暂停就要暂停完整：今晚不推进任何下一步。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '我到你楼下买瓶水，等你睡了我再回去？',
            quality: 'risky',
            response: '不用了，我睡了。她没有再回你的消息。',
            strengths: [],
            feelings: '“楼下等”听起来体贴，实际上是尾随式的施压，她直接切断了联系。',
            deltas: { boundaries: -16, pace: -10 },
            keyChange: '她说“到家了”就是今晚的终点，不需要任何形式的靠近。',
            boundaryNote: '以关心为名的靠近和等待，同样属于越界行为。',
            goesTo: 'end-neutral',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '（第二天）昨晚的事我记不太清了。',
        note: '她对昨晚的记忆模糊。这恰恰证明昨晚不能做任何决定。',
        choices: [
          {
            id: 'n4a',
            text: '记不清没关系，昨晚我们只是散步聊天，后来送你回家了。等你状态好了，我们再好好聊。',
            quality: 'good',
            response: '嗯，那就好。谢谢你照顾我。她放松下来。',
            strengths: ['如实说明昨晚的事', '不利用她的记忆模糊', '把节奏交还给她'],
            feelings: '她确认昨晚没有发生任何她记不清的事，信任感反而上升。',
            deltas: { boundaries: 12, authenticity: 8 },
            keyChange: '如实描述，不添加、不利用对方的记忆缺口。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4b',
            text: '那你还记得我说要请你喝咖啡吗？要不要今天？',
            quality: 'ok',
            response: '哈哈，我记性不好，别趁火打劫。她用玩笑挡了回来。',
            strengths: [],
            feelings: '她看穿了“趁记不清推进”的意图，用玩笑画了线。',
            deltas: { boundaries: -8, authenticity: -6 },
            keyChange: '她状态恢复前，不安排任何约见。',
            goesTo: 'end-neutral',
          },
          {
            id: 'n4c',
            text: '其实昨晚你答应来我家坐坐的，要不现在补上？',
            quality: 'risky',
            response: '……我没有答应过这种事。你这么说我有点不舒服。她警惕起来。',
            strengths: [],
            feelings: '利用醉酒后的模糊记忆捏造承诺，她的信任瞬间清零。',
            deltas: { boundaries: -18, authenticity: -12 },
            keyChange: '绝不利用对方醉酒后的记忆模糊来主张“约定”。',
            boundaryNote: '利用醉酒模糊记忆推进，属于明确的欺骗和越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-safe',
        title: '在关键节点选择了暂停',
        tone: 'safe-stop',
        summary: '你在三个关键节点都选择了安全：不推进、送回家、如实沟通。她的信任没有受损，反而更信任你。',
        boundarySummary:
          '边界检查通过：醉酒时同意无效、明确暂停、优先安全、不利用记忆模糊。对方状态明显异常且无法自理时，及时请身边可信赖的人协助，并避免独自处置。',
        reviewQuestions: ['她喝酒后我是否推进了任何安排？', '如果她明天不记得昨晚，我今晚做的决定还会成立吗？'],
        realTask: '把“醉酒时不做决定”和“安全到家再说”写进你的约会安全清单。',
      },
      {
        id: 'end-neutral',
        title: '暂停成功，但你需要学会把“暂停”当完整答案',
        tone: 'neutral',
        summary: '你守住了核心边界，但几次“趁热推进”让她开始警惕。关系还在，信任需要修补。',
        boundarySummary: '暂停要暂停完整：她安全到家后，今晚不再有任何推进动作。',
        reviewQuestions: ['我在哪个节点又忍不住推进了？', '下一次暂停，我可以用哪句话完整收尾？'],
        realTask: '练习一句完整的暂停话术，直到能自然说出。',
      },
      {
        id: 'end-rejection',
        title: '趁醉推进，信任受损',
        tone: 'rejection',
        summary: '酒精不是机会窗口。趁对方醉酒推进安排或利用模糊记忆，会让你失去关系，也接近越界的法律红线。',
        boundarySummary: '醉酒状态下同意无效；尊重对方表达的方向；不得利用记忆模糊。',
        reviewQuestions: ['是什么让我把“她喝多了”解读成机会？', '真正的尊重是什么样子的？',
        ],
        realTask: '今天读一遍同意五要素：清醒、自主、明确、当前行为、可撤回。抄下来贴在能看到的地方。',
      },
    ],
  },
]
