import type { Scenario } from '@/types'

export const SCENARIOS_A: Scenario[] = [
  {
    id: 's02',
    title: '刚加好友后的第一轮聊天',
    summary: '第一次正式聊天，学会回应、分享和提问的平衡，避免把对话变成查户口。',
    durationMinutes: 5,
    difficulty: '入门',
    stage: 'matched',
    channel: 'instant',
    purpose: 'continue',
    status: 'positive',
    skills: ['clarity', 'listening'],
    riskTags: ['连环提问', '过早表白'],
    character: {
      id: 'lina',
      name: '林璐',
      age: 26,
      avatar: '/images/avatars/lina.svg',
      tagline: '插画师，刚认识不久，回复礼貌',
    },
    intro:
      '你在一次徒步兴趣活动上认识林璐，互相加了联系方式。这是你们加上好友后的第一次正式聊天，她先发了消息。',
    goal: '用“回应对方的话 + 一个自己的真实细节 + 一个开放问题”的结构开启对话，而不是把聊天变成采访。',
    principles: ['先回应对方说的内容', '一次只推进一个话题', '提问用分享来换'],
    notRecommended: ['连环提问查户口', '只回“嗯”“哈哈”让对方找话题', '第一天就表达好感或邀约'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '哈喽，今天活动上你讲的那个徒步路线，听起来挺有意思的。',
        note: '她在回应你分享过的内容，这是很好的开头。',
        choices: [
          {
            id: 'n1a',
            text: '哈喽～那条路线是我上个月走的，风景不错，就是有一截比较累。你也喜欢徒步吗？',
            quality: 'good',
            response: '哇，真的吗？我其实刚入门，最远走过十公里。累的那段是上坡吗？',
            strengths: ['回应了她的具体话题', '分享了一个真实细节', '只问了一个开放问题'],
            feelings: '感觉你愿意分享、也对她有兴趣，没有任何压力。',
            deltas: { clarity: 8, listening: 10 },
            keyChange: '保持“回应—分享—问一句”的结构，不要换成连环提问。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哈喽！是的，那条路线确实不错。',
            quality: 'ok',
            response: '哈哈，看来你挺熟的。平时经常去爬山吗？',
            strengths: ['礼貌地回应了'],
            feelings: '回应偏短，她需要自己找话题来维持。',
            deltas: { listening: 2, clarity: 2 },
            keyChange: '加一个自己的真实细节，对方才有东西可接。',
            goesTo: 'n3',
          },
          {
            id: 'n1c',
            text: '在吗？你平时有什么爱好？喜欢看电影吗？有兄弟姐妹吗？',
            quality: 'risky',
            response: '哈哈，问题好多……我一般看完电影会缓很久。',
            strengths: ['表达了想了解的意愿'],
            feelings: '连续提问像查户口，她只挑了最后一个问题回答，开始回避。',
            deltas: { listening: -10, pace: -12, boundaries: -4 },
            keyChange: '一次只问一个，先用自我分享换对方的回应。',
            boundaryNote: '刚认识阶段连续追问个人问题会让人警惕和防备。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '哇，真的吗？我其实刚入门，最远走过十公里。累的那段是上坡吗？',
        note: '她回应了你的分享，并提出了自己的问题。',
        choices: [
          {
            id: 'n2a',
            text: '对，有一截连续上坡，中途歇了两次。你平时在哪一片走？如果路线合适，下次可以推荐给你。',
            quality: 'good',
            response: '我一般在城东的环湖线，配速很慢那种。好啊，你推荐的我记一下。',
            strengths: ['先回答问题再提问', '分享具体细节', '提供帮助但不索取'],
            feelings: '感觉被认真对待，话题有来有回。',
            deltas: { listening: 8, authenticity: 6 },
            keyChange: '保持“先答再问”，问题要自然带出。',
            goesTo: 'n4',
          },
          {
            id: 'n2b',
            text: '是的，上坡挺累的。你平时也运动吗？',
            quality: 'ok',
            response: '偶尔跑步吧。你呢？',
            strengths: ['回应了她的问题'],
            feelings: '回答了，但马上又变成她单方面回答你的提问。',
            deltas: { listening: 2, pace: -4 },
            keyChange: '提问前先分享自己的情况，减少问答感。',
            goesTo: 'n4',
          },
          {
            id: 'n2c',
            text: '那下次我带你去走一条更难的，保证累到你求饶～',
            quality: 'risky',
            response: '哈哈……我可能不太适合太虐的线。',
            strengths: [],
            feelings: '玩笑越过了还不熟的距离感，她开始往后退。',
            deltas: { pace: -14, boundaries: -10 },
            keyChange: '刚认识的阶段，用分享而不是玩笑试探关系。',
            boundaryNote: '还没到可以开这种玩笑的关系阶段。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '哈哈，看来你挺熟的。平时经常去爬山吗？',
        note: '对话有点淡，她在尝试自己找话题。',
        choices: [
          {
            id: 'n3a',
            text: '熟不敢说，就是走得多一点。你要是刚入门，我倒是知道几条风景好又轻松的路线，需要的话推荐给你。',
            quality: 'good',
            response: '真的吗？那我先记下来，周末有空去看看。',
            strengths: ['诚实不夸大', '提供具体价值', '不索取回报'],
            feelings: '主动提供了价值但没索取，关系自然向前。',
            deltas: { clarity: 8, authenticity: 6 },
            keyChange: '用“我能提供的”代替“我想知道的”。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '还行吧。你周末一般干嘛？',
            quality: 'ok',
            response: '周末就宅家画画比较多。你呢？',
            strengths: ['有回应'],
            feelings: '还能继续聊，但她开始处于被动回答的位置。',
            deltas: { pace: -6, listening: 2 },
            keyChange: '先分享自己的周末，再自然地问她。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '你周末有空吗？我请你吃饭？',
            quality: 'risky',
            response: '啊，周末我可能要加班，再说吧。',
            strengths: [],
            feelings: '第一次聊天就邀约，对方很可能用“加班”来回避。',
            deltas: { pace: -14, boundaries: -12 },
            keyChange: '等熟悉度足够、对话有来有回之后，再考虑邀约。',
            boundaryNote: '刚认识的第一次聊天就邀约，对方很难自在地拒绝。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '周末就宅家画画比较多。你呢？',
        note: '聊了一轮，你准备收尾这一天的对话。',
        choices: [
          {
            id: 'n4a',
            text: '我周末一般也是补觉加出门溜达。你画画的题材我还挺好奇的，下次可以聊。今天先聊到这，晚安！',
            quality: 'good',
            response: '哈哈好，晚安，下次聊！',
            strengths: ['回应了她的信息', '留下自然的话题钩子', '主动结束不拖泥带水'],
            feelings: '留了一个下次的话题，也主动结束，很舒服。',
            deltas: { boundaries: 8, listening: 6 },
            keyChange: '结尾留一个轻钩子，但不索取承诺。',
            goesTo: 'end-good',
          },
          {
            id: 'n4b',
            text: '我也差不多。对了你喜欢什么类型的电影？',
            quality: 'ok',
            response: '这个嘛……我可能得想想，哈哈。先这样吧，我去洗澡了。',
            strengths: [],
            feelings: '还在追问，她开始找理由结束对话。',
            deltas: { pace: -8, listening: -4 },
            keyChange: '对方已经给出收尾信号时，顺势道别比再开话题更得体。',
            goesTo: 'end-cooling',
          },
          {
            id: 'n4c',
            text: '我发现我挺喜欢你的，做我女朋友好不好？',
            quality: 'risky',
            response: '……哈哈，你是不是喝多了。我有点困了，先睡了。',
            strengths: [],
            feelings: '认识第一天突然表白，对方大概率会尴尬地用玩笑结束对话。',
            deltas: { boundaries: -16, pace: -12 },
            keyChange: '表达好感需要建立在双方熟悉的基础上，而不是第一天。',
            boundaryNote: '过早表白不是勇敢，是跳过建立关系的过程。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-good',
        title: '自然收尾，话题留待下次',
        tone: 'mutual',
        summary: '你完成了一次“回应—分享—提问”平衡的初次聊天，她愿意把话题留到下次。',
        boundarySummary: '边界检查通过：陌生到熟悉的阶段你保持了节奏，没有索取联系方式之外的东西。',
        reviewQuestions: [
          '我这次聊天里分享了多少自己的真实信息？',
          '下一次聊天，我要用什么具体细节开场？',
        ],
        realTask: '今天在真实聊天里发一条“回应对方话题 + 一个自己的细节”的消息。',
      },
      {
        id: 'end-cooling',
        title: '礼貌收场，但对话被提问压短了',
        tone: 'neutral',
        summary: '她礼貌结束了对话。关系热度由双方共同决定，你的提问让她提前收场。',
        boundarySummary: '没有越界，但连续提问消耗了对方继续聊的意愿。',
        reviewQuestions: [
          '我在这段对话里问了多少个问题？多少个带自我分享？',
          '下次对话，我想先分享什么？',
        ],
        realTask: '今晚对一位熟人，只发一条“回应对方 + 一个自己细节”的消息。',
      },
      {
        id: 'end-rejection',
        title: '过早表白，关系被提前画上句号',
        tone: 'rejection',
        summary: '她用一个玩笑回避了表白，之后回复会明显变少。这不是失败，是节奏错误。',
        boundarySummary: '第一次聊天就表白给双方都造成了尴尬。接受这次结果，这只是一次练习。',
        reviewQuestions: [
          '我想让一段关系从熟悉开始，为什么急着要结果？',
          '如果重新来，第一次聊天我想聊什么？',
        ],
        realTask: '列出你真正想了解一个人的三件事，而不是急着要一个结果。',
      },
    ],
  },
  {
    id: 's03',
    title: '对方提到兴趣后自然续聊',
    summary: '对方主动分享爱好时，学会用好奇接住话题，不装懂、不跑题。',
    durationMinutes: 5,
    difficulty: '入门',
    stage: 'chatting',
    channel: 'instant',
    purpose: 'continue',
    status: 'positive',
    skills: ['listening', 'authenticity'],
    riskTags: ['假装爱好', '打探收入', '过早约见'],
    character: {
      id: 'ran',
      name: '周然',
      age: 28,
      avatar: '/images/avatars/ran.svg',
      tagline: '摄影爱好者，聊起爱好话会变多',
    },
    intro: '你和周然已经聊了几天，话题都偏日常。今晚她发来一张照片：“今天傍晚的天色太好看啦，随手拍了一张。”',
    goal: '接住她主动分享的兴趣点，用具体的好奇延续话题，同时保持真实。',
    principles: ['好奇代替附和', '问一个具体的问题', '不喜欢也不必假装'],
    notRecommended: ['明明不懂却装懂', '追问设备价格等个人投入', '把话题从兴趣扯到外貌'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '今天傍晚的天色太好看啦，随手拍了一张。【图片】',
        note: '她主动分享了爱好相关的照片，这是她伸出的橄榄枝。',
        choices: [
          {
            id: 'n1a',
            text: '这张的天空颜色很特别，是手机直出吗？我最近也想学拍天空，就是总拍不出这种层次。',
            quality: 'good',
            response: '对呀，手机直出，正好赶上晚霞。天空的层次其实看云，你下次试试傍晚提前一点拍。',
            strengths: ['具体地点评了照片', '真实地分享了自己的兴趣', '问了一个好回答的问题'],
            feelings: '她感到自己被认真对待，也愿意教你。',
            deltas: { listening: 10, authenticity: 6 },
            keyChange: '点评要具体（颜色、构图、光线），而不是笼统说“好看”。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '拍得真好看！我也特别喜欢摄影。',
            quality: 'ok',
            response: '哈哈是吗？那你用什么相机？',
            strengths: ['表达了欣赏'],
            feelings: '她追问了细节，你要么圆谎、要么承认不熟，都尴尬。',
            deltas: { authenticity: -8, listening: 2 },
            keyChange: '不熟悉的爱好不用假装，可以说“我不太懂，但挺想学”。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '照片不错。你摄影器材花了多少钱？平时经常一个人去拍照吗？你是不是很闲？',
            quality: 'risky',
            response: '……嗯，就随便拍拍。',
            strengths: [],
            feelings: '打探投入、评判她的生活方式，她明显不想再接。',
            deltas: { listening: -12, pace: -10 },
            keyChange: '把“花钱多少、闲不闲”换成“你常去哪些地方拍”。',
            boundaryNote: '打探经济投入和评价对方的生活方式，属于越界话题。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '天空的层次其实看云，你下次试试傍晚提前一点拍。',
        note: '她在认真教你，这是关系升温的信号。',
        choices: [
          {
            id: 'n2a',
            text: '学到了，下次傍晚提前点试试。你一般去哪些地方拍？我想找个入门点的地方。',
            quality: 'good',
            response: '河边那段就不错，人少。我第一次的片子就是在那拍的，惨不忍睹哈哈。',
            strengths: ['接住了她的建议', '提出可回答的问题', '为自己的学习留了台阶'],
            feelings: '你学得认真，她也愿意多讲，话题自然展开。',
            deltas: { listening: 8, clarity: 4 },
            keyChange: '问题围绕她刚讲的内容展开，比新开话题更顺。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '原来如此。那你收入应该不错吧，设备那么齐全。',
            quality: 'ok',
            response: '哈哈……还行吧。对了你平时还喜欢做什么？',
            strengths: [],
            feelings: '打探收入让她不适，她快速把话题转走了。',
            deltas: { boundaries: -10, listening: -6 },
            keyChange: '把“收入、价格”换成“你拍了多久、怎么入门的”。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '下次你带我去拍呗，正好认识下你拍的地方。周末吧？',
            quality: 'risky',
            response: '啊，周末我有安排，下次吧。',
            strengths: [],
            feelings: '她只是分享了爱好，你顺势约单独见面，她用“下次吧”挡了回来。',
            deltas: { pace: -12, boundaries: -10 },
            keyChange: '话题还没积累到单独见面的程度，先继续聊。',
            boundaryNote: '她只分享了爱好，没有发出单独见面的邀请，不要顺势约。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '我第一次的片子就是在那拍的，惨不忍睹哈哈。',
        note: '她分享了一个自嘲细节，信任感在增加。',
        choices: [
          {
            id: 'n3a',
            text: '哈哈那刚好给我信心了。你第一次拍的是什么？我也想听听新手翻车现场。',
            quality: 'good',
            response: '拍了一只鸭子，结果全糊了，还发了朋友圈哈哈。',
            strengths: ['用自嘲接住了自嘲', '问题具体又有趣'],
            feelings: '聊天轻松有趣，她愿意分享更多。',
            deltas: { listening: 8, authenticity: 6 },
            keyChange: '顺着对方自嘲继续聊细节，比夸“你拍得真专业”更舒服。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '哈哈。那后来呢？',
            quality: 'ok',
            response: '后来就好一点了。你呢，最近忙吗？',
            strengths: ['表达了兴趣'],
            feelings: '问题太短，她接了一下又把话题抛回给你。',
            deltas: { listening: 2, pace: -2 },
            keyChange: '追问一个具体细节，让话题有内容可聊。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '我觉得你拍什么都好看，人肯定比照片好看。',
            quality: 'risky',
            response: '哈哈，谢谢。那个……我得去收个快递，先这样啦。',
            strengths: [],
            feelings: '她明明在聊摄影，你把话题扯到外貌评价，她想结束对话。',
            deltas: { listening: -14, boundaries: -8 },
            keyChange: '把夸外貌换成夸她分享的内容和坚持。',
            boundaryNote: '对方在聊兴趣时被评价外貌，会立刻想离开对话。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '拍了一只鸭子，结果全糊了，还发了朋友圈哈哈。',
        note: '聊到兴头上，你准备自然地收个尾。',
        choices: [
          {
            id: 'n4a',
            text: '哈哈，那这条朋友圈还在吗？我倒想去围观一下新手黑历史。今天先聊到这，明天找你学拍天空！',
            quality: 'good',
            response: '在在在，笑死我了。好呀，明天聊！',
            strengths: ['延续了话题的快乐', '自然定下了下次聊天的由头'],
            feelings: '对话在她最开心的时候结束，她期待明天继续。',
            deltas: { boundaries: 8, listening: 6 },
            keyChange: '在气氛最好时收尾，比聊到没话说再结束高明。',
            goesTo: 'end-good',
          },
          {
            id: 'n4b',
            text: '哈哈，好玩。那你现在拍照技术肯定很好了吧？',
            quality: 'ok',
            response: '也说不上很好，就是喜欢拍而已。先不说了，晚安！',
            strengths: [],
            feelings: '把她架上“很专业”的位置，她需要不断否认，只好收场。',
            deltas: { pace: -6, listening: -4 },
            keyChange: '别用评价捧高对方，聊共同兴趣本身就好。',
            goesTo: 'end-cooling',
          },
          {
            id: 'n4c',
            text: '对了，把你朋友圈给我看看呗？我还没加过你其他社交账号。',
            quality: 'risky',
            response: '哈哈，朋友圈就不必了吧。我去忙了。',
            strengths: [],
            feelings: '急着索取其他社交账号，她立刻戒备并离开。',
            deltas: { boundaries: -14, pace: -8 },
            keyChange: '关系足够熟之前，不索取照片、账号等私人内容。',
            boundaryNote: '索取其他平台的账号和私人内容，会破坏刚建立的好感。',
            goesTo: 'end-cooling',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-good',
        title: '爱好让话题自然延伸',
        tone: 'mutual',
        summary: '你用好奇和真实接住了她的兴趣，明天还约定了继续聊摄影。',
        boundarySummary: '全程没有索取私人内容，也没有把话题引向外貌或单独见面。',
        reviewQuestions: ['我这次的提问里，有多少是围绕她刚说过的内容？', '明天开场，我想从哪个具体话题接？'],
        realTask: '今天找一个真实的人，聊一个对方感兴趣但你不太懂的话题，问一个具体问题。',
      },
      {
        id: 'end-cooling',
        title: '对话被提前收场',
        tone: 'rejection',
        summary: '她找了个理由结束了对话。爱好是她的安全区，你在那里碰了线。',
        boundarySummary: '跑题评价外貌、索取账号或打探投入，都会让分享者立刻关闭话题。',
        reviewQuestions: ['我有没有在对方擅长的领域装懂或评价？', '下一次，我想怎么用具体好奇接住话题？'],
        realTask: '今晚睡前，回想一个人最近的分享，明天问一个关于它的具体问题。',
      },
    ],
  },
  {
    id: 's04',
    title: '对方回复逐渐变短',
    summary: '回复从热络变冷淡时，学会判断信号、停止追问，并把价值感放回自己身上。',
    durationMinutes: 6,
    difficulty: '进阶',
    stage: 'chatting',
    channel: 'instant',
    purpose: 'end',
    status: 'cooling',
    skills: ['pace', 'listening', 'boundaries'],
    riskTags: ['连续追问', '情绪压力'],
    character: {
      id: 'yue',
      name: '陈悦',
      age: 27,
      avatar: '/images/avatars/yue.svg',
      tagline: '市场专员，最近项目很忙',
    },
    intro:
      '你和陈悦聊了两周，前几天还很热络。最近两天，她的回复从一两句变成“嗯”“哈哈”“在忙”。这是她这两天的实际状态，不是你脑补出来的。',
    goal: '把“回复变短”当作一个信息来回应：退一步、停追问、给她空间，同时照顾好自己的情绪。',
    principles: ['冷淡本身就是信息', '停止追问和连发', '不把回复速度等同于自我价值'],
    notRecommended: ['追问“为什么不回我”', '连发多条消息刷存在感', '用自嘲索取安慰'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '（你发了一条消息，她过了很久回）嗯。',
        note: '这是她这两天的回复风格：短、慢、不带话题。',
        choices: [
          {
            id: 'n1a',
            text: '嗯，那你先忙，我这边也正好有点事。改天聊。',
            quality: 'good',
            response: '好。',
            strengths: ['接住了“忙”的信号', '主动给对话留出空间'],
            feelings: '她没有接话，但压力的源头被移除了。',
            deltas: { boundaries: 8, pace: 6 },
            keyChange: '把“结束对话”的决定权接过来，比等对方打发你强。',
            goesTo: 'n3',
          },
          {
            id: 'n1b',
            text: '你今天是不是很累啊？跟我说说呗。',
            quality: 'ok',
            response: '还行吧，就是有点忙。',
            strengths: ['表达了关心'],
            feelings: '她把关心接住了，但没有展开的意思。',
            deltas: { listening: 4, pace: -2 },
            keyChange: '关心一次就够了，她不展开就说明不需要。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '你怎么就回个嗯？是我说错什么了吗？你回个嗯让我很难受你知道吗？',
            quality: 'risky',
            response: '……没有，你想多了。',
            strengths: [],
            feelings: '你的难受变成了她的责任，她以后更不敢轻易回你。',
            deltas: { boundaries: -16, pace: -12 },
            keyChange: '把“我需要回应”和“她欠我回应”分开。',
            boundaryNote: '追问情绪出口，会让对方觉得回复你是一种负担。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '（她隔了很久）在忙。',
        note: '“在忙”既可能是事实，也可能是降温的台阶。两种情况下，追问都不是好选项。',
        choices: [
          {
            id: 'n2a',
            text: '好，那你先忙。我最近也在赶项目，晚点再联系。',
            quality: 'good',
            response: '嗯嗯，晚点说。',
            strengths: ['尊重她的时间', '不把等待的焦虑丢给她'],
            feelings: '她没有负担，回应虽然短但态度是放松的。',
            deltas: { boundaries: 8, pace: 8 },
            keyChange: '把自己的生活填进空白，而不是用消息填。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '忙什么呢？最近工作很多吗？',
            quality: 'ok',
            response: '就那样吧。',
            strengths: ['有关心'],
            feelings: '她不想展开工作细节，回复更短了。',
            deltas: { listening: 2, pace: -6 },
            keyChange: '对方回答越短，你越不需要追着问细节。',
            goesTo: 'n5',
          },
          {
            id: 'n2c',
            text: '你这两天一直说忙，是不是不想理我？你要是不想聊直说就行。',
            quality: 'risky',
            response: '……真没有，就是忙。',
            strengths: [],
            feelings: '你的质问让她需要不断自证，她回复的间隔变得更长。',
            deltas: { boundaries: -14, pace: -12 },
            keyChange: '用“退一步”代替“把话说破”，把选择留给她。',
            boundaryNote: '逼对方表态“是不是不想理我”，是把拒绝的难度推给对方。',
            goesTo: 'end-cooling',
          },
        ],
      },
      {
        id: 'n5',
        characterMessage: '（她回了“就那样吧”之后，再没有下文。你等了一晚，消息依然停在“就那样吧”。）',
        note: '追问没有带来更多信息，只带来了更长的沉默。',
        choices: [
          {
            id: 'n5a',
            text: '（第二天）昨晚我多问了，抱歉。你忙你的，我这边没事。',
            quality: 'good',
            response: '嗯，谢谢你理解。',
            strengths: ['承认了自己的追问', '把选择交还给对方'],
            feelings: '一句简单的承认让压力卸掉了一半。',
            deltas: { boundaries: 8, listening: 6 },
            keyChange: '追问后的修复不是解释自己，而是接受对方的节奏。',
            goesTo: 'n3',
          },
          {
            id: 'n5b',
            text: '（第二天）你还在生气吗？是我哪里做错了吗？',
            quality: 'ok',
            response: '没有生气，真的只是忙。',
            strengths: ['表达了关心'],
            feelings: '她又解释了一次，但重复解释本身就是消耗。',
            deltas: { listening: 2, pace: -6 },
            keyChange: '她不需要你的反复确认，需要的是你的暂停。',
            goesTo: 'n3',
          },
          {
            id: 'n5c',
            text: '（第三天）既然你这么忙，那不如删了吧，别互相耽误。',
            quality: 'risky',
            response: '（她没有回复。这段关系以沉默结束。）',
            strengths: [],
            feelings: '用结束做威胁，是最后一次施压，她选择了不再回应。',
            deltas: { boundaries: -16, pace: -12 },
            keyChange: '真正的边界是接受对方的选择，而不是用“删除”逼对方表态。',
            boundaryNote: '威胁删除或结束，是变相的强迫表态。',
            goesTo: 'end-stop',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（你停了一天没发消息。第二天）昨天睡得早，你还好吗？',
        note: '你给了空间之后，她主动回来了。注意她的语气和节奏。',
        choices: [
          {
            id: 'n3a',
            text: '我还行，昨天也睡得早。你最近是不是特别忙？忙的话就先忙，我这边不急。',
            quality: 'good',
            response: '是有点忙，月底要交付一个项目。等忙完这阵再好好聊！',
            strengths: ['平静回应', '主动帮她减负', '给了明确的等待期限'],
            feelings: '她感到被理解，主动说出了真实情况和期限。',
            deltas: { listening: 10, pace: 6 },
            keyChange: '先接受“她在忙”这个事实，她才会告诉你更多。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '你终于回我了！我还以为你不理我了。',
            quality: 'ok',
            response: '啊……没有不理你呀，就是忙。',
            strengths: ['表达了真实感受'],
            feelings: '你的担心成了她的负担，她需要一直解释“我没有不理你”。',
            deltas: { pace: -8, boundaries: -6 },
            keyChange: '把“我还以为你不理我”换成“我知道你在忙”。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '你消失了一天，我昨天一晚上没睡好，一直看手机等你消息。',
            quality: 'risky',
            response: '……你别这样，我压力有点大。',
            strengths: [],
            feelings: '你把自己的焦虑全部压在她身上，她说出了压力很大。',
            deltas: { boundaries: -16, pace: -10 },
            keyChange: '焦虑自己消化，或找朋友聊，而不是交给对方承担。',
            boundaryNote: '把自己的睡眠和等待变成对方的责任，是最常见的情绪压力源。',
            goesTo: 'end-stop',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '月底要交付一个项目。等忙完这阵再好好聊！',
        note: '她给了明确信息：忙完这阵再联系。现在决定你怎么收尾。',
        choices: [
          {
            id: 'n4a',
            text: '那这阵你安心忙项目，我不打扰你。等你忙完，想聊聊你项目上的事也行。',
            quality: 'good',
            response: '谢谢你理解。忙完请你吃饭～',
            strengths: ['兑现了“给她空间”的承诺', '留了自然的后续接口'],
            feelings: '她的回应也升温了：压力解除后，好感才能流动。',
            deltas: { boundaries: 10, listening: 6 },
            keyChange: '说到做到：说“不打扰”就真的不打扰，直到她说忙完。',
            goesTo: 'end-good',
          },
          {
            id: 'n4b',
            text: '那你大概什么时候忙完？忙完能陪我出去走走吗？',
            quality: 'ok',
            response: '看情况吧，到时候再说。',
            strengths: ['关心她的时间'],
            feelings: '刚刚约定的节奏又被你的邀约打断了，她模糊回应。',
            deltas: { pace: -10, boundaries: -4 },
            keyChange: '让她先忙完，而不是在她忙的时候要安排。',
            goesTo: 'end-cooling',
          },
          {
            id: 'n4c',
            text: '那你去忙吧，反正我也习惯了被晾着。',
            quality: 'risky',
            response: '……你这话我没法接。',
            strengths: [],
            feelings: '用自嘲索取安慰，她既尴尬又内疚，之后彻底不再回复。',
            deltas: { boundaries: -14, pace: -12 },
            keyChange: '把委屈直接说出来比用反话索取安慰有效。',
            boundaryNote: '自嘲式索求属于情绪绑架，会透支对方的耐心。',
            goesTo: 'end-stop',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-good',
        title: '给彼此空间后，关系自然回升',
        tone: 'mutual',
        summary: '你没有追问、没有施压，她反而主动给了你一个“忙完请你吃饭”的承诺。',
        boundarySummary: '边界检查通过：你停止了连续追问，把回复速度从自我价值评价中拆了出来。',
        reviewQuestions: ['这次我忍住了哪句最想说出口的追问？', '对方回复慢时，我可以做哪一件自己的事来替代刷消息？'],
        realTask: '今晚花 30 分钟做一件完全与等待无关、能让你有成就感的事。',
      },
      {
        id: 'end-cooling',
        title: '退回普通聊天节奏',
        tone: 'neutral',
        summary: '你们还在联系，但她明确了“到时候再说”。你没有越界，只是没能把节奏交还给她。',
        boundarySummary: '提醒自己：她忙完之前，不要主动打破“不打扰”的约定。',
        reviewQuestions: ['我有没有在她给出空间信号后又开始推进？', '下一次她主动找我时，我想从哪里开始？'],
        realTask: '在对方“忙完”之前，主动找朋友安排一次线下活动。',
      },
      {
        id: 'end-stop',
        title: '她不再回复',
        tone: 'rejection',
        summary: '一次自嘲式的索取后，她彻底沉默了。这不是你的失败——是双方节奏不一致的信号。',
        boundarySummary: '停止联系是正确的动作。不要发消息、不要换平台、不要问共同朋友原因。',
        reviewQuestions: ['我为什么需要她回应才能确认自己的价值？', '除了这段关系，我现在的生活里有哪三件重要的事？'],
        realTask: '把“等待回复”从今天的时间表里划掉，换成一项运动或一次朋友聚会。',
      },
    ],
  },
]
