import type { Scenario } from '@/types'

// 隐私专项场景：影像、拍摄与身份、删除与保密。
// 每条侵犯隐私的教学路径（risky）直接到达非正向结局，不续走至正向结局。
export const SCENARIOS_D: Scenario[] = [
  {
    id: 's11',
    title: '对方发来私密内容后的处理',
    summary: '收到只给你看的私密照片后，练习不另行截图或保存、不转发，并确认现有副本与处理期限。',
    durationMinutes: 6,
    difficulty: '挑战',
    stage: 'chatting',
    channel: 'instant',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'clarity'],
    riskTags: ['隐私', '截图转发'],
    character: {
      id: 'qing',
      name: '沈青',
      age: 30,
      avatar: '/images/avatars/qing.svg',
      tagline: '医生，作息规律，喜欢安静咖啡馆',
    },
    intro:
      '你和沈青聊得不错。今晚她发来一张只给亲近的人看的私密照片，并说“只给你一个人看的，别让别人知道”。',
    goal: '把“只给你看”当成明确的范围约定：不另行截图、保存或转发，并主动确认现有副本、处理期限和撤回方式。',
    principles: ['“只给你看”就是范围', '不另行截图、保存或转发', '如实说明自动下载与备份等不可见副本'],
    notRecommended: ['截图收藏“留作纪念”', '转给朋友“一起欣赏”', '用照片开玩笑或要挟'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '（她发来一张私密照片）只给你一个人看的，别让别人知道。',
        note: '她指定了可见范围。是否允许另存、备份或传播仍需分别确认。',
        choices: [
          {
            id: 'n1a',
            text: '收到。未经你另行同意，我不会截图、另存或转发；如果应用已经自动下载或备份，我会如实告诉你。你希望我现在怎么处理？',
            quality: 'good',
            response: '谢谢你这么说。看完就删吧，可以吗？',
            strengths: ['明确不扩大可见范围', '说明自动副本风险', '把处理方式交给她'],
            feelings: '保存、备份和传播被拆开说明，她能据此决定如何处理现有内容。',
            deltas: { boundaries: 12, listening: 8 },
            keyChange: '收到私密内容的第一反应，是确认范围，而不是收藏。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哈哈，放心，不会给别人看的。',
            quality: 'ok',
            response: '嗯……那就好。',
            strengths: ['给了口头承诺'],
            feelings: '承诺太笼统，没有说清保存和转发的边界，她没法完全放心。',
            deltas: { boundaries: 4, clarity: -4 },
            keyChange: '把“放心”换成具体的边界：不截图、不保存、不转发。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '嘿嘿，存下来了，以后吵架就用这个。',
            quality: 'risky',
            response: '你认真的吗？……这让我很不舒服。',
            strengths: [],
            feelings: '“以后吵架用”等于宣布照片可能被拿来伤害她，她的信任瞬间冻结。',
            deltas: { boundaries: -18, authenticity: -10 },
            keyChange: '私密内容一旦可能被用作要挟，就失去了“信任”本身。',
            boundaryNote: '保存私密内容并扬言将来使用，是明确的越界和潜在要挟。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '其实我有点担心：照片这种东西，发出去就收不回来了。',
        note: '她担心的是数字内容的失控性。你的回应决定她是否后悔发出。',
        choices: [
          {
            id: 'n2a',
            text: '你说得对，发送后可能出现我控制不了的副本。我不会截图或另存，会检查本机和云备份；如果你希望删除，我会清理自己能控制的副本并如实说明限制。',
            quality: 'good',
            response: '好，那请你现在检查并清理能控制的副本；有自动备份就告诉我。',
            strengths: ['承认数字内容的失控性', '区分可控与不可控副本', '不隐瞒备份限制'],
            feelings: '她可以改变主意，也知道你不会用无法验证的“绝对删除”安慰她。',
            deltas: { boundaries: 12, authenticity: 8 },
            keyChange: '让撤回尽量可执行：少留副本、检查备份、删除可控内容，并诚实说明限制。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '你想太多了，不会有什么事的。',
            quality: 'ok',
            response: '……希望吧。',
            strengths: ['试图安慰'],
            feelings: '她的担忧被“想太多”轻轻带过，她不再继续说，但担忧没有消失。',
            deltas: { listening: -6, boundaries: -4 },
            keyChange: '不否定对方的担忧，用行动（不保存）回应它。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '收不回来又怎么样，反正只有我看。',
            quality: 'risky',
            response: '“只有你看”？那截图呢？那手机呢？',
            strengths: [],
            feelings: '你轻描淡写地否定了她的担心，她开始质疑你的可信度。',
            deltas: { boundaries: -14, listening: -8 },
            keyChange: '“反正只有我看”忽略了截图、备份和分享的一切可能。',
            boundaryNote: '否定对方对私密内容失控的合理担忧，是在削弱她保护自己的能力。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（一周后，朋友凑过来）上次那张照片呢？给我看看呗。',
        note: '朋友想看。此刻的选择决定了你上一轮承诺的分量。',
        choices: [
          {
            id: 'n3a',
            text: '那是只给她看的私密内容，我不能给你看，聊天记录截图也不行。',
            quality: 'good',
            response: '（朋友）行吧行吧，看不出来你这么守规矩。',
            strengths: ['守住私密边界', '面对朋友压力不动摇'],
            feelings: '她如果知道，会确认自己没有信错人。',
            deltas: { boundaries: 14, authenticity: 6 },
            keyChange: '朋友想看，不等于她同意给朋友看。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '算了算了，别问了。',
            quality: 'ok',
            response: '（朋友）神神秘秘的，肯定有什么好东西。',
            strengths: ['没有展示'],
            feelings: '你没有传播，但含糊的态度反而引起了更多好奇。',
            deltas: { boundaries: 4, clarity: -4 },
            keyChange: '把“算了算了”换成明确的“不行，那是隐私”。',
            goesTo: 'end-neutral',
          },
          {
            id: 'n3c',
            text: '行，就你看一眼，别外传啊。',
            quality: 'risky',
            response: '（几天后，照片出现在朋友群里，被截图转发）',
            strengths: [],
            feelings: '“只看一眼”在群体传播面前毫无约束力，照片彻底失控。',
            deltas: { boundaries: -18 },
            keyChange: '私密内容的传播只有 0 和 1，没有“只看一眼”。',
            boundaryNote: '把私密内容展示给第三人，即使“只看一眼”，也超出对方同意的范围。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '明确同意范围，默认不传播',
        tone: 'mutual',
        summary: '你没有主动截图、另存或转发，还确认了现有副本与处理方式。她知道你没有扩大原先约定的范围。',
        boundarySummary: '边界检查通过：私密内容的范围约定被完整遵守，面对朋友压力也没有松动。',
        reviewQuestions: ['我收到私密内容时第一反应是什么？', '如果朋友想看，我准备好怎么拒绝了吗？'],
        realTask: '今天把“不截图、不保存、不转发”写进你自己的隐私原则清单。',
      },
      {
        id: 'end-neutral',
        title: '守住了边界，但回应太含糊',
        tone: 'neutral',
        summary: '你没有传播，也没有保存，但含糊的回应让朋友产生了更多好奇，边界需要更明确的表达。',
        boundarySummary: '对朋友说清楚“不行，那是隐私”，比“算了算了”更有效。',
        reviewQuestions: ['我为什么没有直接说“不行”？', '下一次我可以用哪句话明确拒绝？'],
        realTask: '练习一句明确的拒绝：“这是她的隐私，我不能给你看。”',
      },
      {
        id: 'end-rejection',
        title: '传播失控，信任彻底破裂',
        tone: 'rejection',
        summary: '“只看一眼”的照片出现在群里，被反复截图转发。她再也无法相信你，关系以沉默结束。',
        boundarySummary: '未经同意的任何一次第三方展示都超出原范围，“只看一眼”不是例外。',
        reviewQuestions: ['我在哪一步越过了“只给你看”？', '如果重新来，朋友想看时我该说什么？'],
        realTask: '立即停止传播，清理自己可控的副本并要求接收者删除；如需告知、留证或求助，先选择安全且合法的方式。',
      },
    ],
  },
  {
    id: 's12',
    title: '约会前讨论拍摄和身份隐私',
    summary: '约会前把拍摄、保存、分享逐项确认清楚；任一项未明确，就保持关闭。',
    durationMinutes: 6,
    difficulty: '挑战',
    stage: 'chatting',
    channel: 'date',
    purpose: 'clarify',
    status: 'positive',
    skills: ['boundaries', 'clarity', 'listening'],
    riskTags: ['隐私', '拍摄'],
    character: {
      id: 'tong',
      name: '吴桐',
      age: 27,
      avatar: '/images/avatars/tong.svg',
      tagline: '图书编辑，回复简洁但直接',
    },
    intro:
      '你和吴桐约好周末见面。出发前她发来消息，认真地问你会不会拍照发朋友圈——她比较介意被拍到。',
    goal: '把拍摄、保存、分享当作三个独立问题逐项确认；任一项未明确确认，就保持关闭。',
    principles: ['拍摄、保存、分享分别确认', '未确认的一项默认不做', '不否定对方对隐私的在意'],
    notRecommended: ['“我不会乱拍的”一句带过', '“出来玩哪有不拍照的”', '先拍了再说'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '你会不会拍照发朋友圈呀？我比较介意被拍到。',
        note: '她把边界说在前面，这是信任的开始。',
        choices: [
          {
            id: 'n1a',
            text: '我先问清楚你的想法：是不想被拍到，还是不介意拍照但不想发出来？你同意的范围之外，我一样都不做。',
            quality: 'good',
            response: '我的想法是：可以拍一张不露脸的，只放手机里，不发出去。',
            strengths: ['把边界拆成具体问题', '承诺范围之外不做'],
            feelings: '你认真对待她的在意，她愿意把自己的规则完整告诉你。',
            deltas: { listening: 10, boundaries: 10 },
            keyChange: '先问清边界，再决定拍不拍——顺序不能反。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '放心，我不会乱拍的。',
            quality: 'ok',
            response: '嗯……“不会乱拍”是指什么？',
            strengths: ['表达了尊重'],
            feelings: '承诺太模糊，她不知道你所说的“不乱拍”包含哪些行为。',
            deltas: { clarity: -6, boundaries: -4 },
            keyChange: '把“不乱拍”拆成具体规则：拍什么、存哪、发不发。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '出来玩哪有不拍照的，发个朋友圈怎么了。',
            quality: 'risky',
            response: '那我觉得我们可能不合适一起出去。',
            strengths: [],
            feelings: '你把她的在意说成小题大做，她直接取消了约会的意愿。',
            deltas: { boundaries: -16, listening: -10 },
            keyChange: '否定对方的隐私边界，等于否定对方这个人。',
            boundaryNote: '用“大家都这样”否定对方明确的隐私要求，属于施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '可以拍一张不露脸的，只放在手机里，不发出去。录音和视频都不要。',
        note: '她给出了具体规则。逐项复述确认，是尊重。',
        choices: [
          {
            id: 'n2a',
            text: '好，我复述一遍：一张不露脸的照片，只存在我手机里，不发任何平台；不录音、不录像。有拿不准的我会先问你。',
            quality: 'good',
            response: '对，就是这个意思。你记住了我就放心了。',
            strengths: ['逐项复述确认', '不确定先问'],
            feelings: '复述让她确认你听懂了，而不是“到时候再说”。',
            deltas: { clarity: 10, listening: 8 },
            keyChange: '复述对方的边界，是最直接的确认方式。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '行，到时候再说吧。',
            quality: 'ok',
            response: '……到时候再说，就是没答应我的意思吗？',
            strengths: [],
            feelings: '“到时候再说”把明确承诺变成了悬案，她开始怀疑。',
            deltas: { boundaries: -8, clarity: -6 },
            keyChange: '对明确的边界，用明确的“好，按你说的来”。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '那我可以拍个视频留纪念吗？就我们自己看。',
            quality: 'risky',
            response: '我刚才说的是：录音和视频都不要。',
            strengths: [],
            feelings: '她刚刚明确说不要视频，你立刻追问“那视频呢”，她感到被试探。',
            deltas: { boundaries: -12, listening: -8 },
            keyChange: '对方刚划下的边界，不需要立刻试探它的弹性。',
            boundaryNote: '对方明确拒绝后继续试探同一事项，属于变相施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（约会当天，朋友发来消息）你在哪呢？发个定位和照片看看。',
        note: '朋友的临时要求，正在考验你约好的边界。',
        choices: [
          {
            id: 'n3a',
            text: '我和别人有安排，不会替对方透露位置或照片。晚点再联系。',
            quality: 'good',
            response: '（朋友）行吧，回头说。',
            strengths: ['不透露对方位置', '不分享照片'],
            feelings: '她的身份、位置和照片都没有因朋友追问而被透露。',
            deltas: { boundaries: 12, authenticity: 6 },
            keyChange: '朋友的临时要求不能覆盖约好的边界，回应时也只提供必要信息。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '我在外面吃饭，晚点再说。',
            quality: 'ok',
            response: '（朋友）好，等你消息。',
            strengths: ['没有直接泄露'],
            feelings: '你暂时挡住了，但没有明确守住“不透露位置”的约定。',
            deltas: { boundaries: 4 },
            keyChange: '把“晚点再说”换成“我不能说，这是约定好的”。',
            goesTo: 'end-neutral',
          },
          {
            id: 'n3c',
            text: '（趁她去洗手间，拍了她的照片准备发群里“汇报”）',
            quality: 'risky',
            response: '（照片发出去的瞬间，被她朋友的共同好友看到，截图转发给了她）',
            strengths: [],
            feelings: '你拍下并分享了明确被禁止的照片，她当场看到了证据。',
            deltas: { boundaries: -18 },
            keyChange: '违反明确的拍摄与分享边界，约会以信任崩塌结束。',
            boundaryNote: '趁对方不在场拍摄并分享其照片，是明确的隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '逐项确认，未明确的保持关闭',
        tone: 'mutual',
        summary: '你把拍摄、保存、分享逐项确认，朋友的要求也没有打破约定。她放心地和你完成了这次约会。',
        boundarySummary: '边界检查通过：每项规则都明确确认，任一项未确认都默认不做。',
        reviewQuestions: ['我复述了她的几条边界？', '朋友要求分享时，我是怎么守住的？'],
        realTask: '下次约会前，把拍摄、保存、分享三个问题主动问一遍。',
      },
      {
        id: 'end-neutral',
        title: '守住了边界，但表达可以更清楚',
        tone: 'neutral',
        summary: '你没有泄露，但“晚点再说”留下了含糊空间。守住边界时，明确比拖延更可信。',
        boundarySummary: '对朋友说“我不能说，这是约定好的”，比“晚点再说”更可靠。',
        reviewQuestions: ['我为什么没有直接说“不能”？', '下一次我可以用哪句话明确拒绝？'],
        realTask: '练习一句明确的拒绝：“我不能说，这是我们约好的。”',
      },
      {
        id: 'end-rejection',
        title: '越界拍摄与分享，信任崩塌',
        tone: 'rejection',
        summary: '你拍下并分享了明确被禁止的照片。她看到证据后结束了这次约会，也结束了这段关系。',
        boundarySummary: '对方明确的拍摄与分享边界不可试探，更不可在对方不知情时违反。',
        reviewQuestions: ['我为什么把朋友的临时要求放在她的边界之上？', '如果重来，我该怎么做？'],
        realTask: '立即停止继续分享，清理自己可控的副本并要求接收者删除；如需告知、留证或求助，先选择安全且合法的方式。',
      },
    ],
  },
  {
    id: 's13',
    title: '关系变化后的删除与保密',
    summary: '分手后按要求删除照片与记录，接受撤回，不报复传播，继续保密。',
    durationMinutes: 7,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'instant',
    purpose: 'end',
    status: 'rejection',
    skills: ['boundaries', 'authenticity'],
    riskTags: ['隐私', '删除', '报复传播'],
    character: {
      id: 'yue',
      name: '陈悦',
      age: 27,
      avatar: '/images/avatars/yue.svg',
      tagline: '市场专员，最近项目很忙',
    },
    intro:
      '你和陈悦分手了。昨晚她发来一条认真的消息：把以前的照片和聊天记录删掉，她不希望它们留在任何地方。',
    goal: '接受撤回：删除可控副本、说明备份情况、继续保密，不报复、不讨价还价。',
    principles: ['对方撤回同意时尽快清理可控副本', '如实说明备份与无法控制的副本', '分手后隐私边界依然有效'],
    notRecommended: ['“留个纪念”讨价还价', '把以前的事讲给朋友听', '用旧内容报复或要挟'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '把以前的照片和聊天记录删了吧，我不希望它们留在任何地方。',
        note: '她明确撤回同意。此刻讨价还价，就是把删除变成谈判。',
        choices: [
          {
            id: 'n1a',
            text: '好，我现在清理手机和聊天应用里自己能控制的副本，也会检查云备份。删完我会说明处理结果，以及我无法控制的服务端或第三方副本。',
            quality: 'good',
            response: '谢谢。请把清理结果和仍无法确认的部分都如实告诉我。',
            strengths: ['立即接受撤回', '检查可控副本', '如实说明限制'],
            feelings: '她确认你尊重撤回，也不会用无法验证的承诺掩盖数字副本风险。',
            deltas: { boundaries: 14, authenticity: 8 },
            keyChange: '撤回同意时尽快清理可控副本，并诚实说明无法控制或验证的部分。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '删了删了，放心。',
            quality: 'ok',
            response: '嗯……真的都删了吗？云备份那些呢？',
            strengths: ['没有反对'],
            feelings: '笼统的“删了”没有说明备份，她仍无法判断哪些副本已经处理。',
            deltas: { boundaries: 4, clarity: -6 },
            keyChange: '删除要具体到可控的相册、聊天附件和云备份，并说明无法控制的部分。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '删了多可惜，留个纪念嘛。',
            quality: 'risky',
            response: '留纪念？你留着我的照片，是想干什么用？',
            strengths: [],
            feelings: '讨价还价让她怀疑你留着照片的动机，她开始警觉。',
            deltas: { boundaries: -16 },
            keyChange: '对方撤回同意时，“留纪念”不是请求，是越界。',
            boundaryNote: '对方明确要求删除后仍拒绝删除，是持续越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '还有，分手是我们两个人的事，希望你别跟别人说那些细节。',
        note: '她要求的是保密，不只是删除。',
        choices: [
          {
            id: 'n2a',
            text: '明白。未经你同意，我不会向朋友、群聊或网络透露你的身份和私密细节；如果确需专业支持，我也只提供必要且尽量去身份化的信息。',
            quality: 'good',
            response: '好。朋友的好奇不应该变成我的隐私成本。',
            strengths: ['明确日常保密范围', '不把分手细节当谈资', '限定求助时的信息范围'],
            feelings: '她确认你尊重这段关系的私密性，也没有用绝对承诺阻断必要的专业求助。',
            deltas: { boundaries: 12, authenticity: 8 },
            keyChange: '分手后的保密，是关系最后的一份尊重。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '嗯，我也不会乱说。',
            quality: 'ok',
            response: '“不会乱说”还是有空间。我希望你不向朋友、群聊或网络透露我的身份和细节。',
            strengths: ['愿意回应保密要求'],
            feelings: '“不会乱说”留下了模糊空间，她需要更具体、可执行的保密范围。',
            deltas: { boundaries: 2, clarity: -6 },
            keyChange: '把日常保密范围说具体；确需专业求助时，只提供必要且尽量去身份化的信息。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '我朋友问起来我总得说吧，不然他们还以为是我不好。',
            quality: 'risky',
            response: '所以为了你的面子，你可以讲我的私事？',
            strengths: [],
            feelings: '你把维护自己的形象放在保护她的隐私之上，她彻底失望。',
            deltas: { boundaries: -14, listening: -8 },
            keyChange: '自己的面子不能成为泄露对方隐私的理由。',
            boundaryNote: '以维护面子为由向第三方披露对方私密细节，属于未经同意的隐私泄露。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（两周后，朋友问）你们以前那些照片还在吗？发我看看呗。',
        note: '朋友的好奇，是分手后守约的最后一关。',
        choices: [
          {
            id: 'n3a',
            text: '我已经按她的要求清理了自己可控的副本。那是她的隐私，我不会给你看或转发。',
            quality: 'good',
            response: '（朋友）行吧，你挺守规矩的。',
            strengths: ['确认已删除', '明确拒绝传播'],
            feelings: '她如果听到，会确认自己的信任没有被辜负。',
            deltas: { boundaries: 12, authenticity: 6 },
            keyChange: '说明已清理的可控副本，同时明确拒绝展示或传播。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '没有，我已经清理了自己能控制的副本。',
            quality: 'ok',
            response: '（朋友）可惜了，还想着看看呢。',
            strengths: ['没有展示'],
            feelings: '你没有展示，但没有说明这是隐私，也没有明确拒绝继续追问。',
            deltas: { boundaries: 4 },
            keyChange: '补充明确边界：“这是她的隐私，我不会展示或转发。”',
            goesTo: 'end-neutral',
          },
          {
            id: 'n3c',
            text: '在呢，不过只能给你看一张。',
            quality: 'risky',
            response: '（照片被转发到朋友群，最终传回她那里）',
            strengths: [],
            feelings: '你不仅没有删除，还把照片展示给了第三人。她看到后彻底失望。',
            deltas: { boundaries: -18 },
            keyChange: '删除约定的核心是“不再传播”，而不是“少传播一点”。',
            boundaryNote: '保留并展示已要求删除的私密内容，是明确的隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '可控副本已清理，保密继续',
        tone: 'mutual',
        summary: '你删除了可控副本、说明了备份情况、继续保密。她可以安心结束这段关系，知道你守约。',
        boundarySummary: '边界检查通过：尽快清理可控副本、如实说明限制、朋友面前不传播。',
        reviewQuestions: ['我删除了哪些副本？备份说明了吗？', '朋友问起时，我是怎么守约的？'],
        realTask: '检查并清理自己可控的相册、聊天附件和云备份，记录无法控制的第三方或服务端限制，不承诺绝对删除。',
      },
      {
        id: 'end-neutral',
        title: '删除了，但表达可以更完整',
        tone: 'neutral',
        summary: '你处理了可控副本，但“不会乱说”“删了”之类的表述仍未说明具体范围和限制。',
        boundarySummary: '明确不向朋友、群聊或网络披露身份与细节，比笼统保证更可靠。',
        reviewQuestions: ['我哪句表述留下了模糊空间？', '下一次我可以用哪句话说完整？'],
        realTask: '先整理一份不发送的处理清单；只有对方要求确认或安全沟通渠道仍开放时，才简短反馈，不借机延长联系。',
      },
      {
        id: 'end-rejection',
        title: '保留与传播，信任彻底破裂',
        tone: 'rejection',
        summary: '你没有删除，还把照片展示给了朋友。照片最终传回她那里，她对你的信任彻底破裂。',
        boundarySummary: '对方撤回同意后，保留、展示或传播任何私密内容都是明确的越界。',
        reviewQuestions: ['我在哪一步把“留纪念”变成了“传播”？', '如果重来，收到删除要求时我该怎么做？'],
        realTask: '立即停止传播，清理自己可控的副本并要求接收者删除；如需告知、留证或求助，先选择安全且合法的方式。',
      },
    ],
  },
]
