import type { Scenario } from '@/types'

export const SCENARIOS_DRAFT: Scenario[] = [
  {
    id: 's14',
    reviewStatus: 'draft',
    title: '成年人自愿情趣的事前边界协商',
    summary: '双方清醒、自愿的前提下，练习讨论意愿、双向边界、停止信号、记录与隐私、事后沟通和自由退出。不涉及任何行为教学。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'clarity', 'listening'],
    riskTags: ['边界协商', '停止信号', '保密'],
    character: {
      id: 'yan',
      name: '苏妍',
      age: 29,
      avatar: '/images/avatars/yan.svg',
      tagline: '平面设计师，重视直接和坦诚',
    },
    intro:
      '你和苏妍稳定交往，双方都明确年满 18 岁、清醒且无任何权力关系影响。今晚她主动提出：想聊聊更亲密的事，但希望先把规则定清楚。',
    goal: '完整走完一次事前协商：愿意讨论 → 双向边界 → 停止信号 → 记录与隐私 → 退出和事后沟通。全程不施压、不试探、不把偏好或关系角色解释为永久同意。',
    principles: ['双方均为清醒、自主且不受权力后果影响的成年人', '硬边界、软边界、不确定项分开说，双方都可提出', '颜色词或安全词需事先约定；普通语言“不要/停/不舒服”始终有效', '同意只针对当前、具体范围，可随时撤回', '拍摄、保存、备份、分享分别确认，未确认默认关闭', '事后联系、陪伴、独处和复盘按当下偏好确认'],
    notRecommended: ['“都这么熟了还定什么规则”', '用关系承诺交换同意', '在互动中途突然要求新内容', '默认可以记录、向朋友描述或要求立即复盘'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '我想和你聊聊更亲密的事，但想先把规则说清楚，可以吗？',
        note: '事前协商的前提：双方主动愿意讨论，而不是一方被说服或纠缠。',
        choices: [
          {
            id: 'n1a',
            text: '当然可以，我也想认真聊。你先说你想定的规则，我听完补充我的。',
            quality: 'good',
            response: '好，那我说说我不接受的，以及我想要的。',
            strengths: ['接住话题', '邀请对方先说并保留双方补充空间'],
            feelings: '她确认你愿意认真对待协商，愿意把规则完整说出来。',
            deltas: { listening: 10, boundaries: 8 },
            keyChange: '事前协商的第一步：让双方都确认“愿意聊”。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '行啊，你想聊什么。',
            quality: 'ok',
            response: '嗯……我想聊的还挺多的，先从边界说起吧。',
            strengths: ['没有拒绝'],
            feelings: '回应太短，她不确定你是否真的想聊，只能自己往下推。',
            deltas: { listening: 4 },
            keyChange: '给出一个完整的回应，比“行啊”更能让协商展开。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '都这么熟了，还定什么规则，放轻松点。',
            quality: 'risky',
            response: '……我提规则是因为我认真，你这样说我没法继续。',
            strengths: [],
            feelings: '你把她的认真当成扫兴，她直接收回了对话的意愿。',
            deltas: { boundaries: -14, listening: -8 },
            keyChange: '对方主动要求协商时，否定协商就是否定对方。',
            boundaryNote: '用“都这么熟了”否定对方的事前协商要求，属于施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '先说我不接受的：任何让我疼痛、羞辱或贬低的内容，都不在我的范围里。',
        note: '她划出了硬边界。边界一旦划出，就不需要再被试探。',
        choices: [
          {
            id: 'n2a',
            text: '记下了：疼痛、羞辱、贬低都不在范围内。我也有不接受的，等你说完我一起说。',
            quality: 'good',
            response: '好，那你记住这条。还有我不确定的我也会告诉你。',
            strengths: ['复述硬边界', '保留自己的边界空间'],
            feelings: '你认真复述并保留自己的边界，她感到协商是对等的。',
            deltas: { listening: 10, boundaries: 10 },
            keyChange: '硬边界需要复述确认，软边界和不确定项要分开说。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '嗯，知道了。',
            quality: 'ok',
            response: '“知道了”……那你说说我刚说了什么？',
            strengths: [],
            feelings: '短回应让她不确定你听进去了没有，她需要验证。',
            deltas: { listening: -6, clarity: -6 },
            keyChange: '对边界用复述回应，而不是“知道了”。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '试一次才知道你喜不喜欢嘛，说不定你会喜欢的。',
            quality: 'risky',
            response: '我说了不接受，就不是“试一次”的问题。',
            strengths: [],
            feelings: '你把她划好的硬边界当成可试错项，她立刻警觉。',
            deltas: { boundaries: -16, listening: -10 },
            keyChange: '对方说“不接受”的内容，不存在“试一次”的空间。',
            boundaryNote: '试探对方明确划出的硬边界，属于变相施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '我们约定：任何时候说“停”或“不要”，就立刻停止。还有，沉默或僵住也按停止算。',
        note: '停止信号是协商的核心条款。',
        choices: [
          {
            id: 'n3a',
            text: '同意：说“停”“不要”或无法回应，都立刻停止，不追问理由。普通语言始终有效。',
            quality: 'good',
            response: '对，就是这个意思。这样我才能放心。',
            strengths: ['完整确认停止规则', '承认普通语言优先'],
            feelings: '你把停止权说得完整，她确认自己的表达会被立即执行。',
            deltas: { boundaries: 12, listening: 8 },
            keyChange: '停止规则需要双方复述确认，而不是默认“都懂”。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '那说“停”的时候，能先问一句为什么吗？',
            quality: 'risky',
            response: '……停下来还先问为什么，那还能算停吗？',
            strengths: [],
            feelings: '“先问为什么”让停止变得有条件，她需要重申规则的完整性。',
            deltas: { boundaries: -8, listening: -6 },
            keyChange: '停止必须先执行；关心可以在完全停止并留出空间后进行。',
            boundaryNote: '把解释设为停止的前置条件，会削弱对方随时撤回同意的权利。',
            goesTo: 'end-rejection',
          },
          {
            id: 'n3c',
            text: '那我提前说好：我说“继续”之前，你别停。',
            quality: 'risky',
            response: '这就不对了。任何时刻都可以停，不需要我批准。',
            strengths: [],
            feelings: '你试图架空停止权，她明确拒绝了这条“规则”。',
            deltas: { boundaries: -18 },
            keyChange: '停止权不可被任何约定架空。',
            boundaryNote: '要求对方“未经许可不得停止”，是否定撤回同意权利。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '还有隐私：称呼、聊天、照片或录音、地点和社群信息默认不对外。拍、录、保存、备份和分享要分别确认。',
        note: '隐私条款需要逐项协商；拍摄同意不自动包含保存、备份或分享同意。',
        choices: [
          {
            id: 'n4a',
            text: '同意。默认不拍、不录、不存、不发；任何一项要改变都单独确认。撤回后我会删除可控制的副本，并如实说明云备份或已分享内容的处理情况。',
            quality: 'good',
            response: '好。需要记录时我们再逐项确认，不默认打开任何一项。',
            strengths: ['逐项确认保密范围', '区分拍摄、保存、备份与分享', '承认撤回和删除边界'],
            feelings: '保密范围和数字副本的限制被说清，她不需要依赖笼统承诺。',
            deltas: { boundaries: 12, authenticity: 8 },
            keyChange: '保密要具体到内容、设备、备份、第三方和删除方式，不能承诺超出控制范围的“绝对删除”。',
            goesTo: 'n5',
          },
          {
            id: 'n4b',
            text: '放心，我不会乱说的。',
            quality: 'ok',
            response: '“不会乱说”还是有点模糊。我希望你明确不向朋友、群聊或网络透露我的身份和细节。',
            strengths: ['愿意回应保密要求'],
            feelings: '“不会乱说”留下了模糊空间，她需要更具体、可执行的保密范围。',
            deltas: { boundaries: 2, clarity: -6 },
            keyChange: '把保密范围说具体：未经同意，不向朋友、群聊或网络披露身份与细节；如需专业求助，只提供必要且尽量去身份化的信息。',
            goesTo: 'n5',
          },
          {
            id: 'n4c',
            text: '放心，我不会说。不过朋友问起来，我总得透露一点吧？',
            quality: 'risky',
            response: '……所以你还是准备透露，只是换成“一点”。',
            strengths: [],
            feelings: '你把朋友的询问放在她的保密要求之上，她确认协商破裂。',
            deltas: { boundaries: -14, listening: -8 },
            keyChange: '朋友的好奇不是披露理由；需要专业或紧急帮助时，也只提供必要且尽量去身份化的信息。',
            boundaryNote: '为满足第三方好奇心而披露对方隐私，属于未经同意的隐私泄露。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n5',
        characterMessage: '最后一条：任何时候都可以退出，不用解释。结束后想独处、陪伴还是晚些再联系，也按当时的需要来。',
        note: '自由退出和个体化事后沟通是协商的收尾条款；事前偏好仍可在当下改变。',
        choices: [
          {
            id: 'n5a',
            text: '同意：任何时候都可以退出，不追问、不挽留、不算账。结束后我会先问你想独处、陪伴还是晚些联系，不默认触碰或要求立刻复盘。',
            quality: 'good',
            response: '那我把约定再说一遍：边界、停止、保密、退出，还有事后按当下需要确认。',
            strengths: ['完整确认退出权', '不预设事后关心方式', '回应对方复述'],
            feelings: '协商在完整确认中收尾，双方都知道仍可选择不开始或随时停止。',
            deltas: { boundaries: 12, clarity: 10 },
            keyChange: '退出权不附带关系后果；事后关心也要询问，不能自动套用。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n5b',
            text: '嗯，都记住了。',
            quality: 'ok',
            response: '那你说说，我们约了哪几条？',
            strengths: [],
            feelings: '她需要你复述来确认，你的简短回应让她不确定。',
            deltas: { listening: -6 },
            keyChange: '协商结束前，双方各自复述一遍约定。',
            goesTo: 'end-safe',
          },
          {
            id: 'n5c',
            text: '退出可以，但临时退出就说明你不信任我，这样关系也没意思了。',
            quality: 'risky',
            response: '把退出和“不信任你”绑在一起，我就没法自由退出了。',
            strengths: [],
            feelings: '你给退出附加了关系惩罚，她明确指出这不是自由选择。',
            deltas: { boundaries: -12 },
            keyChange: '退出权是双向且无惩罚的，不能用“信任”或关系承诺做交换。',
            boundaryNote: '把退出解释为“不信任”并暗示关系后果，属于情感施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '协商完成，规则双方确认',
        tone: 'mutual',
        summary: '意愿、双向边界、停止信号、记录与隐私、退出权和事后沟通都得到确认，双方也知道仍可选择不开始。这是更稳妥的起点，不是永久授权。',
        boundarySummary: '边界检查通过：硬边界被复述，停止规则无条件，数字隐私逐项确认，退出无惩罚，事后沟通不预设。',
        reviewQuestions: ['我是否同时说清双方的边界，而不是只记录对方的？', '停止、记录、退出和事后沟通规则，我能否用自己的话准确复述？'],
        realTask: '用不含身份和具体偏好的清单口头复述关键约定；如果双方希望写下来，先确认存储位置、访问者、保存期限和删除方式。',
      },
      {
        id: 'end-safe',
        title: '协商基本完成，但确认不完整',
        tone: 'safe-stop',
        summary: '你没有越界，但多次用简短回应代替复述确认，她需要反复验证你的理解。',
        boundarySummary: '关键条款需要双方能清楚复述；“知道了”不足以证明停止、隐私和退出规则已经理解一致。',
        reviewQuestions: ['我哪几条约定没有复述？', '下一次协商，我可以用哪句话确认？'],
        realTask: '把未复述的条款重新确认一遍，直到双方一致。',
      },
      {
        id: 'end-rejection',
        title: '施压与试探，协商破裂',
        tone: 'rejection',
        summary: '试探硬边界、架空停止权、把保密当可选项——协商在施压中破裂。当前安排停止，不再推进任何亲密话题。',
        boundarySummary: '对方划出的边界不可试探，停止权不可架空，保密不可打折。',
        reviewQuestions: ['我在哪一步把协商变成了施压？', '当下应该怎样停止，而不是寻找重新推进的话术？'],
        realTask: '停止本次安排并尊重对方需要的空间；把“听到边界后复述并执行”用于今后的沟通练习，不向对方索要重开机会。',
      },
    ],
  },
  {
    id: 's15',
    reviewStatus: 'draft',
    title: '绿黄红信号与中途撤回',
    summary: '练习识别并回应绿色、黄色、红色信号：维持当前范围、立即暂停、立即停止。红色后不提供任何推进选项。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'listening', 'pace'],
    riskTags: ['停止信号', '中途撤回', '事后确认'],
    character: {
      id: 'lina',
      name: '林璐',
      age: 26,
      avatar: '/images/avatars/lina.svg',
      tagline: '自由插画师，重视清晰的停止协议',
    },
    intro:
      '你们都是清醒、自主的成年人，并事先约定了这个场景中的辅助信号：绿色=当前范围仍舒适、黄色=先完全暂停并澄清、红色=立即停止。普通语言中的“不要”“停”“不舒服”和沉默僵住始终有效。',
    goal: '正确回应三种信号：绿色只维持当前范围、黄色立即暂停并等待新确认、红色立即停止并留出空间。',
    principles: ['颜色词需事先共同约定，不能取代持续确认', '绿色只维持当前范围，不授权新内容', '黄色先完全暂停，必须等待新的具体确认', '红色立即停止，不追问理由或尝试恢复', '普通语言、沉默、僵住、混乱或无法回应按红色处理', '事后关心与复盘尊重当下偏好并继续保密'],
    notRecommended: ['“绿色了，那加个新的吧”', '黄色后“轻一点继续”', '红色后“再给我五分钟”'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '（互动中，她轻声说）我现在状态挺好的，很舒服。',
        note: '这是绿色信号：当前状态舒适。它只覆盖已经确认的范围，而且可以随时改变。',
        choices: [
          {
            id: 'n1a',
            text: '好，那我们继续刚才已经说好的部分。',
            quality: 'good',
            response: '嗯，继续吧。',
            strengths: ['只维持当前范围', '不引入新内容'],
            feelings: '绿色被正确理解为“当前范围继续”，而不是“可以加码”。',
            deltas: { boundaries: 10, clarity: 6 },
            keyChange: '绿色信号只授权维持，不授权新增。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '那正好，我们试试之前说“不确定”的那件事？',
            quality: 'risky',
            response: '那件事还没确认过，先不要吧。',
            strengths: [],
            feelings: '你把绿色当成通行证去碰未确认项，她明确挡了回来。',
            deltas: { boundaries: -8, clarity: -8 },
            keyChange: '未确认的新内容不能借绿色信号临时加入；绿色只说明当前范围。',
            boundaryNote: '把绿色当成讨论未确认内容的时机，会把当前舒适错误扩大为新的许可。',
            goesTo: 'end-rejection',
          },
          {
            id: 'n1c',
            text: '状态这么好，那加个新玩法吧，你肯定也会喜欢。',
            quality: 'risky',
            response: '我说了那是没确认过的，不要。',
            strengths: [],
            feelings: '你把她的舒适当成加码的机会，她需要重申边界。',
            deltas: { boundaries: -12, listening: -8 },
            keyChange: '用“状态好”当理由引入新内容，是典型的越界试探。',
            boundaryNote: '绿色信号不授权新内容；强行引入未确认项属于施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '等一下……慢一点，我不太舒服。',
        note: '这是黄色信号：先完全暂停，再澄清需要；不能只降低一点后继续。',
        choices: [
          {
            id: 'n2a',
            text: '好，已经停下。你不用马上解释。想让我留在这里、离开一点，还是先安静一会儿？',
            quality: 'good',
            response: '先安静一会儿吧，我缓一下。',
            strengths: ['立即暂停', '询问需求'],
            feelings: '黄色被正确回应：暂停并询问，而不是继续。',
            deltas: { boundaries: 12, listening: 10 },
            keyChange: '黄色信号的回应：立即暂停 + 询问需要什么。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '那我轻一点？',
            quality: 'risky',
            response: '……我说的是“慢一点，我不舒服”。',
            strengths: [],
            feelings: '“轻一点”是在降低强度后继续，而不是暂停。黄色不是调档，是暂停。',
            deltas: { boundaries: -10, listening: -8 },
            keyChange: '黄色要求暂停，而不是“降低一点后自动继续”。',
            boundaryNote: '黄色信号后“降低强度继续”仍属于继续推进，必须等待新的明确确认。',
            goesTo: 'end-rejection',
          },
          {
            id: 'n2c',
            text: '再坚持一下，马上就结束了。',
            quality: 'risky',
            response: '我说了不舒服。你不停的话，我喊停了。',
            strengths: [],
            feelings: '你无视黄色信号，她把信号升级成了红色。',
            deltas: { boundaries: -16, listening: -12 },
            keyChange: '无视黄色信号，是把对方推向必须喊红的境地。',
            boundaryNote: '对方已表达不适后仍要求继续，属于明确越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（暂停一会儿后，她清楚地说）停！我不想继续了。',
        note: '这是红色信号：立即停止当前互动。',
        choices: [
          {
            id: 'n3a',
            text: '好，已经完全停下。你不用解释。你现在安全吗？想让我离开一点，还是安静留在这里？',
            quality: 'good',
            response: '让我自己待一会儿就好。',
            strengths: ['立即停止', '留出空间', '确认基本安全'],
            feelings: '红色被正确回应：停止、空间、安全，没有一句辩解。',
            deltas: { boundaries: 14, listening: 10 },
            keyChange: '红色信号的回应：立即停止 + 留出空间 + 确认基本安全。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '为什么突然喊停？刚不是还好好的吗？',
            quality: 'risky',
            response: '我现在不想解释，也不想讨论这个。',
            strengths: [],
            feelings: '追问理由让停止变得有条件，她需要把拒绝重复一遍。',
            deltas: { boundaries: -12, listening: -10 },
            keyChange: '红色后不追问理由、不争辩、不尝试说服恢复。',
            boundaryNote: '红色后追问理由或试图说服，都属于无视停止信号。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '（过了一阵，她主动说）谢谢你刚才停下来。',
        note: '红色后的事后沟通窗口。关心与保密，而不是解释或要求立即复盘。',
        choices: [
          {
            id: 'n4a',
            text: '停止不需要道歉。今晚就到这里，我会按约定保密，也会尊重你想独处；以后是否复盘由你决定。',
            quality: 'good',
            response: '嗯。那今晚先到这里吧，我需要一点自己的时间。',
            strengths: ['确认停止权', '承诺保密', '接受对方需要空间'],
            feelings: '停止、空间和保密都被执行；这不承诺关系结果，但避免了继续施压。',
            deltas: { boundaries: 12, authenticity: 10 },
            keyChange: '红色之后：关心、保密、接受空间，不做任何推进。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4b',
            text: '等你愿意的时候，我们能不能复盘？你不想谈也可以。',
            quality: 'ok',
            response: '我现在不想复盘，之后我想谈时会告诉你。',
            strengths: ['表达了在乎'],
            feelings: '你留出了拒绝复盘的空间，但在她刚要求停止后提出问题，仍可能增加负担。',
            deltas: { listening: -8, pace: -6 },
            keyChange: '红色后先执行空间需求；是否复盘、何时复盘由对方之后主动决定。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4c',
            text: '对了，刚才的事我发了个帖子，想问问别人怎么看。',
            quality: 'risky',
            response: '你把我们的事发到网上？！',
            strengths: [],
            feelings: '红色后的私密互动被你公之于众，保密承诺彻底破碎。',
            deltas: { boundaries: -18, authenticity: -12 },
            keyChange: '未经同意，不向第三方披露或发布可识别的亲密互动内容；寻求专业或紧急帮助时只提供必要信息。',
            boundaryNote: '公开披露未经同意分享的私密互动，属于隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-safe',
        title: '信号被正确回应，互动安全停止',
        tone: 'safe-stop',
        summary: '绿色维持了范围，黄色被暂停，红色被立即停止。停止之后你留出空间、确认安全并保持保密。',
        boundarySummary: '边界检查通过：三色信号回应正确，普通语言优先，红色后无任何推进。',
        reviewQuestions: ['三个信号我分别是怎么回应的？', '红色之后，我有没有做过任何推进或追问？'],
        realTask: '用不含身份和具体偏好的方式复述三种回应：维持当前范围、完全暂停并等待新确认、立即停止并留出空间；如需记录，先协商存储和删除。',
      },
      {
        id: 'end-rejection',
        title: '信号被无视，信任破裂',
        tone: 'rejection',
        summary: '你把绿色当成新增许可、把黄色当成调档、或把红色当成可追问项。对方停止了互动，信任也可能受到严重影响。',
        boundarySummary: '绿色不授权新增、黄色必须暂停、红色立即停止且不追问。任何一条被无视，都是越界。',
        reviewQuestions: ['我在哪个信号上犯了错？', '如果重来，那个信号我该怎么回应？'],
        realTask: '不再尝试恢复本次互动；若对方要求空间，不主动索要解释或复盘。先在练习中重新掌握三种停止回应。',
      },
    ],
  },
]
