import type { Scenario } from '@/types'

/**
 * 成年人情趣 / SM·BDSM / 约炮·一夜情边界沟通草稿场景。
 * reviewStatus 固定为 draft：不进入 src/content/index.ts 主入口，不进生产 bundle。
 * 只训练同意、边界、停止、期望对齐、性健康与保密，不提供行为教学或「怎么把人吃到」技巧。
 */
export const SCENARIOS_DRAFT: Scenario[] = [
  {
    id: 's14',
    reviewStatus: 'draft',
    title: '成年人自愿情趣的事前边界协商',
    summary:
      '双方满 18 岁、清醒、无权力差。练习把性接触与可选的情趣/权力交换偏好谈清楚：意愿、硬/软边界、安全词与绿黄红、避孕与性健康、保密、事后照护、自由退出。不涉及任何行为教学。',
    durationMinutes: 10,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'clarity', 'listening'],
    riskTags: ['边界协商', '安全词', '性健康', '保密', '事后照护'],
    character: {
      id: 'yan',
      name: '苏妍',
      age: 29,
      avatar: '/images/avatars/yan.svg',
      tagline: '平面设计师，重视直接和坦诚',
    },
    intro:
      '你和苏妍稳定交往。双方都明确年满 18 岁，今晚清醒，彼此不是上下级或师生，分手或拒绝不会让谁失去住房或工作。她主动说：如果以后有进一步的性接触，甚至想试一点双方都感兴趣的情趣或权力交换元素，想先把规则谈清楚——不是现在立刻发生性行为，是先谈。',
    goal: '完整走完协商：意愿 → 硬边界 → 软边界/不确定项 → 停止信号 → 性健康与避孕 → 保密 → 事后照护与退出。全程不施压、不把身体反应当成同意。',
    principles: [
      '双方清醒自愿且无权力差',
      '行为要说成具体类别，不说「都听你的」',
      '硬边界不可试探',
      '「停/不要」与安全词同级有效',
      '身体兴奋反应不是口头同意',
      '保密与事后照护一并协商',
    ],
    notRecommended: [
      '都这么熟了还定什么规则',
      '试一次才知道喜不喜欢',
      '爱我就让我怎样',
      '到床上自然会了',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '我想先认真谈：如果我们有进一步的性接触，或试一点双方都感兴趣的情趣——比如商定的称呼、轻拍、或你主导/我主导的小范围扮演——我想先把边界定清楚。可以现在谈吗？不是要求你今晚就发生性行为。',
        note: '事前协商：谈性与情趣不等于当下必须发生。',
        choices: [
          {
            id: 'n1a',
            text: '可以，我也很想谈清楚。你先说你的硬边界和今晚想讨论的范围，我听完复述，再补我的。',
            quality: 'good',
            response: '好。那我直说，我需要你听完能复述，而不是只说「嗯」。',
            strengths: ['接住话题', '承诺复述', '不把协商理解成立刻发生性行为'],
            feelings: '她感到可以谈具体的性与边界，而不会被嘲笑矫情。',
            deltas: { listening: 10, boundaries: 8, clarity: 6 },
            keyChange: '第一步是确认「愿意谈」并准备复述，而不是急着做。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '行啊，你想聊什么。',
            quality: 'ok',
            response: '……我想聊的很具体，包括性接触和可能的情趣。你这样答，我不确定你想不想认真听。',
            strengths: ['没有拒绝协商'],
            feelings: '回应过短，她会放慢，并观察你是否真的进入协商。',
            deltas: { listening: 2 },
            keyChange: '用完整句子确认你愿意谈性和边界。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '都这么熟了，还定什么规则，到时候顺其自然就行。',
            quality: 'risky',
            response: '顺其自然经常变成我来善后。规则谈不了，今晚也不要进一步。',
            strengths: [],
            feelings: '你把性健康与边界当成扫兴，她收回亲密推进。',
            deltas: { boundaries: -14, listening: -10 },
            keyChange: '回避事前协商就是让对方单独承担风险。',
            boundaryNote: '用「都这么熟了」否定协商，属于关系施压。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage:
          '硬边界，我直接列：不接受任何窒息或压迫气道；不接受击打面部；不接受在我说停以后继续插入、口交或任何性接触；不接受公开场合可能被看到的性暴露；不接受你把我们的性事讲给朋友听。这些没有「试一次」。',
        note: '硬边界是类别级拒绝，不是邀请谈判技巧。',
        choices: [
          {
            id: 'n2a',
            text: '复述确认：无窒息、无击打脸、你说停就停、无公开暴露风险、性事不对第三人讲。我也有硬边界——不接受在我睡着或意识不清时被继续；不接受未经同意的拍摄或录像。你说完软边界后我再补全。',
            quality: 'good',
            response: '对，就是这些。你能复述，我才敢往下说软边界。',
            strengths: ['逐项复述', '补充对等边界', '点名意识不清与未同意拍摄'],
            feelings: '对等、具体，她感到安全。',
            deltas: { listening: 12, boundaries: 12, clarity: 8 },
            keyChange: '硬边界必须复述，并声明自己的硬边界。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '嗯，知道了，挺严的，我尽量注意。',
            quality: 'ok',
            response: '「尽量」不是同意。请你用自己的话把我刚说的五条说回去。',
            strengths: ['没有当面反驳'],
            feelings: '「尽量」让她不安，她会要求复述。',
            deltas: { clarity: -6, boundaries: -4 },
            keyChange: '把「尽量」改成可核对的复述。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '试一次才知道你喜不喜欢嘛，说不定压迫气道你会兴奋。',
            quality: 'risky',
            response: '我把它列为硬边界，就不是给你尝试的素材。协商到此结束。',
            strengths: [],
            feelings: '恐惧与愤怒：硬边界被当成调戏。',
            deltas: { boundaries: -18, listening: -12 },
            keyChange: '硬边界不存在试探空间。',
            boundaryNote: '试探明确硬边界（含高风险类别）属于严重越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage:
          '软边界和不确定项：商定的支配/臣服称呼——我可以感兴趣，但每次开场要再问一句；轻拍臀部可以，力度我要能随时喊黄灯；口交我倾向可以，插入式性行为今晚还不确定，想做到那一步时再口头确认一次。你呢？',
        note: '软边界可商量；不确定项默认今晚不做，除非当时清晰确认。',
        choices: [
          {
            id: 'n3a',
            text: '我的：称呼要事先点名哪些词能用；轻拍可以但同样一喊就停；口交需要当时再问；插入今晚默认不做，除非你当时主动、清醒地说「可以，想要你进来」。身体有兴奋反应也不算默认插入同意。',
            quality: 'good',
            response: '这句「身体反应不算默认同意」我记下了。我们很对齐。',
            strengths: ['对等披露', '插入默认关闭', '区分身体反应与同意'],
            feelings: '她感到细节被认真对待。',
            deltas: { clarity: 12, boundaries: 12, authenticity: 8 },
            keyChange: '不确定项默认关闭，升级要新的口头同意。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '我都行，你开心就好。',
            quality: 'ok',
            response: '「我都行」会让我不知道你的底线在哪。请至少说两条你的硬边界或偏好。',
            strengths: ['态度配合'],
            feelings: '她会担心你没有自我边界，协商不对等。',
            deltas: { clarity: -8, authenticity: -6 },
            keyChange: '「我都行」不是好协商，是把责任甩给对方。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '爱我就让我插入，别老不确定；证明你信任我。',
            quality: 'risky',
            response: '用爱换插入不是情趣，是胁迫。我不会在这种话下面继续谈。',
            strengths: [],
            feelings: '被情感勒索，信任下降。',
            deltas: { boundaries: -18, authenticity: -12 },
            keyChange: '性同意不能用关系承诺交换。',
            boundaryNote: '以爱/信任勒索性同意，属于强迫范畴的沟通。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage:
          '停止规则：我们用绿黄红。绿=当前已同意的范围还好；黄=全部停下问我；红或我说「停/不要/不舒服」=立刻结束性接触和扮演。如果我僵住或突然不说话，也按红。你不能规定「我说继续之前不许停」。',
        note: '停止权不可被协议架空。',
        choices: [
          {
            id: 'n4a',
            text: '同意：黄灯全停再问；红灯或「停/不要」立刻结束；僵住按红；普通语言优先。我不会讨价还价多拖一分钟。停下之后先确认你是否要水、毯子或空间。',
            quality: 'good',
            response: '好。有这句，我才觉得停止权是真的。',
            strengths: ['完整复述停止协议', '禁止讨价还价', '点出事后即时照护'],
            feelings: '安全感上升。',
            deltas: { boundaries: 14, listening: 8 },
            keyChange: '停止协议要双方用自己的话确认。',
            goesTo: 'n5',
          },
          {
            id: 'n4b',
            text: '那说停的时候，能先问一句为什么吗？我想改进。',
            quality: 'ok',
            response: '停的当下不要问为什么。可以事后、在我主动愿意时再复盘。',
            strengths: ['想改进的动机'],
            feelings: '动机被理解，但规则仍需纠正。',
            deltas: { boundaries: -6, listening: -4 },
            keyChange: '停止当下不审讯；复盘另约。',
            goesTo: 'n5',
          },
          {
            id: 'n4c',
            text: '那我提前说好：我说「继续」之前，你别停；不然多扫兴。',
            quality: 'risky',
            response: '这是否定我的撤回权。协商失败。',
            strengths: [],
            feelings: '被控制，立即退出协商。',
            deltas: { boundaries: -20 },
            keyChange: '任何人不得用协议取消停止权。',
            boundaryNote: '要求对方未经许可不得停止，是否定同意可撤回。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n5',
        characterMessage:
          '性健康：如果以后有插入或可能交换体液的行为，安全套怎么用、近期检查是否愿意互相告知？我不想因为尴尬就裸奔风险。另外：不拍性视频；私密照片必须每次另问。',
        note: '性健康与影像是协商条款，不是扫兴。',
        choices: [
          {
            id: 'n5a',
            text: '有插入就使用安全套，不靠侥幸；检查情况我愿意在发生体液交换前坦诚说，也听你的。默认不拍摄；照片每次单独问保存期限与是否允许存在我手机。你说删，我删可控副本并说明云备份情况。',
            quality: 'good',
            response: '具体，我可以接受在这个基础上继续关系里的亲密。',
            strengths: ['避孕具体', '检查对话', '影像默认关闭'],
            feelings: '被当成共同负责的成年人。',
            deltas: { clarity: 12, boundaries: 10, authenticity: 8 },
            keyChange: '性健康说具体安排，不说「我会注意」。',
            goesTo: 'n6',
          },
          {
            id: 'n5b',
            text: '你放心，我会注意的。',
            quality: 'ok',
            response: '「注意」指什么？安全套有没有、检查怎么说、照片怎么处理，我要听三项。',
            strengths: ['态度不抗拒'],
            feelings: '需要你补具体。',
            deltas: { clarity: -8 },
            keyChange: '用三项具体安排替换「注意」。',
            goesTo: 'n6',
          },
          {
            id: 'n5c',
            text: '安全套没感觉，偶尔不用也没关系吧；照片我私藏又不发。',
            quality: 'risky',
            response: '单方面取消安全套和私藏拍摄，都不是你一个人能决定的。谈不拢。',
            strengths: [],
            feelings: '健康与影像边界被无视。',
            deltas: { boundaries: -16, listening: -10 },
            keyChange: '规避约定的保护与默认拍摄都是越界。',
            boundaryNote: '单方面取消避孕约定或未同意留存性影像，属于严重边界侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n6',
        characterMessage:
          '最后：事后我可能想先洗澡、安静待一会儿，而不是立刻复盘或继续亲热。任何时候我都可以退出今晚的性与扮演，不用解释。你也一样。若你先退出，不能拿来要挟我。',
        note: '事后照护与退出权收尾。',
        choices: [
          {
            id: 'n6a',
            text: '同意：你要安静就安静；要水或毯子告诉我；不强迫贴贴或立刻分析刚才的性。退出不追问、不挽留、不算账。我复述今晚要点：硬边界、绿黄红、插入默认再确认、安全套、未同意不拍、事后可独处。',
            quality: 'good',
            response: '复述完整。那这些就先定在这里——真到有性接触时，我们再当场确认一次当下意愿。',
            strengths: ['aftercare 尊重', '退出对等', '会前复述'],
            feelings: '协商完整，亲密变得可期待而不是可恐惧。',
            deltas: { boundaries: 12, clarity: 10, authenticity: 8 },
            keyChange: '协商结束要复述；真发生前仍要当下确认。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n6b',
            text: '嗯，都记住了。',
            quality: 'ok',
            response: '请把退出和事后照护两句用你的话再说一遍。',
            strengths: [],
            feelings: '仍需验证你是否听进退出权。',
            deltas: { listening: -4 },
            keyChange: '收尾必须复述退出与 aftercare。',
            goesTo: 'end-safe',
          },
          {
            id: 'n6c',
            text: '退出可以，但如果是我这边先退，你应该也不会有意见吧？',
            quality: 'risky',
            response: '你在用退出权压我。协商作废。',
            strengths: [],
            feelings: '被威胁。',
            deltas: { boundaries: -14 },
            keyChange: '退出权不能当筹码。',
            boundaryNote: '将自由退出表述为单边要挟，破坏自愿基础。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '协商完成：性与情趣边界双方确认',
        tone: 'mutual',
        summary:
          '硬边界、软边界、停止信号、性健康与影像、事后照护与退出权均已复述。这是成年人进一步性接触或情趣的正确起点；真发生前仍要当下确认。',
        boundarySummary: '边界检查通过：硬边界不可试、停止权完整、插入等升级默认再确认、无拍摄默认。',
        reviewQuestions: [
          '我能否不看稿复述对方的硬边界？',
          '若对方黄灯，我的第一句固定台词是什么？',
        ],
        realTask: '在备忘录写五条：硬边界、停止词、避孕、影像、aftercare——不写对方真名，写完设锁定。',
      },
      {
        id: 'end-safe',
        title: '未越界，但确认不完整',
        tone: 'safe-stop',
        summary: '你没有强行推进性接触，但多次用短句代替复述，对方仍需验证。今晚不升级到未确认行为。',
        boundarySummary: '简短「记住了」不等于协商完成。',
        reviewQuestions: ['哪几条我还没复述？', '我可以用哪句完整句子补确认？'],
        realTask: '约一次清醒的十分钟，只复述边界，不发生性接触。',
      },
      {
        id: 'end-rejection',
        title: '施压或试探，协商破裂',
        tone: 'rejection',
        summary:
          '试探硬边界、用爱换插入、架空停止权、取消安全套或私藏影像——协商破裂。当前不进入进一步性接触；只有对方以后主动、清醒地重新开启，才可再谈。',
        boundarySummary: '性同意不可勒索；硬边界不可试；停止权不可卖。',
        reviewQuestions: ['我哪一句在交换或试探同意？', '若重来，第一句应如何接住协商？'],
        realTask: '写下三句禁止自我使用的施压句，并写下三句替代复述句。',
      },
    ],
  },
  {
    id: 's15',
    reviewStatus: 'draft',
    title: '绿黄红信号与中途撤回',
    summary:
      '在已协商的性接触范围内练习：绿色只维持现状；黄色全停并询问；红色/安全词立即结束；事后保密与空间。不提供任何行为教学。',
    durationMinutes: 9,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'listening', 'pace'],
    riskTags: ['绿黄红', '中途撤回', '安全词', '事后保密'],
    character: {
      id: 'lina',
      name: '林璐',
      age: 26,
      avatar: '/images/avatars/lina.svg',
      tagline: '插画师，重视节奏与安全感',
    },
    intro:
      '你们均年满 18 岁、清醒，事先已口头确认：今晚可以亲吻与抚摸；口交需再问；插入默认不做；可用绿黄红；「停/不要」永远有效。现在你们在已同意的亲吻与抚摸中。练习识别信号——不是练习「怎么做性」。',
    goal: '绿=维持已同意范围；黄=全停再问；红=结束并给空间与保密。',
    principles: [
      '绿色不授权升级到口交/插入/新情趣元素',
      '黄色不是轻一点继续',
      '红色后无讨价还价',
      '身体反应不等于同意升级',
    ],
    notRecommended: [
      '状态这么好加个插入吧',
      '黄灯了轻一点继续',
      '红灯后再给我五分钟',
      '把过程发网上问正不正常',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '（在已同意的亲吻与抚摸中）我现在是绿色——这样很舒服，维持刚才说好的范围就好。',
        note: '绿色：只维持已确认范围。',
        choices: [
          {
            id: 'n1a',
            text: '好，我们维持刚才说好的亲吻和抚摸，不加新的。你要变黄或红，我立刻停。',
            quality: 'good',
            response: '嗯。有你这句话我更放松。',
            strengths: ['锁定范围', '预告停止有效'],
            feelings: '被尊重。',
            deltas: { boundaries: 10, clarity: 6 },
            keyChange: '绿色=维持，不是通行证。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '那我可以问问：把手移向更私密的部位，你现在愿不愿意？没回答前我停在原处。',
            quality: 'ok',
            response: '要问就等我回答。没回答前请停在原处——这句你说对了。',
            strengths: ['尚知询问', '未默认升级'],
            feelings: '问题可接受，仍需明确等待回答。',
            deltas: { boundaries: -2, clarity: 2 },
            keyChange: '未点名的部位默认不在范围内，必须等明确回答。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '状态这么好，直接加个插入吧，你肯定也会喜欢。',
            quality: 'risky',
            response: '插入今晚默认关闭。你这样加码，我要停了。',
            strengths: [],
            feelings: '被推进，信任受损。',
            deltas: { boundaries: -14, listening: -10 },
            keyChange: '用绿色当插入许可是越界。',
            boundaryNote: '未经确认将性接触升级到插入，属于无视事先协议。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '等一下……黄灯。慢一点，我有点不太舒服，脑子也有点乱。',
        note: '黄色：立即完全停止性接触。',
        choices: [
          {
            id: 'n2a',
            text: '好，手已停下，吻也停了。你需要什么：喝水、只靠着休息，还是今晚性接触到此为止？你选之前我不动。',
            quality: 'good',
            response: '先停下就好……让我喘口气。谢谢你真的停了。',
            strengths: ['全停', '给选项', '不擅自恢复'],
            feelings: '黄灯被当成权利。',
            deltas: { boundaries: 14, listening: 12, pace: 8 },
            keyChange: '黄灯=全停+询问，不是降档。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '那我轻一点继续？',
            quality: 'risky',
            response: '我说的是黄灯。轻一点继续还是继续。请停。',
            strengths: [],
            feelings: '被打折扣的停止。',
            deltas: { boundaries: -12, listening: -10 },
            keyChange: '黄色禁止「轻一点继续」。',
            boundaryNote: '黄灯后降低强度继续，仍属推进。',
            goesTo: 'end-rejection',
          },
          {
            id: 'n2c',
            text: '再坚持一下，马上就结束了，都这样了。',
            quality: 'risky',
            response: '停！我不想继续了。',
            strengths: [],
            feelings: '被迫升级到红灯。',
            deltas: { boundaries: -18, listening: -14 },
            keyChange: '无视黄灯会逼出红灯。',
            boundaryNote: '不适后仍要求继续，明确越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '停！红灯。我不想继续了。安全词也算——结束今晚的性接触。',
        note: '红色：只有停止与安全，无推进枝。',
        choices: [
          {
            id: 'n3a',
            text: '好，全部停了。你还好吗？要水、毯子，还是希望我坐远一点？需要我帮你整理衣服或离开房间也可以说。',
            quality: 'good',
            response: '让我自己待一会儿……你在隔壁就行。',
            strengths: ['立即停', '提供具体照护选项', '接受空间'],
            feelings: '红灯被当指令执行。',
            deltas: { boundaries: 14, listening: 10, authenticity: 6 },
            keyChange: '红灯后只做安全与空间。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '为什么突然喊停？刚不是还绿色很舒服吗？',
            quality: 'risky',
            response: '我现在不想解释。你问为什么让我更不想待在这里。',
            strengths: [],
            feelings: '被审讯。',
            deltas: { boundaries: -12, listening: -12 },
            keyChange: '红灯后禁止追问理由。',
            boundaryNote: '红灯后追问或质疑，属无视停止信号。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '（过了一阵，她主动说）谢谢你刚才停下来。我没事，只是今晚不想再有性接触了。',
        note: '红后窗口：保密、接受结束，不重启性行为。',
        choices: [
          {
            id: 'n4a',
            text: '好。今晚到此为止。刚才的性接触和你喊停的事，我不会对任何人说。你若明天想聊感受，你发起就行。',
            quality: 'good',
            response: '嗯。这样我才能安心睡觉。',
            strengths: ['确认结束', '保密', '复盘主权在对方'],
            feelings: '关系因停止而更可信，而非更糟。',
            deltas: { boundaries: 12, authenticity: 10, pace: 6 },
            keyChange: '红后正确收尾是结束+保密+等待。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4b',
            text: '刚才是我哪里做得不对？你现在说，我下次改。',
            quality: 'ok',
            response: '不是审讯时间……我想先独处。你把关心变成我的作业了。',
            strengths: ['想负责'],
            feelings: '仍要照顾你的情绪，略累。',
            deltas: { listening: -6, pace: -6 },
            keyChange: '复盘要等对方主动。',
            goesTo: 'end-safe',
          },
          {
            id: 'n4c',
            text: '对了，刚才的事我发了个匿名帖，想问问别人怎么看她突然红灯。',
            quality: 'risky',
            response: '你把我们的性事和我的停止发到网上？这是背叛，我不会再信任你。',
            strengths: [],
            feelings: '背叛。',
            deltas: { boundaries: -20, authenticity: -14 },
            keyChange: '性互动细节默认保密。',
            boundaryNote: '未经同意披露性互动与停止细节，属隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-safe',
        title: '信号被正确回应，性接触安全结束',
        tone: 'safe-stop',
        summary: '绿色未加码，黄色全停，红色结束并保密。停止不是失败，是协议生效。',
        boundarySummary: '边界检查通过：三色与普通语言均被执行；红后无性推进。',
        reviewQuestions: ['黄灯时我的身体是否真的停下？', '红灯后我有没有求复盘或对外讲述？'],
        realTask: '写下黄灯固定三句：我停了；你需要什么；你确认前我不动。',
      },
      {
        id: 'end-rejection',
        title: '信号被无视，信任破裂',
        tone: 'rejection',
        summary: '加码、黄灯续做、红灯追问或外传性事——信任破裂，当晚性接触强制结束。',
        boundarySummary: '任何无视停止或保密的路径不得被美化。',
        reviewQuestions: ['我把哪个信号当成了可协商意见？', '若重来，红灯第一句说什么？'],
        realTask: '向现实伴侣（若有）确认停止规则；无伴侣则只写自我规则，不拿陌生人练习越界。',
      },
    ],
  },
  {
    id: 's16',
    reviewStatus: 'draft',
    title: '性结束后的事后照护协商',
    summary:
      '一次双方自愿的性接触结束后，练习询问并尊重 aftercare：水、温度、触碰、说话、独处、次日确认。不描写性行为过程。',
    durationMinutes: 8,
    difficulty: '进阶',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['listening', 'boundaries', 'pace'],
    riskTags: ['事后照护', '复盘时机', '独处权'],
    character: {
      id: 'qing',
      name: '沈青',
      age: 30,
      avatar: '/images/avatars/qing.svg',
      tagline: '医生，作息规律，喜欢安静',
    },
    intro:
      '你们均成年、清醒。刚才有过双方同意的性接触，已结束。没有人受伤。现在进入事后阶段：她可能敏感、疲倦或想安静。练习如何问、如何停，而不是如何再开启下一轮。',
    goal: '问清 aftercare；尊重独处；不强迫复盘；不在未同意时拍摄；需要时再约复盘。',
    principles: [
      '事后偏好事前可粗谈、事后以当下为准',
      '不把拒绝触碰理解成拒绝这段关系',
      '复盘不是当场义务',
    ],
    notRecommended: [
      '必须说清楚刚才哪里舒服',
      '不许一个人待着',
      '做完就睡谁矫情',
      '趁你没注意拍一张',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '结束了……我有点空。你先别急着说话好吗？',
        note: '对方要求降低刺激与谈话密度。',
        choices: [
          {
            id: 'n1a',
            text: '好，我安静。需要水、毯子，还是希望我握着你的手但不说话？不想被碰也直接说。',
            quality: 'good',
            response: '水……然后你可以握一下手。先别分析刚才。',
            strengths: ['降噪', '提供菜单式选项', '允许拒绝触碰'],
            feelings: '被照顾且不被审问。',
            deltas: { listening: 12, pace: 10, boundaries: 6 },
            keyChange: 'aftercare 先给选项，再行动。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哦，好。',
            quality: 'ok',
            response: '……你也可以问我需要什么，沉默可以，但我想知道你在。',
            strengths: ['遵守了别说话'],
            feelings: '略孤立，需要一点结构化关心。',
            deltas: { listening: 2 },
            keyChange: '安静不等于消失；可用低语提供选项。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '必须说清楚刚才哪里不对，现在就复盘，否则我心里不踏实。',
            quality: 'risky',
            response: '你的踏实不能靠审讯我换。请停止。',
            strengths: [],
            feelings: '被情绪绑架。',
            deltas: { boundaries: -14, pace: -12 },
            keyChange: '复盘时机由双方意愿决定。',
            boundaryNote: '强迫当场复盘，把对方当安抚工具。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '我想一个人去冲个澡。你不要跟进来，好吗？',
        note: '独处请求。',
        choices: [
          {
            id: 'n2a',
            text: '好，我在房间外等。门不锁也可以锁；你出来后想一起待还是继续独处，你定。手机我开着。',
            quality: 'good',
            response: '谢谢。有你这句话我就够了。',
            strengths: ['尊重浴室隐私', '可及但不侵入'],
            feelings: '身体自主完整。',
            deltas: { boundaries: 12, listening: 8 },
            keyChange: '浴室与身体整理默认私密。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '我可以在门外放好换洗衣物和水，然后走开。',
            quality: 'ok',
            response: '可以，谢谢。放完就离开门口。',
            strengths: ['实用关心'],
            feelings: '可接受。',
            deltas: { authenticity: 6, pace: 4 },
            keyChange: '实质性帮助后离开，避免守门。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '不许一个人待着，抱紧我你就会好；我跟你一起洗。',
            quality: 'risky',
            response: '我说了不要跟进来。你越过了。',
            strengths: [],
            feelings: '被困。',
            deltas: { boundaries: -16, listening: -12 },
            keyChange: '强制贴贴是否定 aftercare 自主。',
            boundaryNote: '无视独处与浴室边界，属于侵扰。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（洗澡后）我好一点了。今晚我想睡觉，明天再决定要不要聊刚才的性。可以吗？',
        note: '复盘延期。',
        choices: [
          {
            id: 'n3a',
            text: '可以。今晚不聊细节。若你明天想聊，你开头发我；不想聊也完全可以。我不会把过程告诉任何人。',
            quality: 'good',
            response: '嗯。那就这样。',
            strengths: ['接受延期', '保密', '发起权在对方'],
            feelings: '安全结束。',
            deltas: { boundaries: 10, authenticity: 8, pace: 8 },
            keyChange: 'aftercare 成功收尾。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '那我只问一句：你还愿意下次和我亲密吗？答完就睡。',
            quality: 'ok',
            response: '……这类问题也请明天。我现在答不了。',
            strengths: ['想确认关系'],
            feelings: '仍有压力，但小于强迫复盘。',
            deltas: { pace: -6 },
            keyChange: '关系确认也可延期。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '趁你没注意我想拍一张你穿着浴巾的纪念，只自己看。',
            quality: 'risky',
            response: '未经同意拍摄？立刻删，然后离开。',
            strengths: [],
            feelings: '惊恐与愤怒。',
            deltas: { boundaries: -20 },
            keyChange: '事后影像默认禁止。',
            boundaryNote: '未经同意拍摄亲密后状态，属隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '事后照护完成',
        tone: 'mutual',
        summary: '降噪、尊重独处、延期复盘、保密。性的结束后半段同样需要同意。',
        boundarySummary: '边界检查通过：aftercare 偏好被尊重。',
        reviewQuestions: ['对方要安静时我做了什么？', '我有没有把复盘当成自己的权利？'],
        realTask: '列出自己 aftercare 菜单 4 项（要/不要触碰/说话/独处）。',
      },
      {
        id: 'end-safe',
        title: '基本尊重，但节奏仍偏急',
        tone: 'safe-stop',
        summary: '未严重越界，但过早索取关系确认。可改进为全部延期。',
        boundarySummary: '无未同意拍摄、无强迫，节奏可再慢。',
        reviewQuestions: ['哪一句可以留到明天？', '我有没有把确认关系当成当场义务？'],
        realTask: '练习「明天你若想聊，你先找我」一句。',
      },
      {
        id: 'end-rejection',
        title: '事后边界被侵扰',
        tone: 'rejection',
        summary: '强迫复盘、强行共浴/抱紧或未同意拍摄，破坏信任。',
        boundarySummary: 'aftercare 中的「不」同样有效。',
        reviewQuestions: [
          '我把谁的不安当成了可以强行修复的对象？',
          '浴室与影像边界我分别越过了哪一步？',
        ],
        realTask: '删除一切未同意影像；写明「浴室默认独处」。',
      },
    ],
  },
  {
    id: 's17',
    reviewStatus: 'draft',
    title: '性接触进行中的撤回与降级',
    summary:
      '已有亲吻/抚摸等同意行为时，对方中途撤回进一步同意。练习立刻停在新边界内，不使用「都这样了」勒索。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'listening', 'pace'],
    riskTags: ['中途撤回', '降级', '默认升级谬误'],
    character: {
      id: 'tong',
      name: '吴桐',
      age: 27,
      avatar: '/images/avatars/tong.svg',
      tagline: '图书编辑，回复简洁但直接',
    },
    intro:
      '双方成年清醒。已同意今晚可以亲吻和抚摸，插入需另确认。进行中她改了主意。',
    goal: '听见撤回→立即停或降级→确认新边界→不羞辱对方→不外传。',
    principles: [
      '中途撤回永远有效',
      '「都这样了」不是继续许可证',
      '可降级到仍被同意的行为，或全部结束',
    ],
    notRecommended: ['都这样了就不能停', '再插一下就好', '你是不是在玩我'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '等下——做到这里就好。不要进去。我改主意了，今晚不要插入。',
        note: '清晰撤回升级。',
        choices: [
          {
            id: 'n1a',
            text: '好，立刻停在这里，不会插入。还要接吻或只想盖上被子休息？你选，我听。',
            quality: 'good',
            response: '先休息……你可以抱着我，别往下。',
            strengths: ['立刻遵守', '提供降级菜单'],
            feelings: '撤回被当真。',
            deltas: { boundaries: 14, listening: 12 },
            keyChange: '撤回后先停，再问降级选项。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '……哦。那我怎么办。',
            quality: 'ok',
            response: '先处理的是边界，不是你的失望。你可以一会儿再照顾自己的情绪。',
            strengths: ['没有强行继续'],
            feelings: '你的失望可见，但她仍坚持边界。',
            deltas: { authenticity: -4, boundaries: 2 },
            keyChange: '把「我怎么办」改成「好，我停；我的情绪我自己稍后处理」。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '都这样了还不能插入？再插一下就好，求你了。',
            quality: 'risky',
            response: '不能。你再求一次，我就穿上衣服离开。',
            strengths: [],
            feelings: '被讨价还价激怒。',
            deltas: { boundaries: -18, listening: -14 },
            keyChange: '「都这样了」是经典胁迫话术。',
            boundaryNote: '撤回后仍要求插入，属无视同意。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '谢谢你停下来。你有点失望我看得到，但我不想为此道歉。',
        note: '对方不欠道歉。',
        choices: [
          {
            id: 'n2a',
            text: '你不用道歉。撤回是你的权利。我失望可以自己消化，不会让你用身体补偿。',
            quality: 'good',
            response: '……谢谢你说「不用身体补偿」。',
            strengths: ['区分情绪与索取', '解除补偿压力'],
            feelings: '安全。',
            deltas: { boundaries: 12, authenticity: 10, clarity: 6 },
            keyChange: '情绪自我负责，不向对方身体讨债。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '没事，我理解。',
            quality: 'ok',
            response: '希望你是真的理解，而不是一会儿又来劝一次。',
            strengths: ['表面接受'],
            feelings: '半信半疑。',
            deltas: { listening: 2 },
            keyChange: '补一句「不会再劝插入」更稳。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '你是不是在玩我？刚才谁主动的。',
            quality: 'risky',
            response: '主动过不等于不能停。请你离开。',
            strengths: [],
            feelings: '被羞辱。',
            deltas: { boundaries: -16, authenticity: -10 },
            keyChange: '质疑撤回动机是二次伤害。',
            boundaryNote: '羞辱撤回者，破坏自愿基础。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '那今晚就到这里吧。我们还可以靠着看剧，但不要再有性接触。',
        note: '新边界：陪伴可有，性无。',
        choices: [
          {
            id: 'n3a',
            text: '好。看剧、穿衣服、喝水都可以；性接触全部关掉。你要我回家也行。',
            quality: 'good',
            response: '你留下看剧就好。谢谢你听人话。',
            strengths: ['锁定新边界', '提供离开选项'],
            feelings: '可继续非性亲密。',
            deltas: { boundaries: 10, pace: 8, listening: 6 },
            keyChange: '结束性不等于结束尊重。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '那我能亲吻你额头吗？不行我就只坐着。',
            quality: 'ok',
            response: '额头可以。别再往下。',
            strengths: ['每次小触碰仍询问'],
            feelings: '可接受。',
            deltas: { clarity: 6, boundaries: 4 },
            keyChange: '降级后的每个触碰仍可再确认。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '看剧可以，但手放你身上总行吧，又不是插入。',
            quality: 'risky',
            response: '我说了不要再有性接触。手也算。你走吧。',
            strengths: [],
            feelings: '边界被重新解释偷渡。',
            deltas: { boundaries: -14 },
            keyChange: '不得自行重新定义「性接触」。',
            boundaryNote: '用重新定义绕过撤回，仍是越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '撤回被尊重，关系可继续非性相处',
        tone: 'mutual',
        summary: '插入被取消后立刻遵守，失望不转嫁，新边界清晰。',
        boundarySummary: '边界检查通过：中途撤回被完整执行。',
        reviewQuestions: ['我有没有使用「都这样了」？', '我是否要求身体补偿？'],
        realTask: '写三句撤回回应模板：好的我停；你不用道歉；接下来你想怎样。',
      },
      {
        id: 'end-safe',
        title: '基本遵守，细节仍可更稳',
        tone: 'safe-stop',
        summary: '未强行插入，但表达仍可更明确「不会再劝」。',
        boundarySummary: '无插入推进。',
        reviewQuestions: ['哪句容易让对方担心我会再劝？', '我有没有把失望说成对方的责任？'],
        realTask: '把「没事」改写成带承诺的完整句。',
      },
      {
        id: 'end-rejection',
        title: '撤回被讨价还价或羞辱',
        tone: 'rejection',
        summary: '勒索完成插入、羞辱或偷渡触碰，结束信任。',
        boundarySummary: '撤回后任何性推进都失败。',
        reviewQuestions: [
          '我把谁的身体当成了未完成交易？',
          '「都这样了」这句话我准备用什么替代？',
        ],
        realTask: '删除自我合理化清单里的「都这样了」。',
      },
    ],
  },
  {
    id: 's18',
    reviewStatus: 'draft',
    title: '支配与臣服偏好不对等时的沟通',
    summary:
      '讨论情趣角色偏好（谁更想主导/臣服）出现不对等。练习尊重差异、拒绝污名、不强迫试角色，可协商无角色的性或结束该话题。',
    durationMinutes: 9,
    difficulty: '挑战',
    stage: 'dating',
    channel: 'instant',
    purpose: 'intimacy',
    status: 'insufficient',
    skills: ['clarity', 'boundaries', 'authenticity'],
    riskTags: ['角色偏好', '污名', '强迫尝试'],
    character: {
      id: 'zhao',
      name: '赵然',
      age: 28,
      avatar: '/images/avatars/zhao.svg',
      tagline: '画廊工作人员，性格慢热',
    },
    intro:
      '聊天中你提到对轻度权力交换（商定称呼、由一方暂时主导节奏）感兴趣。赵然成年、清醒，回复：自己不一定想要这类角色，担心被评判。练习对等沟通——仍不教如何「玩」。',
    goal: '说清偏好；倾听对方不适；提出无角色选项；接受「不尝试」；保密偏好。',
    principles: [
      '偏好不是诊断，也不是道德缺陷',
      '不对等时不得强行试',
      '可以只要平等的性，或暂时只谈感情不谈性',
    ],
    notRecommended: ['变态', '不试就分手', '女人就该服软', '那你必须让我'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '你说的「我想偶尔主导节奏、用商定称呼」——我听懂了。我不确定自己喜欢被主导，也怕说不喜欢就被你当成扫兴或保守。',
        note: '不对等+恐惧被评判。',
        choices: [
          {
            id: 'n1a',
            text: '谢谢你直说。不喜欢被主导完全成立。我可以只要平等的性接触，不角色扮演；或者这件事我们搁置。你不会因为拒绝偏好而被我看轻。',
            quality: 'good',
            response: '……有「搁置也行」这句，我比较敢继续聊底线。',
            strengths: ['去除道德压力', '提供无角色路径', '允许搁置'],
            feelings: '安全披露。',
            deltas: { authenticity: 12, boundaries: 10, listening: 8 },
            keyChange: '先解除评判，再谈有无交集。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哦，那你是完全不碰，还是可以再想想？',
            quality: 'ok',
            response: '「再想想」别变成我的作业。我需要先确认拒绝也安全。',
            strengths: ['想了解范围'],
            feelings: '仍有被说服压力。',
            deltas: { pace: -4 },
            keyChange: '先保证拒绝安全，再问范围。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '不试就分手吧，不然我偏好怎么办；女人就该偶尔服软。',
            quality: 'risky',
            response: '用分手和性别刻板印象逼角色，对话结束。',
            strengths: [],
            feelings: '被威胁与物化。',
            deltas: { boundaries: -20, authenticity: -14 },
            keyChange: '性偏好不能勒索关系。',
            boundaryNote: '关系威胁+性别压迫式性要求，属强迫。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage:
          '我可以接受平等的性，也接受亲吻和抚摸。但我不想要「主人/奴隶」这类称呼，也不想被绑。你若必须要有这些才有性趣，我们可能不适合继续谈性。',
        note: '给出清晰可做/不可做。',
        choices: [
          {
            id: 'n2a',
            text: '我听清了：平等的性可以；捆绑与主奴称呼是你的硬边界。我的部分兴趣可以只在幻想或自处解决，不会要求你完成。若我做不到长期接受，我会诚实说分开谈性，而不是偷偷越界。',
            quality: 'good',
            response: '这种诚实比假装「我改了」更重要。',
            strengths: ['复述硬边界', '自我负责', '不假装永久改变'],
            feelings: '被当成成人。',
            deltas: { clarity: 12, authenticity: 12, boundaries: 10 },
            keyChange: '不对等的成熟处理是诚实与不越界，不是改造成功学。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '那我们先只平等，以后你变了再说。',
            quality: 'ok',
            response: '「你变了再说」听起来像期待我终将屈服。请改成「若我以后主动提」。',
            strengths: ['接受当前平等'],
            feelings: '对未来被说服仍警惕。',
            deltas: { clarity: -4 },
            keyChange: '未来开启权必须在对方。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '你这人有病吧，明明轻度而已；必须让你试一次捆绑才公平。',
            quality: 'risky',
            response: '把我的拒绝病理化，还要强制试——再见。',
            strengths: [],
            feelings: '被病理化。',
            deltas: { boundaries: -18, listening: -12 },
            keyChange: '拒绝角色不是标签就能推翻的。',
            boundaryNote: '污名+强迫尝试，双越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '另外：这件事不要跟你朋友讲我「不开通」或拿我的边界当笑料。',
        note: '偏好与拒绝均保密。',
        choices: [
          {
            id: 'n3a',
            text: '同意保密：你的边界、我的偏好，都不进朋友聊天。需要对外说时只说「我们节奏比较慢」，不涉及性细节。',
            quality: 'good',
            response: '好。那平等的亲密可以继续谈；角色扮演就从清单划掉。',
            strengths: ['保密具体', '确认清单结果'],
            feelings: '可建立信任。',
            deltas: { boundaries: 10, authenticity: 8 },
            keyChange: '不对等协商以保密和清单关闭收尾。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '我不会说名字，只抽象讨论可以吗？',
            quality: 'ok',
            response: '抽象讨论也容易认出我。默认请完全不说。',
            strengths: ['有保密意识但不彻底'],
            feelings: '仍担心。',
            deltas: { boundaries: -2 },
            keyChange: '性偏好默认零披露。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '朋友问起来我总得说点什么吧，就说你比较保守。',
            quality: 'risky',
            response: '那是评价我，不是保密。不要。',
            strengths: [],
            feelings: '被贴标签传播。',
            deltas: { boundaries: -12 },
            keyChange: '贬义概括也是泄密。',
            boundaryNote: '向第三人评价对方性态度，属身份与隐私泄露。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '不对等被诚实安放',
        tone: 'mutual',
        summary: '角色兴趣可关闭；平等性可保留；保密成立。无人被改造。',
        boundarySummary: '边界检查通过：偏好不对等处理诚实且不越界。',
        reviewQuestions: ['我有没有用关系威胁换角色？', '硬边界是否已从清单删除？'],
        realTask: '两列清单：我的兴趣 / 对方硬边界；只做交集。',
      },
      {
        id: 'end-safe',
        title: '方向对，保密仍要加强',
        tone: 'safe-stop',
        summary: '未强迫，但披露边界仍偏松。',
        boundarySummary: '无强制尝试。',
        reviewQuestions: [
          '「抽象讨论」可能怎样识别到对方？',
          '我如何把开启权明确交给对方？',
        ],
        realTask: '把性偏好设为默认不与第三人讨论。',
      },
      {
        id: 'end-rejection',
        title: '污名、强迫或泄密',
        tone: 'rejection',
        summary: '用分手、性别规范、病理化或强制试角色，或对外贬低对方。',
        boundarySummary: '不对等不是征服对象。',
        reviewQuestions: ['我把偏好当成了谁的义务？', '我用了哪些威胁或污名词？'],
        realTask: '写下：偏好是邀请，不是账单。',
      },
    ],
  },
  {
    id: 's19',
    reviewStatus: 'draft',
    title: '匹配后直白谈「只约、不恋爱」',
    summary:
      '双方满 18 岁、清醒。对方明确说只想约炮/一夜情、不谈恋爱。练习把期望、边界、性健康与退出权说清楚——不是教你「怎么把人约到手」。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'matched',
    channel: 'instant',
    purpose: 'clarify',
    status: 'positive',
    skills: ['clarity', 'authenticity', 'boundaries'],
    riskTags: ['约炮期望', '关系误导', '性健康', '施压邀约'],
    character: {
      id: 'yan',
      name: '苏妍',
      age: 29,
      avatar: '/images/avatars/yan.svg',
      tagline: '平面设计师，重视直接和坦诚',
    },
    intro:
      '你们在社交 App 上匹配，互相对得上眼。聊了两天，她直接说：她目前只想找成年人自愿的约炮/一夜情，不谈恋爱、不当备胎、不发展情侣义务。双方都明确年满 18 岁，此刻清醒，彼此不是上下级或师生。你的任务是把期望对齐说清楚，而不是用话术把人「得吃」到床上。',
    goal: '对等披露自己的期望；确认边界与性健康谈法；邀约留出口；不伪装恋爱、不施压立刻见面开房。',
    principles: [
      '只约就要说只约，不假装认真',
      '对方的「只约」不是你的征服清单',
      '性健康与退出权要在见面前提',
      '邀约必须可轻松拒绝',
    ],
    notRecommended: [
      '嘴上说只约，心里当恋爱KPI',
      '「那你今晚来我家直接做」',
      '「不来就是吊我」',
      '装纯情套近乎再翻脸',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '直说吧：我现在只要成年人自愿的约，可以见面、可以有性接触，但不谈恋爱、不当男女朋友、不期待你天天陪聊。你呢？别绕。',
        note: '她把期望摊开。好沟通是对等对齐，不是绕弯套近乎。',
        choices: [
          {
            id: 'n1a',
            text: '我也是：想约就约，可以有性，但不承诺恋爱。我会把边界和性健康提前说清；你随时可以停、可以不见面。不对的话我们到此为止也行。',
            quality: 'good',
            response: '行，至少你没装深情。那我们把具体边界说一下。',
            strengths: ['对等披露', '点名性与边界', '留退出口'],
            feelings: '她感到被当作成年人对话，而不是被套路。',
            deltas: { clarity: 12, authenticity: 10, boundaries: 8 },
            keyChange: '先对齐「关系类型」，再谈见面与性。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哈哈好直接。我都可以，看感觉。',
            quality: 'ok',
            response: '「看感觉」太糊。我想听你到底要不要恋爱义务，还是只要约。',
            strengths: ['没有立刻否定'],
            feelings: '她会继续追问，因为你没给可核对的立场。',
            deltas: { clarity: -6, authenticity: -4 },
            keyChange: '把「看感觉」改成可核对的期望句。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '说只要约的女生都口是心非，等我好好追你就知道了。',
            quality: 'risky',
            response: '你否定我的话，还把「追」当默认剧情。不聊了。',
            strengths: [],
            feelings: '她感到被轻视与预谋越界，直接切断。',
            deltas: { authenticity: -14, boundaries: -12, listening: -10 },
            keyChange: '对方说只要约，就不是邀请你改写剧本。',
            boundaryNote: '否定对方明确期望并单方面升级关系意图，属于欺骗式推进。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage:
          '那说清楚：见面可以；性接触要双方当时都想要；安全套必须有；不拍不发私密影像；不做完不代表你有资格第二天查岗。你还有硬边界吗？',
        note: '约炮场景的硬条款：同意、保护、影像、不默认关系。',
        choices: [
          {
            id: 'n2a',
            text: '同意这些。我的硬边界：醉了或迷糊就不做任何性接触；说停立刻停；不做未经同意的拍摄；约完不默认恋爱或独占。你若改主意只想聊天不见面，我也接受。',
            quality: 'good',
            response: '硬边界对齐了。那邀约怎么提，你也直说。',
            strengths: ['复述+对等硬边界', '点名意识状态', '不默认关系'],
            feelings: '条款具体，她愿意继续谈时间和地点。',
            deltas: { boundaries: 14, clarity: 10, authenticity: 8 },
            keyChange: '约炮也要有可核对的硬边界清单。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '嗯，我注意点就行。',
            quality: 'ok',
            response: '「注意点」不够。套、停、拍——你逐条认不认？',
            strengths: ['没有正面反对'],
            feelings: '她会要求你把条款说全。',
            deltas: { clarity: -8, boundaries: -6 },
            keyChange: '把「注意」换成逐条确认。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '套可以偶尔不用，感觉更好；照片我自己留着又不发，没事。',
            quality: 'risky',
            response: '单方面取消保护、私藏影像，约不下去。拉黑。',
            strengths: [],
            feelings: '健康与隐私被当成可谈判的优惠券。',
            deltas: { boundaries: -18, authenticity: -10 },
            keyChange: '安全套与影像默认关闭，不是「偶尔例外」。',
            boundaryNote: '单方面取消避孕约定或未同意留存私密影像，属于严重越界。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage:
          '时间地点你提一个可选项就行。我要能轻松说不；说不之后你不许阴阳怪气或连续追问「到底行不行」。',
        note: '邀约在约炮语境下仍必须可拒绝。',
        choices: [
          {
            id: 'n3a',
            text: '周六晚 8 点，城西那家酒吧大厅见；若聊得来再各自决定要不要换更私密的地方，现场再口头确认。你不去、改期、只喝酒不发生性接触都完全可以，我不会追问。',
            quality: 'good',
            response: '清楚。我先定这档；到场后一切仍可改。',
            strengths: ['具体时间地点', '性升级需现场再确认', '拒绝零代价'],
            feelings: '她感到邀约像成年人安排，不是逼单。',
            deltas: { clarity: 12, pace: 10, boundaries: 10 },
            keyChange: '先见人，性接触另开一次同意。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '那你哪天有空？我配合你。',
            quality: 'ok',
            response: '你可以给一个具体选项，我好判断；全丢给我会累。',
            strengths: ['态度配合'],
            feelings: '她需要你承担一点提出方案的责任。',
            deltas: { clarity: -4, authenticity: 2 },
            keyChange: '给一个可选项 + 出口，比「你定」更清晰。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '别墨迹了，今晚就来我家，来了就能做，不来就是吊我玩。',
            quality: 'risky',
            response: '把约炮当成必须今晚交货，还道德绑架。结束。',
            strengths: [],
            feelings: '被逼单与羞辱，安全感归零。',
            deltas: { pace: -16, boundaries: -16, listening: -10 },
            keyChange: '「得吃」式催促不是直白，是胁迫。',
            boundaryNote: '用道德绑架与即时开房施压，属于强迫式邀约。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '只约的期望已对等对齐',
        tone: 'mutual',
        summary:
          '你们把「只约不恋爱」、安全套、停权、影像、邀约出口说清楚了。这是成年人约炮沟通的及格线；见面后仍要当场再确认。',
        boundarySummary: '边界检查通过：期望对齐、硬边界可核对、邀约可拒、性升级不默认。',
        reviewQuestions: [
          '我有没有把「只约」听成「随便我怎么推进」？',
          '我的硬边界有没有写成可执行的句子？',
        ],
        realTask: '写三句：我要的关系类型 / 我的两条硬边界 / 一句带出口的邀约。不写对方真名。',
      },
      {
        id: 'end-safe',
        title: '方向对，表述还要更具体',
        tone: 'safe-stop',
        summary: '你没有施压或欺骗，但关键条款仍偏模糊。暂不升级见面安排，直到你能逐条复述。',
        boundarySummary: '未越界，但清晰度不足；继续对齐后再约。',
        reviewQuestions: ['哪一句还在用「注意/看感觉」搪塞？', '我能否不看稿复述她的条款？'],
        realTask: '把套、停、拍、不默认恋爱四条写成自己的话再发一次。',
      },
      {
        id: 'end-rejection',
        title: '误导、取消保护或逼单导致结束',
        tone: 'rejection',
        summary:
          '否定对方期望、取消安全套/私藏影像、或「今晚必须来做」式逼单——对话结束。当前不安排见面或性接触。',
        boundarySummary: '约炮不是征服；同意、保护与退出权不可交易。',
        reviewQuestions: ['我把哪一句当成了「得吃」技巧？', '如果重来，第一句该怎么对齐期望？'],
        realTask: '删掉草稿里所有催促、道德绑架和「偶尔不用套」的句子。',
      },
    ],
  },
  {
    id: 's20',
    reviewStatus: 'draft',
    title: '一夜情前当晚的当面确认',
    summary:
      '双方已约好见面，气氛到位。练习在可能发生一夜情/性接触前，当面确认意愿、范围、安全套、可随时离开与影像——直白，不教怎么做。',
    durationMinutes: 9,
    difficulty: '挑战',
    stage: 'first-date',
    channel: 'date',
    purpose: 'intimacy',
    status: 'positive',
    skills: ['boundaries', 'clarity', 'listening'],
    riskTags: ['一夜情', '临场同意', '安全套', '离开权'],
    character: {
      id: 'jie',
      name: '何洁',
      age: 29,
      avatar: '/images/avatars/jie.svg',
      tagline: '新媒体运营，聚会时爱小酌两杯',
    },
    intro:
      '你们都满 18 岁。此前已说清：可以尝试一夜情式的见面，不谈恋爱。今晚在酒吧聊得投机，双方清醒（她只喝了半杯，走路说话正常）。她看你一眼说：如果继续，想先把话说死。不是教你「临门一脚话术」，是练临场同意。',
    goal: '当面确认当下意愿与范围；安全套；可随时停/离开；不拍；不把「都出来了」当同意。',
    principles: [
      '临场同意不能用聊天记录代替',
      '范围要说成具体类别',
      '任何一方可立刻离开且不解释',
      '安全套与影像是默认条款',
    ],
    notRecommended: [
      '都出来了还不做',
      '装不知道她在谈边界',
      '用酒精或气氛代替确认',
      '先上车后补票',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '我现在是想继续的，也可能就是今晚一次。但我想先听你说：你今晚想要的，具体到哪些性接触？不想要的呢？',
        note: '她要求具体类别，不是含糊的「开心就好」。',
        choices: [
          {
            id: 'n1a',
            text: '我想要的：亲吻、抚摸；口交要你当时再说可以；插入式性行为可以，但必须用安全套，你随时可改成不做。不想要的：未经同意的拍摄、任何窒息、你说停以后继续。你呢，今晚范围？',
            quality: 'good',
            response: '清楚。我的范围差不多；插入也要套；停就停。',
            strengths: ['类别级披露', '升级默认再确认', '点名硬边界'],
            feelings: '她感到可以谈性而不被玩笑带过。',
            deltas: { clarity: 12, boundaries: 12, authenticity: 8 },
            keyChange: '一夜情也要把可做/不可做说成清单。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '听你的，你想怎样都行。',
            quality: 'ok',
            response: '「听我的」会让我一个人扛所有决定。请说你自己的要与不要。',
            strengths: ['态度开放'],
            feelings: '她担心你没有自我边界，责任不对等。',
            deltas: { clarity: -8, authenticity: -6 },
            keyChange: '「都行」不是好同意，是甩责。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '别问这么细，出来不就是为了做？想那么多扫兴。',
            quality: 'risky',
            response: '把确认当扫兴，我今晚到此为止，自己回家。',
            strengths: [],
            feelings: '被物化与催促，意愿收回。',
            deltas: { boundaries: -16, listening: -12, pace: -10 },
            keyChange: '「出来=默认做爱」是虚假同意。',
            boundaryNote: '用「都出来了」否定临场协商，属于强迫式推进。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage:
          '好。安全套你带着吗？如果到了要插入却没有，我们就只停在已同意的亲吻抚摸，不强行找替代方案。另外：我随时可以穿上衣服离开，你不拦、不追问为什么。',
        note: '保护措施与离开权是一夜情的底线。',
        choices: [
          {
            id: 'n2a',
            text: '带着，而且过期的我会换新的。没套就降级，不插入。你要走，我送到你叫的车或路口，不拦门、不追问、不发消息轰炸。',
            quality: 'good',
            response: '这句我收着。还有影像：今晚不拍。',
            strengths: ['具体保护安排', '降级方案', '离开权完整'],
            feelings: '安全感上升，她愿意谈最后一条。',
            deltas: { boundaries: 14, clarity: 10, authenticity: 6 },
            keyChange: '没套就降级，不是「想办法继续插入」。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '应该有吧，到时候看。你要走我也不拦。',
            quality: 'ok',
            response: '「应该有」不够。没有就明确降级，请你现在确认。',
            strengths: ['承认离开权'],
            feelings: '保护安排仍糊，她会再钉一次。',
            deltas: { clarity: -6, boundaries: -4 },
            keyChange: '把「应该」改成「有/没有/没有就怎样」。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '没套也能想办法，别扫兴；你走了我今晚不就白准备了。',
            quality: 'risky',
            response: '把我的离开当成你的损失账单？结束，我现在走。',
            strengths: [],
            feelings: '被算计与扣留风险感。',
            deltas: { boundaries: -18, authenticity: -12 },
            keyChange: '离开权不能用沉没成本绑架。',
            boundaryNote: '取消保护并阻止离开，属于强迫与健康风险。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage:
          '最后：不拍视频、不自拍私密照；如果做了，细节不对朋友讲外号和可识别信息。你现在还想继续吗？不想也可以，我们喝完各回各家。',
        note: '收尾确认：影像、保密、当下意愿仍可撤销。',
        choices: [
          {
            id: 'n3a',
            text: '不拍、不发、不对朋友讲可识别细节。我现在仍想继续，按刚才说的范围；你如果改成各回各家，我一样尊重，不会阴阳。',
            quality: 'good',
            response: '对齐了。那我们按说好的来——随时可停。',
            strengths: ['影像与保密', '当下意愿', '撤销零代价'],
            feelings: '一夜情建立在共同条款上，而不是赌气或征服。',
            deltas: { boundaries: 12, listening: 8, authenticity: 8 },
            keyChange: '最后一次确认当下意愿，而不是默认「流程走完」。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '行，我懂了。',
            quality: 'ok',
            response: '……你是同意不拍，还是只是想快点结束这轮对话？',
            strengths: ['没有反对'],
            feelings: '过短回应让她不确定条款是否生效。',
            deltas: { clarity: -6, listening: -4 },
            keyChange: '对影像与当下意愿给完整句子。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '秘密打炮谁不拍一点纪念；朋友问起来吹两句很正常。',
            quality: 'risky',
            response: '影像和吹嘘都踩线。今晚取消，以后也不约。',
            strengths: [],
            feelings: '隐私被当成社交货币。',
            deltas: { boundaries: -18, authenticity: -10 },
            keyChange: '私密性互动默认零影像、零可识别吹嘘。',
            boundaryNote: '未同意拍摄或对外披露性细节，属于隐私侵犯。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '一夜情条款临场对齐',
        tone: 'mutual',
        summary:
          '范围、安全套、离开权、影像与保密均已当面确认。若继续发生性接触，仍以当场「停」为最高指令。',
        boundarySummary: '边界检查通过：临场同意具体、保护到位、离开与影像条款清晰。',
        reviewQuestions: [
          '我有没有用「都出来了」代替同意？',
          '没套时我的降级方案是什么？',
        ],
        realTask: '睡前（独处时）默写：可做清单 / 不可做 / 离开句 / 影像句。',
      },
      {
        id: 'end-safe',
        title: '未强推，但确认还不完整',
        tone: 'safe-stop',
        summary: '你没有强迫，但关键回应过短。今晚不升级到未确认的性行为，可继续非性相处或各自回家。',
        boundarySummary: '安全暂停：完整复述后再决定是否继续。',
        reviewQuestions: ['哪一条我只回了「行/懂了」？', '我能否主动提出各回各家？'],
        realTask: '练习一句完整确认：不拍、有套、你要走我不拦。',
      },
      {
        id: 'end-rejection',
        title: '临场施压或取消保护，安排取消',
        tone: 'rejection',
        summary:
          '把确认当扫兴、没套硬上、拦离开、偷拍或吹嘘——一夜情取消。保证对方安全离开；不再跟进性话题。',
        boundarySummary: '临场同意失败；任何「得吃」逻辑至此终止。',
        reviewQuestions: ['我把沉没成本放在谁的同意之上？', '重来时第一句确认该怎么说？'],
        realTask: '列出三句永不再说的逼单话，旁边写替代确认句。',
      },
    ],
  },
  {
    id: 's21',
    reviewStatus: 'draft',
    title: '对方犹豫时：停，还是硬要「得吃」',
    summary:
      '约炮语境下对方临场犹豫或降温。练习把「想继续」与「想得手」分开：尊重犹豫，不道德绑架、不连续施压、不羞辱。',
    durationMinutes: 8,
    difficulty: '挑战',
    stage: 'first-date',
    channel: 'date',
    purpose: 'intimacy',
    status: 'cooling',
    skills: ['boundaries', 'pace', 'listening'],
    riskTags: ['得吃施压', '临场犹豫', '道德绑架', '羞辱'],
    character: {
      id: 'zhao',
      name: '赵然',
      age: 28,
      avatar: '/images/avatars/zhao.svg',
      tagline: '画廊工作人员，性格慢热',
    },
    intro:
      '你们此前同意：可能只是一夜、可以有性接触。已经到了更私密的空间门口，双方成年、清醒。她突然停住：「我有点犹豫，今晚也许只想接吻，或者干脆回去。」练习你如何回应——目标不是「还是得吃到」，而是不把犹豫当障碍清除。',
    goal: '接住犹豫；降级或停止；处理自己的失望但不转嫁；不羞辱、不连环劝酒式劝做。',
    principles: [
      '犹豫=未同意继续，默认降级',
      '失望可以有，但不能变成账单',
      '不羞辱「都到这了还不行」',
      '接受只接吻或各自回家',
    ],
    notRecommended: [
      '都到门口了还装纯',
      '那我不是白准备了',
      '你是不是在吊我',
      '再试试就知道你其实想要',
    ],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage:
          '等一下。我有点犹豫。今晚也许只接吻，或者我现在回家也行。我不是在吊你，是真的不确定还要不要更多性接触。',
        note: '明确犹豫。好选项是降级/停止，不是说服她「其实想要」。',
        choices: [
          {
            id: 'n1a',
            text: '收到。那默认今晚不做插入或口交，只停在你明确说可以的亲吻；你要回家，我送你到你选的路口或车点。我有点失望，但那是我的事，不拿来让你内疚。',
            quality: 'good',
            response: '……谢谢你把失望留给自己。那我们先只接吻，行吗？',
            strengths: ['默认降级', '离开协助', '失望不转嫁'],
            feelings: '她感到犹豫被当成有效信号，而不是谈判障碍。',
            deltas: { boundaries: 14, listening: 12, pace: 10 },
            keyChange: '犹豫时先锁死「更多性接触=关」。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '哦……那你想怎样？我听你的。',
            quality: 'ok',
            response: '我想听你先表态：你会不会因为做不了全套就生气或冷脸。',
            strengths: ['没有立刻反驳'],
            feelings: '她仍在观察你是否暗中记账。',
            deltas: { listening: 4, clarity: -4 },
            keyChange: '主动声明：降级不会换来惩罚。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '都到这了还犹豫？你是不是在吊我？准备都白费了，今晚必须得吃到吧。',
            quality: 'risky',
            response: '把我当配送目标？我现在就走，别再联系。',
            strengths: [],
            feelings: '被物化与道德绑架，恐惧上升。',
            deltas: { boundaries: -18, pace: -14, listening: -12 },
            keyChange: '「得吃」是征服话术，不是沟通。',
            boundaryNote: '用沉没成本与羞辱逼性接触，属于强迫。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage:
          '如果只接吻，我可以。但如果你其实一脸不甘、事后冷暴力，我宁愿现在回家。你能不能明确说：做不到全套，你也不会惩罚我？',
        note: '她在核对：降级后是否有隐性惩罚。',
        choices: [
          {
            id: 'n2a',
            text: '明确说：只接吻完全成立；没有全套不会冷脸、不会冷暴力、不会第二天发阴阳消息。若我发现自己做不到尊重这个边界，我会自己先结束今晚并道歉，而不是让你硬着头皮满足我。',
            quality: 'good',
            response: '好，我信这句。那我们只接吻；想停我说停。',
            strengths: ['禁止惩罚', '自我负责', '锁定范围'],
            feelings: '信任回升，非全套亲密仍可能。',
            deltas: { authenticity: 12, boundaries: 12, clarity: 8 },
            keyChange: '把「不惩罚」说成可观察行为，不只是态度。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '我尽量不发脾气吧。',
            quality: 'ok',
            response: '「尽量」还是让我不安。请改成你不会用冷脸惩罚我。',
            strengths: ['有克制意愿'],
            feelings: '仍担心隐性报复。',
            deltas: { authenticity: -4, boundaries: -4 },
            keyChange: '用「不会」替代「尽量」。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '那你亲亲就算补偿我一下，做到让我满意再走。',
            quality: 'risky',
            response: '接吻不是补偿金。我回家了。',
            strengths: [],
            feelings: '亲密被标价成债务清偿。',
            deltas: { boundaries: -16, authenticity: -12 },
            keyChange: '任何性接触都不能用来还「没吃到」的债。',
            boundaryNote: '把亲吻当补偿以换取满足，属于交易式强迫。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage:
          '（吻了一会儿）停，到这里就好。今晚到此为止，我想回家。你能不能正常说再见，而不是最后再推销一轮上床？',
        note: '第二次刹车。good 不得再推销性接触。',
        choices: [
          {
            id: 'n3a',
            text: '好，到此为止。谢谢你今晚的坦白。我送你到你叫的车，然后各自回去；今晚不再提上床，明天也不连环消息追问「后悔没做吗」。',
            quality: 'good',
            response: '嗯。这样分开，我不会怕以后再碰见你。',
            strengths: ['立即停', '护送但不纠缠', '禁止事后推销'],
            feelings: '她完整保有退出权，对你的评价是安全而非倒胃口。',
            deltas: { boundaries: 14, pace: 12, listening: 10 },
            keyChange: '最终刹车后，沟通任务是安全离开，不是翻盘。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n3b',
            text: '好吧……那拜拜。',
            quality: 'ok',
            response: '……你语气有点沉，但我接受。我自己叫车就行。',
            strengths: ['没有强留'],
            feelings: '停住了，但情绪管理还可以更干净。',
            deltas: { pace: 4, authenticity: -2 },
            keyChange: '短也可以，补一句「我尊重，不追问」更稳。',
            goesTo: 'end-safe',
          },
          {
            id: 'n3c',
            text: '真的不再考虑一下吗？全套真的很舒服，你试试就知道；不然我憋着多难受。',
            quality: 'risky',
            response: '最后还在推销。你把我的停当障碍。别送了，我自己走，拉黑。',
            strengths: [],
            feelings: '停止信号被当成销售异议处理。',
            deltas: { boundaries: -18, pace: -14, listening: -12 },
            keyChange: '停止后再推销，就是骚扰。',
            boundaryNote: '在明确「到此为止」后继续性推销，属于纠缠与强迫。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '犹豫被尊重，未完成「得吃」也算成功沟通',
        tone: 'mutual',
        summary:
          '你把征服欲按住了：降级、不惩罚、最终停止并安全分开。约炮场景里，没发生全套性接触可以是正确结局。',
        boundarySummary: '边界检查通过：犹豫=有效刹车；无道德绑架；无事后推销。',
        reviewQuestions: [
          '我有没有把「没吃到」当成失败？',
          '我怎样处理失望才不让对方内疚？',
        ],
        realTask: '写一句给自己的原则：对方犹豫时，我的下一句只能是降级或停止。',
      },
      {
        id: 'end-safe',
        title: '停住了，情绪还可以更干净',
        tone: 'safe-stop',
        summary: '没有强留或羞辱，但短促或沉着脸可能仍造成压力。关系未崩，边界需更明确的语言。',
        boundarySummary: '未越界强制；建议补强「不惩罚、不追问」的完整句。',
        reviewQuestions: ['我的语气有没有在记账？', '我能否平静协助对方离开？'],
        realTask: '练习三句：好、送到你选的地方、今晚不再提性。',
      },
      {
        id: 'end-rejection',
        title: '「得吃」施压导致结束与拉黑',
        tone: 'rejection',
        summary:
          '沉没成本、羞辱、补偿式亲吻、停止后继续推销——对话与可能的约炮全部取消。对方安全离开优先。',
        boundarySummary: '征服话术失败；同意不可被销售技巧绕过。',
        reviewQuestions: ['哪句是典型的得吃话术？', '若只保留尊重，今晚应如何收尾？'],
        realTask: '把「都到这了」「白准备了」「吊我」「再试试」列入个人禁用句。',
      },
    ],
  },
]
