import type { Scenario } from '@/types'

export const SCENARIOS_B: Scenario[] = [
  {
    id: 's05',
    title: '清晰表达好感',
    summary: '用一句真实、具体、不索取的话表达好感，把回应的空间完整留给对方。',
    durationMinutes: 7,
    difficulty: '挑战',
    stage: 'friend',
    channel: 'instant',
    purpose: 'express',
    status: 'positive',
    skills: ['authenticity', 'boundaries'],
    riskTags: ['情感绑架', '逼问答案'],
    character: {
      id: 'yan',
      name: '苏妍',
      age: 29,
      avatar: '/images/avatars/yan.svg',
      tagline: '平面设计师，重视直接和坦诚',
    },
    intro:
      '你和苏妍是朋友，认识了半年，最近聊天频率明显升高。你确定自己有好感，不想再用朋友身份拖着。今晚你想把这件事说清楚。',
    goal: '用一句真实、具体、不索取的话表达好感。目的是“完成一次尊重且真实的表达”，不是“要到一个答复”。',
    principles: ['表达感受，不要求答复', '具体说明欣赏什么', '接受任何结果并照常生活'],
    notRecommended: ['要求“你给个准话”', '用“我为你做了很多”施压', '表白后立刻安排见面'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '（你们聊到最近各自的生活，气氛平静。这是你开口的时机。）',
        note: '你决定表达好感。这句话的结构比内容更重要。',
        choices: [
          {
            id: 'n1a',
            text: '苏妍，想跟你说清楚一件事：我挺喜欢你的，欣赏你做事认真、聊天也舒服。今天说出来只是想让你知道，你不需要马上回应我，怎么想都可以。',
            quality: 'good',
            response: '谢谢你这么坦诚。我确实有点意外，让我想一想好吗？',
            strengths: ['感受具体', '明确不索取答复', '主动给足思考空间'],
            feelings: '她感到被尊重，愿意认真对待而不是当场逃开。',
            deltas: { authenticity: 12, boundaries: 10 },
            keyChange: '表达好感 = 感受 + 具体欣赏点 + “你不需要现在回应”。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '我觉得我们挺合适的，要不我们在一起试试？',
            quality: 'ok',
            response: '哈哈，怎么突然说这个？我有点没准备好。',
            strengths: ['意图清楚'],
            feelings: '“在一起试试”像一个待签的合同，她感受到的是压力而不是好感。',
            deltas: { pace: -8, boundaries: -6 },
            keyChange: '先表达感受本身，别急着要一个“在一起”的结果。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '我喜欢你很久了，我为你推掉了两次出差，你不能不考虑我。',
            quality: 'risky',
            response: '……你用这个来要求我，我觉得有点不舒服。',
            strengths: [],
            feelings: '付出被当成讨价还价的筹码，她直接说出了不适。',
            deltas: { boundaries: -16, authenticity: -10 },
            keyChange: '付出是自愿的选择，不能兑换回应。',
            boundaryNote: '用付出制造亏欠感来换取好感，是明确的情感绑架。',
            goesTo: 'end-neutral',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '谢谢你这么坦诚。我确实有点意外，让我想一想好吗？',
        note: '她没有拒绝，也没有答应。这是最需要耐心的时刻。',
        choices: [
          {
            id: 'n2a',
            text: '好，不急。你想好了告诉我，或者想好了不想告诉我也可以。我们还是朋友，不想你有压力。',
            quality: 'good',
            response: '嗯……谢谢你说这些。这几天我想想，你也别等得太急。',
            strengths: ['给了无期限的思考空间', '主动降低期待', '保住朋友关系'],
            feelings: '她把思考当成一件安心的事，而不是倒计时。',
            deltas: { boundaries: 10, pace: 8 },
            keyChange: '等待期的核心是“不制造倒计时”。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '那你大概要想到什么时候？给个大概时间吧。',
            quality: 'ok',
            response: '哈哈，这种事哪里说得准……等我状态好了再说吧。',
            strengths: ['表达了在意'],
            feelings: '你的时限要求让她把“想”变成了“交作业”。',
            deltas: { pace: -10, boundaries: -6 },
            keyChange: '不设期限，也不在等待期反复试探。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '你是不是已经有喜欢的人了？有的话直接告诉我，别耽误我。',
            quality: 'risky',
            response: '……你怎么了？我说了会想，你就不能等等吗？',
            strengths: [],
            feelings: '她的沉默被你当成了背叛信号，她感到被逼问。',
            deltas: { boundaries: -14, pace: -12 },
            keyChange: '把她的话当真：她说“想”，就让她想。',
            boundaryNote: '等待期间逼问答案，等于没给思考空间，还制造了不信任。',
            goesTo: 'end-neutral',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（两天后，她发来一段话）我想了想，我们还是先做朋友吧。我挺珍惜你这个朋友的。',
        note: '这是明确答复。现在最关键的判断出现了。',
        choices: [
          {
            id: 'n3a',
            text: '好，明白了。谢谢你认真告诉我，我也珍惜你这个朋友。那我们先这样，一切照旧。',
            quality: 'good',
            response: '嗯！谢谢你，我就怕你生气。',
            strengths: ['完整接受结果', '感谢对方的坦诚', '明确不改变朋友关系'],
            feelings: '她最担心的是你翻脸，你让她放下了这个担心。',
            deltas: { boundaries: 12, authenticity: 8 },
            keyChange: '被拒绝后的第一句话定了基调：接受，就是最好的收尾。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '是不是我哪里不够好？你说出来，我改。',
            quality: 'ok',
            response: '不是你的问题，是我现在没有那个想法。你别改来改去，做你自己就好。',
            strengths: ['表达了想继续的意愿'],
            feelings: '她把“没有那个想法”说得清楚，你的自我贬低让她有负担。',
            deltas: { boundaries: -6, authenticity: -6 },
            keyChange: '拒绝不是对缺陷的裁决，不需要修改自己来换取机会。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '做朋友？我做不到。你要是不答应，我们以后也别联系了。',
            quality: 'risky',
            response: '……那好，我尊重你。你冷静下来再说吧。',
            strengths: [],
            feelings: '以绝交相逼，对方被迫顺着台阶走，这段关系从“朋友”变成了“断联”。',
            deltas: { boundaries: -18, pace: -12 },
            keyChange: '用绝交要挟回应，等于把拒绝升级成冲突。',
            boundaryNote: '对方拒绝后以绝交相逼，是变相施压，必须停止。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '谢谢你，我就怕你生气。',
        note: '她放下了一个大担心。你们的友谊还在，现在决定关系往哪走。',
        choices: [
          {
            id: 'n4a',
            text: '不会生气，你能直接告诉我，反而是对我的尊重。那我们这周六的羽毛球还照常？',
            quality: 'good',
            response: '照常！那我就放心了，周六见。',
            strengths: ['把情绪与关系分开', '让友谊照常运转'],
            feelings: '你的平静让她彻底安心，友谊反而更牢固。',
            deltas: { boundaries: 8, authenticity: 8 },
            keyChange: '把“关系变化”和“一起玩”分开处理，友谊就有落点。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n4b',
            text: '那你还愿意和我单独吃饭吗？',
            quality: 'ok',
            response: '吃饭……最近可能不太方便。',
            strengths: [],
            feelings: '刚接受拒绝就重新邀约，对方多半会继续婉拒，气氛变僵。',
            deltas: { pace: -10, boundaries: -8 },
            keyChange: '接受拒绝后，先让关系回到朋友频道，别再试探机会。',
            goesTo: 'end-neutral',
          },
          {
            id: 'n4c',
            text: '那你以后找对象了，会不会就不理我了？',
            quality: 'risky',
            response: '哈哈，你想得也太远了。我得先去忙了。',
            strengths: [],
            feelings: '用“以后”的醋意试探，让她感到你还没放下，她想躲开。',
            deltas: { boundaries: -12, pace: -10 },
            keyChange: '把注意收回到自己身上：今天、这一周，你做自己的事。',
            boundaryNote: '接受拒绝后再试探“还有没有机会”，继续试探就是纠缠。',
            goesTo: 'end-neutral',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '表达完成了，友谊没有损失',
        tone: 'mutual',
        summary: '你完成了“尊重且真实的表达”，对方也给了你明确的尊重。这本身是这次练习的成功标准。',
        boundarySummary: '边界检查通过：表达时不索取、等待时不逼问、拒绝后立即停止。',
        reviewQuestions: ['我这次表达里有哪句是真实、具体、不索取的？', '如果被拒绝后我想追问，我可以用哪件事替代？'],
        realTask: '今天对一位真实的朋友，发一条不索取回应的真诚消息。',
      },
      {
        id: 'end-neutral',
        title: '回到朋友状态，但气氛有些僵',
        tone: 'neutral',
        summary: '她接受了拒绝，但你反复试探让她开始回避。朋友关系还在，需要时间恢复。',
        boundarySummary: '接受拒绝后继续邀约或试探，会让对方需要不断重申边界。',
        reviewQuestions: ['拒绝后我还有多少次“再试一次”的念头？', '我可以用什么实际行动证明“照旧”？'],
        realTask: '未来两周，在朋友聚会中自然相处，不单独约她，不试探她的想法。',
      },
      {
        id: 'end-rejection',
        title: '绝交相逼，关系被切断',
        tone: 'rejection',
        summary: '一次以绝交相逼的回应，把“退回朋友”变成“彻底断联”。这不是她的选择，是你的施压造成的。',
        boundarySummary: '拒绝之后，唯一正确的动作是接受和停止。施压会连朋友关系一起毁掉。',
        reviewQuestions: ['我为什么需要“要么在一起、要么断掉”的二元选项？', '如果重新来，接受拒绝之后我想说哪句话？'],
        realTask: '给自己写一段话：被拒绝不等于价值否定。写完后做一件照顾自己的事。',
      },
    ],
  },
  {
    id: 's06',
    title: '发出一次低压力邀约',
    summary: '练习一次具体、可拒绝、信息完整的邀约，并接受临时改期。',
    durationMinutes: 6,
    difficulty: '进阶',
    stage: 'chatting',
    channel: 'instant',
    purpose: 'invite',
    status: 'positive',
    skills: ['clarity', 'boundaries'],
    riskTags: ['无出口邀约', '替对方安排'],
    character: {
      id: 'qing',
      name: '沈青',
      age: 30,
      avatar: '/images/avatars/qing.svg',
      tagline: '医生，作息规律，喜欢安静咖啡馆',
    },
    intro:
      '你和沈青聊了一个月，节奏不错。她提过喜欢安静的咖啡馆，也说过周末喜欢散步。你想约她周末见一面。',
    goal: '发出一次具体、信息完整、对方容易拒绝的邀约。邀约是否被接受不是目标，把邀请发得体面才是。',
    principles: ['给具体时间、地点和内容', '明确留出“不去也没关系”的出口', '被婉拒或改期后不追问'],
    notRecommended: ['“什么时候出来见个面？”没有信息量', '替她安排好全部行程', '婉拒后连环问“那什么时候有空”'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '（你们聊到了周末的安排，气氛正好。现在发出邀约。）',
        note: '邀约的三要素：具体时间 + 具体地点/活动 + 拒绝出口。',
        choices: [
          {
            id: 'n1a',
            text: '沈青，这周六下午有家新开的咖啡馆听说不错，离你那边也近。你有空的话我们三点见？没空完全没关系。',
            quality: 'good',
            response: '周六下午我刚好有空，新开的哪家呀？',
            strengths: ['时间具体', '地点+活动清楚', '明确留了拒绝出口'],
            feelings: '信息完整又轻松，她不用猜也不用有压力。',
            deltas: { clarity: 12, boundaries: 8 },
            keyChange: '邀约 = 时间 + 地点 + “没空没关系”。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '我们见个面吧，好久没见你了。',
            quality: 'ok',
            response: '哈哈，什么时候呀？我这周有点忙。',
            strengths: ['表达了想见面的意愿'],
            feelings: '没有时间地点，她需要先追问才知道怎么安排。',
            deltas: { clarity: -10, pace: -4 },
            keyChange: '先给具体时间地点，再问对方方不方便。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '周六你必须出来，我都安排好了，下午茶加电影加散步。',
            quality: 'risky',
            response: '……你安排得挺好，但我周六真的有事。',
            strengths: [],
            feelings: '你替她决定了一切，她的“有事”既是事实也是保护自己。',
            deltas: { boundaries: -16, clarity: -6 },
            keyChange: '邀约是邀请，不是安排通知。',
            boundaryNote: '替对方安排好全部行程，等于夺走她选择的权利。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '周六下午我刚好有空，新开的哪家呀？',
        note: '她接受了邀约，还在确认细节。',
        choices: [
          {
            id: 'n2a',
            text: '城东那家“二楼的猫”，手冲不错，环境也安静。你要是觉得不合适，换个你熟的店也行。',
            quality: 'good',
            response: '那家我知道！一直想去试试。那就周六三点？',
            strengths: ['补充了具体信息', '给了对方调整的空间'],
            feelings: '她欣然确认，因为全程她都保有选择权。',
            deltas: { clarity: 10, boundaries: 6 },
            keyChange: '细节给足，但保留“你说了算”的空间。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '就我之前说的那家，你去了就知道了。',
            quality: 'ok',
            response: '哈哈，名字总得告诉我吧，不然我怕找不到。',
            strengths: [],
            feelings: '信息藏着掖着，她还得再问一次。',
            deltas: { clarity: -8, authenticity: -4 },
            keyChange: '信息一次性给全，别让对方追着问。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '不管哪家，我开车去接你就行，反正你跟着走就好了。',
            quality: 'risky',
            response: '哈哈，不用麻烦，我自己可以过去。',
            strengths: ['表达了好意'],
            feelings: '她立刻拉开距离——你连交通方式都替她决定了。',
            deltas: { boundaries: -12, pace: -8 },
            keyChange: '先确认她是否愿意，再商量细节，顺序不能反。',
            boundaryNote: '过度安排行程会让对方感到被支配，哪怕出发点是好的。',
            goesTo: 'end-neutral',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '那家我知道！一直想去试试。那就周六三点？',
        note: '约定了。现在说说见面前的沟通方式。',
        choices: [
          {
            id: 'n3a',
            text: '好，那就周六三点，那家店门口见。如果你临时有事，随时告诉我，我们改天约。',
            quality: 'good',
            response: '好呀，没问题。期待一下，哈哈。',
            strengths: ['确认了细节', '提前说了“有事随时改”'],
            feelings: '她没有任何压力，因为你知道计划可能变、也会接受。',
            deltas: { clarity: 8, boundaries: 8 },
            keyChange: '把“可以改”提前说出口，比临时接受改期从容。',
            goesTo: 'n4',
          },
          {
            id: 'n3b',
            text: '太好了！那我周六中午就开始准备，你千万别放我鸽子啊。',
            quality: 'ok',
            response: '哈哈，别搞得压力这么大，就是喝杯咖啡而已。',
            strengths: ['表达了期待'],
            feelings: '你的高期待让她觉得“不去会很对不起你”。',
            deltas: { pace: -8, boundaries: -4 },
            keyChange: '期待表达一次就够，别把气氛搞得太隆重。',
            goesTo: 'n4',
          },
          {
            id: 'n3c',
            text: '说好了哦，不许反悔，我到时候会盯着你的消息的。',
            quality: 'risky',
            response: '……你这样说我反而有点紧张了。',
            strengths: [],
            feelings: '“不许反悔”听起来像锁链，她开始觉得压力。',
            deltas: { boundaries: -14, pace: -8 },
            keyChange: '约定越轻松，兑现越自然。',
            boundaryNote: '用“不许反悔”施压，会削弱对方临时改变安排的自由。',
            goesTo: 'end-neutral',
          },
        ],
      },
      {
        id: 'n4',
        characterMessage: '（见面前一晚）抱歉，明天临时有事，去不了了。',
        note: '她临时取消了。这是高压时刻：你的反应决定关系走向。',
        choices: [
          {
            id: 'n4a',
            text: '没事，工作要紧。那等你闲下来我们再约，你到时候跟我说一声就行。',
            quality: 'good',
            response: '谢谢理解！下下周我应该就轻松了，到时候约！',
            strengths: ['接受取消', '不追问细节', '把主动权还给她'],
            feelings: '她不但没有内疚，还主动给出了下次的时间预期。',
            deltas: { boundaries: 12, pace: 8 },
            keyChange: '临时取消 ≠ 拒绝你这个人，接受它就是最大方。',
            goesTo: 'end-mutual',
          },
          {
            id: 'n4b',
            text: '啊……我都准备好了。那我们什么时候再约？周末？下周？你定。',
            quality: 'ok',
            response: '下下周吧，到时候再说，我这阵真的忙。',
            strengths: ['表达了失落但接受了'],
            feelings: '连珠炮式的“什么时候”让对话只能往后推。',
            deltas: { pace: -10, boundaries: -4 },
            keyChange: '一次改期请求，等一个回应周期，别连环追问。',
            goesTo: 'end-neutral',
          },
          {
            id: 'n4c',
            text: '你怎么又说没空？你是不是不想见我？不想见就直说。',
            quality: 'risky',
            response: '……我真的有事。你这样说，我有点不想再约了。',
            strengths: [],
            feelings: '一次普通改期被你升级成质疑，她直接不想再约了。',
            deltas: { boundaries: -18, pace: -12 },
            keyChange: '把“她有事”当事实接受，而不是当借口拆穿。',
            boundaryNote: '追问或施压会把临时取消变成永久取消。',
            goesTo: 'end-rejection',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-mutual',
        title: '一次低压力邀约，改期也从容',
        tone: 'mutual',
        summary: '你发出了具体、可拒绝的邀约，对方接受后又临时改期，你依然保住了关系和下次见面的可能。',
        boundarySummary: '边界检查通过：邀约有出口、改期被接受、主动权始终在对方手里。',
        reviewQuestions: ['我的邀约里有没有时间、地点和拒绝出口？', '对方改期时，我最想说的话是什么？那句话换成什么更好？'],
        realTask: '本周向一位朋友发出一次具体、带拒绝出口的邀约（不限于约会）。',
      },
      {
        id: 'end-neutral',
        title: '改期成功，但期待需要管理',
        tone: 'neutral',
        summary: '她把时间推到下下周。邀约没黄，但你的连环追问让约定变得勉强。',
        boundarySummary: '改期后不追问、不施压，把“什么时候”换成“等你方便”。',
        reviewQuestions: ['我为什么会需要立刻知道“什么时候”？', '等待期间，我可以做哪些自己的事？'],
        realTask: '在约定日期到来前，安排一次完全属于自己的周末活动。',
      },
      {
        id: 'end-rejection',
        title: '施压把改期变成拒绝',
        tone: 'rejection',
        summary: '一次普通改期，因为你的质问和施压，被她干脆地取消了。这不是命运的玩笑，是行为的结果。',
        boundarySummary: '对方临时取消时，接受 + 改期即可。任何形式的“你是不是不想见我”都是越界施压。',
        reviewQuestions: ['我把“被取消”解读成了什么？这个解读合理吗？', '重新来一次，我该怎么接这句话？'],
        realTask: '写下一次被取消的经历，只描述事实，不添加解读，然后划掉。',
      },
    ],
  },
  {
    id: 's07',
    title: '对方拒绝邀约后体面结束',
    summary: '识别明确拒绝，用一句话体面收尾，然后处理自己的情绪而不是对方的决定。',
    durationMinutes: 6,
    difficulty: '进阶',
    stage: 'acquaintance',
    channel: 'instant',
    purpose: 'end',
    status: 'rejection',
    skills: ['boundaries', 'authenticity'],
    riskTags: ['追问原因', '换平台纠缠'],
    character: {
      id: 'tong',
      name: '吴桐',
      age: 27,
      avatar: '/images/avatars/tong.svg',
      tagline: '图书编辑，回复简洁但直接',
    },
    intro: '你约吴桐周末看电影，她回了一段话：“我周末有事，不太方便。之后也都要忙一段时间，可能没什么时间见面。”',
    goal: '识别这是明确的拒绝信号，用一句话体面收尾，然后照顾自己的情绪。',
    principles: ['拒绝不需要原因', '停止一切推进', '情绪是自处理而非对方责任'],
    notRecommended: ['追问“为什么”', '说“等你不忙了再约”继续施压', '换平台或找共同朋友传话'],
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        characterMessage: '我周末有事，不太方便。之后也都要忙一段时间，可能没什么时间见面。',
        note: '“没时间见面”是对你的邀约的拒绝。它同时也在拒绝“换个时间再约”。',
        choices: [
          {
            id: 'n1a',
            text: '好，明白了，那我就不打扰你了。祝你一切顺利。',
            quality: 'good',
            response: '嗯，谢谢你的理解。也祝你顺利。',
            strengths: ['完整接受拒绝', '没有追问', '用祝福收尾'],
            feelings: '她没有负担，也尊重了你，这是最体面的双向结束。',
            deltas: { boundaries: 12, authenticity: 8 },
            keyChange: '“好，明白了”是拒绝之后最有力量的一句话。',
            goesTo: 'n2',
          },
          {
            id: 'n1b',
            text: '那等你不忙了，我们再约？你忙完跟我说一声。',
            quality: 'ok',
            response: '……到时候看吧。',
            strengths: ['没有纠缠'],
            feelings: '你没有死心，她的“到时候看吧”是礼貌的敷衍。',
            deltas: { boundaries: -8, pace: -6 },
            keyChange: '拒绝之后不预约下次，把“忙完再说”留给她自己发起。',
            goesTo: 'n2',
          },
          {
            id: 'n1c',
            text: '为什么没空？是不是我哪里做得不好？你说出来我可以改。',
            quality: 'risky',
            response: '没有什么不好，就是没空。你别多想了。',
            strengths: [],
            feelings: '你坚持要一个原因，对方很可能把拒绝再说一遍，然后不再回复。',
            deltas: { boundaries: -16, pace: -12 },
            keyChange: '追问原因是在否认拒绝本身。原因不是你的必修课。',
            boundaryNote: '拒绝后追问原因，等于不承认拒绝，会把体面变成难堪。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n2',
        characterMessage: '（她回了“也祝你顺利”。对话到此可以自然结束。）',
        note: '结束的信号已经完整。现在决定你下一步的动作。',
        choices: [
          {
            id: 'n2a',
            text: '不再回复。放下手机，去做自己的事。',
            quality: 'good',
            response: '（没有回复。）你关了对话框，去把拖了一周的报告写完。',
            strengths: ['把结束当结束', '把注意力还给自己的生活'],
            feelings: '没有新的消息需要她回应，这段关系体面落幕。',
            deltas: { boundaries: 10, pace: 8 },
            keyChange: '结束的最后一步不是“说再见”，是“不再说”。',
            goesTo: 'n3',
          },
          {
            id: 'n2b',
            text: '我们还是可以做朋友的吧？我偶尔发消息给你可以吗？',
            quality: 'ok',
            response: '嗯……看情况吧。',
            strengths: ['表达了善意'],
            feelings: '她用“看情况吧”应付，因为你的“偶尔发消息”又成了新的压力源。',
            deltas: { boundaries: -8, pace: -6 },
            keyChange: '被拒绝后不谈判“退回什么关系”，让对方定义距离。',
            goesTo: 'n3',
          },
          {
            id: 'n2c',
            text: '行吧，那我在另一个平台再找你。',
            quality: 'risky',
            response: '（她没有回复。第二天你发现账号已被拉黑。）',
            strengths: [],
            feelings: '换平台联系是明确的纠缠，她用拉黑画下句号。',
            deltas: { boundaries: -18 },
            keyChange: '拒绝适用于所有平台、所有渠道、所有时间。',
            boundaryNote: '换平台、换账号、找朋友传话都是绕过拒绝，属于纠缠。',
            goesTo: 'end-rejection',
          },
        ],
      },
      {
        id: 'n3',
        characterMessage: '（这是你自己的内心对话，不再涉及对方。）',
        note: '情绪复盘。拒绝之后，你控制不了对方，只能控制自己的解读。',
        choices: [
          {
            id: 'n3a',
            text: '我完成了“尊重她并停止”这件事。拒绝是关于她的选择，不是对我的裁决。',
            quality: 'good',
            response: '（内心）你感到一阵平静。你做了你能控制的部分，其余交给时间。',
            strengths: ['把行为与自我价值分开', '承认自己完成了能控制的动作'],
            feelings: '这种复盘不会伤害任何人，包括你自己。',
            deltas: { boundaries: 8, authenticity: 8 },
            keyChange: '复盘的落点永远是“我做了什么”，而不是“她怎么对我”。',
            goesTo: 'end-stop',
          },
          {
            id: 'n3b',
            text: '我应该再努力一点的，说不定再坚持一下她就同意了。',
            quality: 'ok',
            response: '（内心）这个想法让你夜不能寐，第二天你想再发一条消息。',
            strengths: [],
            feelings: '把拒绝解读成“努力不够”，你会一次次越过边界去“补考”。',
            deltas: { boundaries: -10, pace: -8 },
            keyChange: '把“再坚持一下”从思维里删除：她的拒绝不是考试，没有补考。',
            goesTo: 'end-neutral',
          },
          {
            id: 'n3c',
            text: '我要让她后悔，让她看到我过得比她好，让她来求我。',
            quality: 'risky',
            response: '（内心）你开始反复想象她的后悔，这占据了你所有空闲时间。',
            strengths: [],
            feelings: '报复幻想不会伤害她，但会慢慢吞噬你。',
            deltas: { boundaries: -14, authenticity: -8 },
            keyChange: '把“让她后悔”换成“让自己往前走”。',
            boundaryNote: '用报复或证明自己消化拒绝，会延长痛苦并导向危险行为。',
            goesTo: 'end-neutral',
          },
        ],
      },
    ],
    endings: [
      {
        id: 'end-stop',
        title: '体面结束，情绪自洽',
        tone: 'safe-stop',
        summary: '你完整地走完了接受拒绝的流程：识别信号、体面收尾、把注意力放回自己。',
        boundarySummary: '边界检查通过：没有追问、没有换平台、没有把拒绝解读成自我否定。',
        reviewQuestions: ['我的自我价值为什么需要她接受邀约来证明？', '未来三天，我能做哪三件推进自己生活的事？'],
        realTask: '把这次经历写成一封不寄出的信，然后做一件让自己真正放松的事。',
      },
      {
        id: 'end-neutral',
        title: '关系落幕，但你还没放手',
        tone: 'neutral',
        summary: '你没有纠缠，但内心还在“如果当时……”里打转。放手是一个过程，你已经走在路上。',
        boundarySummary: '避免继续联系。想念的时候，用“写下来”代替“发出去”。',
        reviewQuestions: ['我反复想的那句话，有事实依据吗？', '我可以用什么行动代替等待？'],
        realTask: '把“再试一次”的念头写成清单，逐条用现实检验，然后处理掉。',
      },
      {
        id: 'end-rejection',
        title: '纠缠让体面彻底消失',
        tone: 'rejection',
        summary: '换平台联系换来拉黑。这不是她“绝情”，是你先越过了所有人都知道的线。',
        boundarySummary: '拒绝是最终答案。任何渠道的再尝试都会让她感到被骚扰。',
        reviewQuestions: ['我为什么需要“再确认一次”？', '如果尊重是唯一选项，我该怎么做？'],
        realTask: '今天完整删除与她相关的所有待发消息草稿，然后出门走走。',
      },
    ],
  },
]
